### PR TITLE
Return can take many arguments

### LINKED ISSUE #3223: `on_const` not being called for second arg of `return`
## Expected behavior
`on_const` is called for this program

```
$ cat a.rb
def foo
  return A, B
end
$ ruby-parse a.rb
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.8-compliant syntax, but you are running 2.1.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(def :foo
  (args)
  (return
    (const nil :A)
    (const nil :B)))
```

## Actual behavior
`on_const` isn't called

## Steps to reproduce the problem

Write a rubocop rule with a `on_const` and see it isn't called for `B`.

## RuboCop version

Include the output of `rubocop -V`:

```
$ rubocop -V
0.40.0 (using Parser 2.3.1.0, running on ruby 2.1.2 x86_64-darwin15.0)
```

### PR DESCRIPTION
**Pull request by ptarjan**
Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it)
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

### CODE REVIEW

**Comment by jonas054** [comment]
We always start commit messages with a capital letter. Other than that, it looks fine.

**Comment by ptarjan** [comment]
updated

**Comment by jonas054** [comment]
:+1:

**Comment by bbatsov** [comment]
Prefix the second commit title with `[Fix #3223]` and we're good to go.

**Comment by ptarjan** [comment]
@bbatsov done

**Comment by bbatsov** [comment]
👍

**Pull request merged**
