### PR TITLE
Fixin the bugs like that

### PR DESCRIPTION
**Pull request by alexdowad**
I haven't been around for a while, and come back to discover **122** open issues have accumulated. C'mon, guys, try to fix bugs once and a while rather than just adding, adding, and adding some more, OK?

### CODE REVIEW

**Comment by bbatsov** [comment]
The new code generates some RuboCop offenses.

**Comment by alexdowad** [comment]
Yep, I'll fix it up soon. No time right now, sorry.

**Comment by bbatsov** [comment]
Take your time.

**Comment by jonas054** [comment]
:+1: All changes look good to me.

**Comment by alexdowad** [comment]
Thanks for review, @jonas054. I'll see if I can fix up those last remaining style problems tonight.

**Comment by alexdowad** [comment]
Should be good now. Let's just make sure the CI build passes.

**Comment by bbatsov** [comment]
👍

**Comment by alexdowad** [comment]
Thanks @bbatsov. Now there are only **107** open issues... gulp...

**Comment by bbatsov** [comment]
Next week I might get to squashing a few of those myself. Too much work, too little time for anything else...

**Pull request merged**
