### PR TITLE
[Fix #4910] add examples for Layout/EmptyLines

### PR DESCRIPTION
**Pull request by fidelscodes**
Adds examples for the `Layout/EmptyLines` cop.

Enabled by default | Supports autocorrection
--- | ---
Enabled | Yes

This cops checks for two or more consecutive blank lines.

### Example

```ruby
# bad
def method_name
  puts 'hello world'


end

if a > b


  a
end

# good
def method_name
  puts 'hello world'
end

if a > b
  a
end
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by pocke** [comment]
Hmm... maybe YARD or RuboCop's code omits consecutive empty lines while the task generates the documentation.

**Comment by bbatsov** [comment]
@fidelscodes Can you please rebase your PR on top of the current `master`?

**Comment by pocke** [comment]
Examples for this cop have already been added in https://github.com/bbatsov/rubocop/pull/5002 . So I think we can close this pull-request.

**Comment by bbatsov** [comment]
@pocke Roger that! 

@fidelscodes Thanks anyways and sorry we can't merge your PR! Looking forward to more contributions from you!

**Pull request closed without merging**
