### PR TITLE
Fix bugs in IfUnlessModifier

### PR DESCRIPTION
**Pull request by jonas054**
It's not entirely clear how best to handle comments around `if` statements when changing them to modifier form. I came to the conclusion that EOL comments right after the condition can be transferred by auto-correct, but comments after `end` need to be looked at by a person. See if you agree.

### CODE REVIEW

**Comment by bbatsov** [comment]
Have a look at the failing build, please.

**Comment by jonas054** [comment]
Thanks for the reminder! I took the easy way out this time and just upped the `MethodLength: Max`. I will do a refactoring PR later that brings it back down.

**Comment by bbatsov** [comment]
You'll also have to rebase this.

**Comment by jonas054** [comment]
Rebased.

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
