### PR TITLE
Fix config#check to use loaded_path in warning

### PR DESCRIPTION
**Pull request by chrishulton**
Due to a configuration refactor, the `#path` variable is no longer
available in `config#check`, which causes rubocop to crash with
`NameError: undefined local variable or method path` if the deprecation
check yields a deprecation warning.

This replaces the warning to use the instance variable `#loaded_path`
and adds a spec to cover the behavior.

-----------------

This is a small bug that looks to have been introduced with [this commit](https://github.com/bbatsov/rubocop/commit/a8dac501c1361d4e7e92e75cd18326ea27ae68fd
) and is impacting version 0.52.

Without the code change, the spec fails with:
```
 NameError:
   undefined local variable or method `path' for #<RuboCop::Config:0x007fe191cc9a00>
 # ./lib/rubocop/config.rb:198:in `block in check'
 # ./lib/rubocop/config.rb:288:in `block in deprecation_check'
 # ./lib/rubocop/config.rb:282:in `each'
 # ./lib/rubocop/config.rb:282:in `deprecation_check'
 # ./lib/rubocop/config.rb:197:in `check'
 # ./spec/rubocop/config_spec.rb:533:in `block (4 levels) in <top (required)>'
```

This is also reproducible by defining the configuration:
```
AllCops:
  Excludes:
    - 'path'
```
which results in an exit with the `NameError` described above.

Please let me know if I should add anything else to this PR!  Thanks!

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by volmer** [comment]
Thank you! I was experiencing the same problem. I hope the gem gets patched soon 🙏

**Comment by bbatsov** [comment]
The change looks good to me. I'll leave it to @jonas054 to review it as well before merging this patch , though, as he worked on the change that caused the bug.

**Comment by bbatsov** [comment]
P.S. This needs a changelog entry.

**Comment by chrishulton** [comment]
Thanks, changelog added.

**Comment by jonas054** [comment]
Yes, that was my fault. I missed that variable when I moved the method. The change looks good! :+1:

**Pull request merged**
