### PR TITLE
[Proposal] Display cop names by default

### PR DESCRIPTION
**Pull request by pocke**
Problem
===

I believe `--display-cop-names` is very useful option, but it is disabled by default.
Cop names are very important in using RuboCop. For example, searching with cop names, bug reporting to rubocop with cop names.
So I think RuboCop should display cop names by default.

Many linters have same behaviour, for instance:

- Reek
    ```
    test.rb -- 3 warnings:
      [2, 3]:DuplicateMethodCall: x calls 'foo.foo' 2 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
      [1]:UncommunicativeMethodName: x has the name 'x' [https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Method-Name.md]
      [1]:UtilityFunction: x doesn't depend on instance state (maybe move it to another class?) [https://github.com/troessner/reek/blob/master/docs/Utility-Function.md]
    ```
- ESLint
    ```
    /tmp/tmp.GhjIgnTwAu/test.js
      1:5  error  'a' is defined but never used  no-unused-vars
      1:9  error  Missing semicolon              semi

    ✖ 2 problems (2 errors, 0 warnings)
    ```
- stylelint
    - https://stylelint.io/#example-output

  

Solution
===

I propose to make `--display-cop-names` option to enable by default.

- Make `--display-cop-names` to enable by default.
- Add `--no-display-cop-names` option to disable displaying cop names.

----

- [x] Add an entry to the changelog
- [x] Fix the failing tests
- [x] Fix the rubocop's offences
  - maybe many "Line is too long" exist.
- [x] Update the manual.

What do you think?

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by Drenmi** [comment]
I tend to agree with this. 🙂 Another, related issue which has bothered me is that re-running with `-D` seems to clear the cached result, which is completely useless. 😅

**Comment by rrosenblum** [comment]
@Drenmi I don't think I have ever run into an issue with `-D` clearing the cache before. 


```
rrosenblum@C02NV0KSG3QN:~/work/rubocop (master u=)$ time b rubocop -D lib/rubocop/cop/rails --cache false
Inspecting 36 files
....................................

36 files inspected, no offenses detected
bundle exec rubocop -D lib/rubocop/cop/rails --cache false  1.77s user 0.10s system 98% cpu 1.890 total
rrosenblum@C02NV0KSG3QN:~/work/rubocop (master u=)$ time b rubocop -D lib/rubocop/cop/rails              
Inspecting 36 files
....................................

36 files inspected, no offenses detected
bundle exec rubocop -D lib/rubocop/cop/rails  0.76s user 0.17s system 97% cpu 0.957 total
rrosenblum@C02NV0KSG3QN:~/work/rubocop (master u=)$ time b rubocop -D lib/rubocop/cop/rails
Inspecting 36 files
....................................

36 files inspected, no offenses detected
bundle exec rubocop -D lib/rubocop/cop/rails  0.74s user 0.17s system 97% cpu 0.934 total

rrosenblum@C02NV0KSG3QN:~/work/rubocop (master u=)$ b rubocop -V
0.51.0 (using Parser 2.4.0.0, running on ruby 2.4.2 x86_64-darwin16)

```

It worked fine for me running against master. Did you have other options enabled when ran into the issue?

**Comment by Drenmi** [comment]
@rrosenblum: What I meant was when you run without `-D` first, then run again using `-D`. Nothing changed, so it would be reasonable to believe it could just use the cache and display the cop names. 🙂

**Comment by pocke** [comment]
> I tend to agree with this. :slightly_smiling_face: Another, related issue which has bothered me is that re-running with -D seems to clear the cached result, which is completely useless. :sweat_smile:

We can add `display_cop_names` to here.
https://github.com/bbatsov/rubocop/blob/3122cc78df8716c9fdfc93ee7098e0ae69a11866/lib/rubocop/result_cache.rb#L10-L11

But unfortunately it does not work.
`add_offense` method create a new offense with an annotated offense message.
https://github.com/bbatsov/rubocop/blob/3122cc78df8716c9fdfc93ee7098e0ae69a11866/lib/rubocop/cop/cop.rb#L194-L198
So rubocop caches "annotated" messages.
To cache with `-D`, rubocop should annotate after caching.

For example:

```ruby
# cop.rb
def add_offense
  Offense.new(message: not_annotated_message)
end

# offense.rb
def message
  MessageAnnotator.annotate(@message)
end
```

**Comment by pocke** [comment]
It's all done!
@bbatsov  Can you review this pull-request?

**Comment by bbatsov** [comment]
Looks good overall. But if we're making this mainstream I want us to make one more change - color cops (possibly different colors for different cop groups) for the cop names stand out more in the messages.

**Comment by pocke** [comment]
Thank you.

> But if we're making this mainstream I want us to make one more change - color cops (possibly different colors for different cop groups) for the cop names stand out more in the messages.

Sorry, I'm not sure what did you mean. 
I guess  cop names, right?

before


after


It is reasonable to me. But I think we should implement it on another pull-request.

**Comment by bbatsov** [comment]
> I guess cop names, right?

Yeah, that's what I meant.

> It is reasonable to me. But I think we should implement it on another pull-request.

Fine by me.

**Pull request merged**
