### PR TITLE
Add Lint/MissingRequireStatement Cop

### PR DESCRIPTION
**Pull request by milch**
This cop checks for implicit dependencies by checking whether your code is missing any require statements. I created this because I've found a need for it over at [fastlane](https://github.com/fastlane/fastlane): many parts of fastlane were architected like this 

```ruby
# in tool/lib/tool/fileA.rb

require 'spaceship'

module Tool
  class A
    def use()
      Spaceship.login(...)
      # ...
    end
  end
end

# in tool/lib/tool/fileB.rb

module Tool
  class B
    def use()
      Spaceship.login(...)
      A.new.use(...)
      # ...
    end
  end
end

# in tool/lib/tool.rb

require 'fileA'
require 'fileB'

```

As you can see, while this works, it only does so incidentally, since the requires in `tool/lib/tool.rb` are ordered 'correctly'. If someone removes `fileA`, changes the order of the requires or tries to do `require 'tool/fileB'` they will get a crash. This has caused many hard-to-debug errors in the fastlane codebase and results in issues such as fastlane/fastlane#11027

With this cop enabled this error would be caught right during development of `fileB`, because the cop would show an error on the `Spaceship.login` line:

```
`Spaceship` not found, you're probably missing a require statement or there is a cycle in your dependencies
```

It does this by breaking the file down to a "timeline" of constant accesses, definitions, assignments and requires. Then it forks a new process so as not to pollute the ruby process running rubocop and processes the timeline in order, requiring the files that were required in the source file. 

I ran this on the whole fastlane codebase, and it enabled me to fix missing requires there (it's not done yet, but the first iteration touching over 300 source files is now merged). The ability to more confidently require submodules instead of whole modules because of this cop also resulted in an average decrease in startup time of around 20%. As a tradeoff, on my laptop rubocop takes about 1 minute longer with this cop enabled on fastlane (around 1000 source files). With cache enabled the additional time is usually negligible. 

This cop should probably be disabled by default, because it is not applicable to e.g. rails projects that automatically require all the source files in the project. For most CLI projects and libraries it is probably a good idea to enable, but I'm curious to hear what people think. 

Edit: I would've liked to break up the code a bit more, e.g. having the `State` class in a separate file, but I didn't know whether there is a directory for putting helper classes like that or if all cops should be self-contained

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1]. (I hope) 
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists). (There's no related issue)
* [x] Feature branch is up-to-date with `master` (if not - rebase it). (just rebased)
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation. (I get errors, but in unrelated files?) 

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by milch** [comment]
Ah, one thing I forgot: I don't know how the policy here is on having one cop emit multiple kinds of warning messages, but this cop could trivially also emit errors for when there is a superfluous require statement, if that is also something people want

**Comment by milch** [comment]
Hmm, I suppose `fork` is not available on Windows, which is why it is failing there. I don't really have a Windows machine to test on. Are all cops required to to be working on both Windows and macOS/Linux, or is there a way to make some available per-platform?

**Comment by bbatsov** [comment]
> Hmm, I suppose fork is not available on Windows, which is why it is failing there. I don't really have a Windows machine to test on. Are all cops required to to be working on both Windows and macOS/Linux, or is there a way to make some available per-platform?

Ideally yes, but if this can't be done without forking I guess we can make the cop a no-op on Windows.

**Comment by milch** [comment]
@pocke 

> 1. RuboCop is a static analyzer. So I think it should not load ruby scripts that are analyzed. So the cop needs to allow false positives / negatives.

Understandable. In my opinion, ruby is a dynamic language and therefore some analysis might require a more dynamic approach to be useful, like this one. The only aspect of the analysed file that is actually executed are the requires, and those are contained in a separate process 

The value of this tool would certainly be greatly diminished if it had no way of accounting for constants that are defined in required files, but if you think that it does not fit rubocop's core vision feel free to close this PR and I'll create an extension instead

> 2. Use visitor pattern that is provided RuboCop instead of process_* methods. We can use on_* method. (e.g. on_const is called on const node.)

That was what I was doing in the beginning, but I ran into some limitations. For example, if I am processing an AST that looks like this 

```
(const
    (const
      (const nil :A) :B) :C)
```

I have to extract the full `A::B::C` when I'm at the outermost `C` node. When I used the `on_const` callback the function would be called for the `A`, `B` and `C` nodes separately, whereas my code skips the `A` and `B` nodes because they have already been processed after visiting the `C` node. It could certainly be done by having an instance variable with a list of nodes to skip, that nodes would have to be added to recursively, but I found that this approach is cleaner and simpler. I also don't think there would be a simple way to push "meta"-nodes to the stack as is done [here](https://github.com/bbatsov/rubocop/pull/5411/files#diff-9106129ea4987584376e90b022ec9401R138) for example

Another limitation that I ran into was that with the `on_*` methods I couldn't find a way to have code run after the file is done analysing. I use this to group the encountered errors together because they often happen lots of times in the same file, which results in a high noise ratio, and also so fork only has to happen once per file

@bbatsov 

> Ideally yes, but if this can't be done without forking I guess we can make the cop a no-op on Windows.

I think it could be done on Windows (and JRuby, it seems) by moving the part inside fork into a separate file that is then opened with something like `Open3.popen2`. Would have to do more research, though.

**Comment by milch** [comment]
Because of the issues that have been brought up I've decided to release this as an extension instead: https://github.com/milch/rubocop-require_tools

@pocke Is it alright if I submit a PR to list this under the ["Known Custom Cops"](https://github.com/bbatsov/rubocop/blob/1a7c066128df0418ce6ff6aba4fbe1aec80ead8e/manual/extensions.md#known-custom-cops) section in the manual?

**Comment by pocke** [comment]
Sorry for my late response.

> @pocke Is it alright if I submit a PR to list this under the "Known Custom Cops" section in the manual?


Yes 👍

**Pull request closed without merging**
