### PR TITLE
Make Lint/BlockAlignment cop configurable

### PR DESCRIPTION
**Pull request by panthomakos**
Added enforced configurable styles to this cop.

### CODE REVIEW

**Comment by jonas054** [comment]
The cop seems to be doing the same job as `Lint/BlockAlignment`, which BTW accepts two styles instead of being configurable.

**Comment by panthomakos** [comment]
@jonas054 I've looked through the tests for `Lint/BlockAlignment`. I think there is an opportunity for some of the functionality that my change is providing. In particular, `Lint/BlockAlignment` is very permissive which means that if we do in fact want to enforce stricter alignment rules we cannot do so in the current state of the system.

I can make slight modifications to the `Lint/BlockAlignment` spec and have the tests pass for `Lint/DoEndAlignment`. For example:

`Lint/BlockAlignment` has the following spec:

```
  context 'on an arithmetically negated method call' do
    it 'aligns end with the - operator' do
      inspect_source(cop,
                     ['def abc',
                      '  @abc ||= A[-xyz { |x|',
                      '               x',
                      '             }.flatten]',
                      'end'])
      expect(cop.offenses).to be_empty
    end
  end
```

But the cop is permissive enough that the following (which is the result of auto-correcting or enforcing `Lint/DoEndAlignment` with `AlignWith: do`) also works:

```
  context 'on an arithmetically negated method call' do
    it 'aligns end with the - operator' do
      inspect_source(cop,
                     ['def abc',
                      '  @abc ||= A[-xyz { |x|',
                      '               x',
                      '  }.flatten]',
                      'end'])
      expect(cop.offenses).to be_empty
    end
  end
```

This means that the cops are never really in opposition it's just that adding `Lint/DoEndAlignment` allows a stricter enforcement of rules.

What are your thoughts on this?  How would you recommend I proceed?

My ultimate goal (at least in projects I work on) would be to never use `Lint/BlockAlignment` because it is too complex and permissive. I would greatly prefer to enforce rules that ensure that multi-line blocks live on their own lines and are more easily structured. For instance, instead of even allowing:

```
def abc
  @abc ||= A[-xyz { |x|
    x
  }.flatten]
end
```

I would rather enforce something along these lines:

```
def abc
  @abc ||= A[
    -xyz { |x|
      x
    }.flatten
  ]
end
```

In order to do this though I need to be able to enforce `end` and `}` alignment more strictly.

**Comment by jonas054** [comment]
I definitely don't want two cops with the the same basic responsibilities, but I also think you're right in wanting strict rules. First option should be to just make `Lint/BlockAlignment` more strict and configurable.

**Comment by panthomakos** [comment]
@jonas054 That sounds like a good approach to me. I'll take a look at implementing this functionality w/in `Lint/BlockAlignment`.

**Comment by panthomakos** [comment]
@jonas054 I am running into an issue with the following test case and I was wondering if you could help me. I am guessing that you have run into this before with other cops.

I want to auto-correct the following code by aligning the `end`s with the do lines. The way parsing happens, the last block `select do |stuff| stuff.third end` gets auto-corrected first, then the second block and finally the first. This means that the `end` of the second block gets aligned with the misaligned `end` of the first block so that when the first block gets auto-corrected the second block has a misaligned end.

Before:
```
bar.get_stuffs
  .reject do |stuff|
    stuff.first
    end.select do |stuff|
    stuff.second
end
  .select do |stuff|
    stuff.third
    end
```

After:
```
bar.get_stuffs
  .reject do |stuff|
    stuff.first
  end.select do |stuff|
    stuff.second
    end
  .select do |stuff|
    stuff.third
  end
```

Is there a way to reverse the parsing order or to re-parse once something changes? I am not sure how to handle this use-case.

**Comment by jonas054** [comment]
What happens in a real run, I mean not in a test case for the cop, will auto-correction get it right in the end? If so, then I think we can live with it.

**Comment by panthomakos** [comment]
@jonas054 Okay, I finally am betting back to this PR and it looks like it works properly w/ live data. I'll adjust the tests so they aren't combined and I'll update.

**Comment by panthomakos** [comment]
@jonas054 I have taken your advice and modified the `Lint/BlockAlignment` cop. It now supports 3 different enforced styles. PTAL

**Comment by bbatsov** [comment]
Btw, this time we really have conflicts on `master`. Recently we merged other modifications to this cop.

**Comment by panthomakos** [comment]
The conflicts are all from #2900 which duplicates the work done here. This change is no longer needed.

**Pull request closed without merging**
