### PR TITLE
Fix misspelling of Integer

### PR DESCRIPTION
**Pull request by swrobel**

### CODE REVIEW

**Comment by pocke** [comment]
Can you execute `rake generate_cops_documentation`? It will fix the failing CI.

**Comment by swrobel** [comment]
Sorry, wasn't sure if I needed to do that or if it happened automatically.

**Comment by mikegee** [comment]
LGTM! Squashing these commits would be super if you could do that too.

**Comment by swrobel** [comment]
Squashed

**Comment by bbatsov** [comment]
Thanks! 👍

**Pull request merged**
