### PR TITLE
[Fix #3247] Ensure whitespace after beginning of block in Style/BlockDelimiters

### LINKED ISSUE #3247: Should Style/BlockDelimiters auto-correct introduce whitespace after do?
Given code like this:

```
foo.detect {|f|
  FOO.include? f
}
```

The autocorrect of `Style/BlockDelimiters` cop creates

```
foo.detect do|f|
  FOO.include? f
end
```
which is then criticized by `Style/SpaceAroundKeyword`

```
foo.rb:1:12: C: Style/SpaceAroundKeyword: Space after keyword do is missing. 
foo.detect do|f|
           ^^
```
Is this expected behavior that one cop auto-corrects to a state another cop complains about or should `Style/BlockDelimiters` auto-correct to code that adheres to the default rubocop style, i.e. introducing a space after the `do`?

```
$ rubocop -v
0.41.1

```

### PR DESCRIPTION
**Pull request by tjwp**
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by bbatsov** [comment]
This has to be rebased.

**Comment by tjwp** [comment]
@bbatsov rebased

**Comment by bbatsov** [comment]
Unfortunately you'll have to do this one more time. After this is merged I'll cut a bugfix release.

**Comment by tjwp** [comment]
@bbatsov Rebased again

**Pull request merged**
