### PR TITLE
[Don't merge: work in progress] FakeFS

### PR DESCRIPTION
**Pull request by bquorning**
As mentioned in #1681, it might be a good idea to use [FakeFS](https://github.com/defunkt/fakefs) to isolated the file system when testing. I’m opening this PR to get some early feedback, as it will change some core parts of the spec setup.

@rrosenblum @jonas054

### CODE REVIEW

**Comment by jonas054** [comment]
Apart from it not working, it looks fine to me. I get a lot of
```
Errno::EEXIST:
       File exists - /home
     # /home/jonas/.rvm/gems/ruby-2.1.2/bundler/gems/fakefs-15e2ee818ee1/lib/fakefs/fileutils.rb:42:in `block in mkdir'
```

**Comment by bquorning** [comment]
@jonas054 I haven't seen that particular error, but I have seen a lot of other ones :-)

I just pushed a couple of commits – now I only have 5 examples failing locally.

**Comment by bquorning** [comment]
FakeFS ignores the `flags` argument to `Dir.glob`, meaning that hidden directories are always traversed. However, hidden leaves seems to be never returned (see defunkt/fakefs@0156ffdde8e2e453542622434bc9f8fb529c8bef). I will need to investigate further.

**Comment by bquorning** [comment]
Actually, the implementation of `Dir.glob` in FakeFS is flawed. Using pattern alternation only works in very simple cases, and fails when using code like RuboCop’s `TargetFinder`.

I looked into maybe porting some of Rubinius’ `Dir.glob` code (https://github.com/rubinius/rubinius/blob/master/kernel/common/dir.rb#L49-L101 and https://github.com/rubinius/rubinius/blob/master/kernel/common/dir_glob.rb) into FakeFS, but that’s gonna be a whole lot of work.

**Comment by rrosenblum** [comment]
Having not used FakeFS before, I was curious how well it would handle things like `Dir.glob`. Given the work that is going to be needed, is it still a viable option? Are there other gems out there might fit our need? If there are, they may or not have the same issues that you have experienced.

**Comment by bquorning** [comment]
Another option would be to test on a real, but isolated file system. A RAM Disk?

**Comment by bbatsov** [comment]
Seems this is going nowhere, right?

**Comment by bquorning** [comment]
Yeah, this was harder than expected. Closing.

**Pull request closed without merging**
