### PR TITLE
Allow ignoring methods in Style/BlockDelimiters when using line_count_based style

### PR DESCRIPTION
**Pull request by twe4ked**
See title.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing. (~~We'll see what the build server says.~~ Yep.)
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by bbatsov** [comment]
Hmm, I don't even remember why we added this functionality to begin with. Someone should refresh my memory before this is merged. I also wonder why the ignored methods were considered in just one style out of 3.

**Comment by bbatsov** [comment]
Finally coming back to this. Update this to respect the ignored methods for all styles and I'll have it merged.

**Comment by twe4ked** [comment]
Done :+1:. The build doesn't seem to have kicked off though, not sure if it's just taking its time to start.

Would you like me to squash/rebase on master and force push?

Thanks

**Comment by bbatsov** [comment]
Yeah, you'll have to squash and rebase.

**Comment by twe4ked** [comment]
Done.

**Pull request merged**
