### PR TITLE
Update copyright notices to 2016 [ci skip]

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by jonas054** [comment]
This PR competes with #2566. I guess the first one to use the correct verb form in the commit message ("Update") will be merged. :smile:

**Comment by Atul9** [comment]
@jonas054 Done.

**Comment by bbatsov** [comment]
One more thing - use rebase to discard the annoying merge commit.

**Comment by Atul9** [comment]
@bbatsov  Ok. Done.

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
