### PR TITLE
[Fix #2060] New cop Style/RescueEnsureAlignment

### LINKED ISSUE #2060: Alignment rules missing for rescue/ensure
Currently there seems to be no cop to complain about the following.

```ruby
begin
  a
      rescue
        b
            ensure
              c
end
```

And if we start with:
```ruby
begin
a
rescue
b
ensure
c
end
```

...and auto-correct, `Style/IndentationWidth` (alone) makes it to look like this (by default):
```ruby
begin
  a
  rescue
    b
  ensure
    c
end
```

### PR DESCRIPTION
**Pull request by lumeet**

### CODE REVIEW

**Comment by bbatsov** [comment]
I'm fine either way. Generally, I don't think there's much room for interpretation regarding the indentation of `rescue` and `ensure`, but you're right that this is less likely to introduce problems.

**Comment by jonas054** [comment]
Looks good apart from my two comments!

**Comment by lumeet** [comment]
I had nothing against moving this to `Style`, so that's fixed now as well as the tiny `modifier?` adjustment. Thanks for the feedback. One day I'll find the boundary between `Lint` and `Style`. ;)

**Comment by bbatsov** [comment]
:+1: Thanks!

**Pull request merged**
