### PR TITLE
[Fix #3292] Remove `Performance/PushSplat` cop

### LINKED ISSUE #3292: Performance/PushSplat autocorrect can lead to runtime error
## Actual behavior
With a *push splat* where the argument may be `nil` autocorrect will still change it and then the code will throw a TypeError (as `Array#concat` cannot handle `nil` arguments).

## Expected behavior
Autocorrect should not cause breaking changes to codebase. Therefore when auto-correcting a *push splat* where the argument may be nil it should either not correct it, or maybe coerce it to an array with `#to_a`.

## Steps to reproduce the problem
1. Put this code somewhere:

  ```
  x = nil
  y = []
  y.push(*x)
  ```
2. Run the code, see that it doesn't raise an exception.
3. Run RuboCop with autocorrect, see it makes 1 change.
4. Run the code again, see that it now raises a `TypeError`.

## RuboCop version
```
$ rubocop -V
0.41.1 (using Parser 2.3.1.2, running on ruby 2.3.1 x86_64-linux)
```
I've tested this on `master` too, still applies.

### PR DESCRIPTION
**Pull request by jonas054**
This cop's auto-correct (or manual correction based on its recommendations) can produce code that is slower or code that fails for various reasons.

Cc: @segiddins Hope you agree with removing the cop. See #3292 for reason behind.

### CODE REVIEW

**Comment by segiddins** [comment]
I'm disappointed to see this reverted

**Comment by bbatsov** [comment]
If doesn't really yield performance improvements I guess we should remove it. We might have to consider the style angle, though, as arguably `concat` yield a bit cleaner code.

**Comment by bbatsov** [comment]
> various reasons.

Thought only `nil` was an issue.

**Comment by jonas054** [comment]
>Thought only nil was an issue.

According to a comment in #3292, there's also `TypeError: no implicit conversion of Hash into Array`.

**Comment by Drenmi** [comment]
One problem with these kinds of optimizations is that their characteristics can change over different releases of the language, based on internal changes, optimization strategies, etc. and there's really no way for us to notice, unless we run all the benchmarks on each release.

**Comment by bbatsov** [comment]
> I was contemplating earlier, whether this should also be extracted into its own extension when time comes to break out rubocop-rails.

Yeah, I can definitely envision a `rubocop-performance` gem down the road. I guess we should finally get some work done on a proper API for RuboCop extensions...

**Comment by Drenmi** [comment]
> I guess we should finally get some work done on a proper API for RuboCop extensions...

How about we open an issue where we can keep discussions on the design of such a system in one place?

**Comment by bbatsov** [comment]
There's one such issue already - https://github.com/bbatsov/rubocop/issues/3414

**Comment by jonas054** [comment]
@bbatsov Will we remove this cop? If you agree, I'll rebase.

**Comment by bbatsov** [comment]
Let's remove it.

**Comment by bbatsov** [comment]
@jonas054 ping :-)

**Comment by jonas054** [comment]
Here you go. :-)

**Pull request merged**
