### PR TITLE
To the bitter end

### PR DESCRIPTION
**Pull request by alexdowad**

### CODE REVIEW

**Comment by alexdowad** [comment]
OK, fixed up everything which @bbatsov commented on.

**Comment by bbatsov** [comment]
The `ClassStructure` cop looks the same to me. I really think that making it flexible is the key to its long-term usefulness. The defaults are pretty sensible for sure, but as you mentioned yourself - preferences on the subject will vary.

**Comment by bbatsov** [comment]
I'd suggest moving the ClassStructure work to a separate PR and merging everything else right away.

**Comment by alexdowad** [comment]
Removed `Style/ClassStructure`.

**Pull request merged**
