### PR TITLE
Add rubocop:todo directive alongside rubocop:disable

### PR DESCRIPTION
**Pull request by vergenzt**
Implementation of @Drenmi's idea from https://github.com/bbatsov/rubocop/pull/4127#issuecomment-286930398 to introduce a separate `# rubocop:todo` directive that operates in parallel to `# rubocop:disable`:

> @vergenzt: For example if I'm editing method foo and I see it's surrounded by # rubocop:disable Metrics/MethodLength, then that's a lot more likely to prod me to refactor the method than if Metrics/MethodLength happened to include the file in its exclude list in a yaml todo list file I never think to check.
> 
> @Drenmi: For me, it is the opposite. If I see a rubocop:disable, it is a colleague (or past me) telling me: "this is a false positive" or "we made all the considerations, and we still think this is the best shape for this code right now." Adding a disable is a deliberated decision.
> 
> How about an alias directive, that works the same way, but that offers some context? E.g. rubocop:todo_begin and rubocop:todo_end?

 I implemented it according to option 1 from my proposal in https://github.com/bbatsov/rubocop/pull/4127#issuecomment-292757859:

> Option 1. :todo and :disable are separate switches/"modes", and either being active will suppress a cop.
> 
> Example:
> 
> ```ruby
> # rubocop:disable Style/PredicateName
> # rubocop:todo Style/PredicateName
> def is_example
>   puts "Yep."
> end
> # rubocop:end_todo Style/PredicateName
> 
> def is_another_example
>   puts "Also yep."
> end
> # rubocop:enable Style/PredicateName
> ```
>
> No offenses would be reported.

Will likely be easiest to digest commit-by-commit, as it's split into two. The first commit refactors `CommentConfig` to split out some appropriate classes with no behavior change, and the second actually implements the `# rubocop:todo` behavior.

Thoughts?

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  axd description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
I haven't had time to review this recently. Sorry about the delay. @jonas054 @Drenmi Feel free to take a look as well.

**Comment by vergenzt** [comment]
No problem. I understand it's a lot to process.

Sorry for the large-ish PR. I tried a few times to implement this without major refactorings, but I kept bumping up against pretty confusing issues, so I figured a cleaner abstraction was warranted.

**Comment by Drenmi** [comment]
Ping @vergenzt. 🙂

**Comment by bbatsov** [comment]
Closing due to lack of progress.

**Pull request closed without merging**
