### PR TITLE
Fix Style/ParallelAssignment

### LINKED ISSUE #2464: Style/ParallelAssignment for array swapping
I have code like this. I just need to swap two elements in array
```
array = [1, 2, 3, 4]
array[0], array[1] = array[1], array[0]
p array
```

rubocop game me this offence:
```
test.rb:2:1: C: Style/ParallelAssignment: Do not use parallel assignment.
array[0], array[1] = array[1], array[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
````
By documentation of [Style/ParallelAssignment cop](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/parallel_assignment.rb) I cannot understand that is wrong with my code.
Is this a bug in cop, or there is better way to swap elements in my array?

I use 
`rubocop 0.35.1 (using Parser 2.2.3.0, running on ruby 2.1.6 x86_64-linux)`

### PR DESCRIPTION
**Pull request by alexdowad**
Fixes #2464.

### CODE REVIEW

**Comment by bbatsov** [comment]
Apart from the stylistic issues uncovered by RuboCop, the changes look fine.

**Comment by rrosenblum** [comment]
Looks good to me. Thanks for implementing this fix.

**Comment by alexdowad** [comment]
> Apart from the stylistic issues uncovered by RuboCop

...The stylistic issues are fixed.

> Looks good to me. Thanks for implementing this fix.

And thank you for all your work as well, @rrosenblum!

**Comment by bbatsov** [comment]
The changes look good to me as well. You'll have to rebase.

**Comment by alexdowad** [comment]
Slipped in another bug fix.

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
