### PR TITLE
Add new Style/RaiseString cop

### PR DESCRIPTION
**Pull request by tjwp**
This cop checks if `raise` or `fail` is called with just a String
and suggests using an exception class.

This cop is disabled by default.

This change partly addresses https://github.com/bbatsov/rubocop/issues/3066. There are some projects where I've wanted all `raise` calls to use custom errors and this would help to enforce that. 

* [x] Wrote [good commit messages][1].
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it)
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

### CODE REVIEW

**Comment by jonas054** [comment]
A very similar cop is added in #3182.

**Comment by alexdowad** [comment]
A couple good things here: both `raise` and `fail` are caught, and with both `str` and `dstr` arguments. I neglected to handle a couple of those cases.

**Comment by jonas054** [comment]
So if you could rewrite this as an improvement of `Style/ImplicitRuntimeError`, which has been merged to `master`, that would be great, @tjwp.

**Comment by tjwp** [comment]
I'm going to close this and will work on a separate PR with improvements for `Style/ImplicitRuntimeError`.

**Comment by tjwp** [comment]
Added improvements here: https://github.com/bbatsov/rubocop/pull/3225

**Pull request closed without merging**
