### PR TITLE
New cop Lint/ShadowedException

### PR DESCRIPTION
**Pull request by rrosenblum**
As far as I know, there is not something that will warn about shadowed exceptions in Ruby. This breaches the wall from static code analysis to a bit of dynamic code analysis. It seemed easier to let Ruby figure out its own hierarchy than it would be to maintain a map or a list. 

I think that this cop has some usefulness, but I am not sure how effective it will be since it only works with exceptions that are internal to Ruby itself.

I might have some refactoring to do around `rescue_modifier?`. This class, `ParallelAssignment`, and `RescueModifier` all have different checks. I should be able to merge the implementation from this class and `ParallelAssignment`. I am hoping that the same method also works for `RescueModifier`.

### CODE REVIEW

**Comment by bbatsov** [comment]
This cops looks useful in general, but:

* it needs to be aware of all built-in exception classes to provide some meaningful feedback
* I don't like the terminology you've used - typically the terms "more specific" and "less specific" exception are used. Guess this can be investigated further

**Comment by rrosenblum** [comment]
> I don't like the terminology you've used - typically the terms "more specific" and "less specific" exception are used. Guess this can be investigated further

I am fine updating this. I went with terminology that I happened to be thinking about at that time.

> it needs to be aware of all built-in exception classes to provide some meaningful feedback

Can you expand upon this? Were you thinking that something needed to be hard coded for this? I am relying on Ruby's [object comparison](http://ruby-doc.org/core-2.3.1/Object.html#method-i-3C-3D-3E) to handle this. Unless I am misunderstanding something, comparing classes using `<`, `>`, `==`, and other methods, Ruby will compare them based on there hierarchy. `StandardError` is less than `Exception` because it is child of `Exception`.
```ruby
pry(main)> StandardError.ancestors
=> [StandardError, Exception, Object, PP::ObjectMixin, Kernel, BasicObject]
```

**Comment by bbatsov** [comment]
> Can you expand upon this? Were you thinking that something needed to be hard coded for this? I am relying on Ruby's object comparison to handle this. Unless I am misunderstanding something, comparing classes using <, >, ==, and other methods, Ruby will compare them based on there hierarchy. StandardError is less than Exception because it is child of Exception.

I didn't read the PR carefully. Guess I should do this eventually. :-)

**Comment by rrosenblum** [comment]
I have updated the wording. Let me know if there are any other changes that need to be made.

**Comment by jonas054** [comment]
@rrosenblum The following code makes the cop crash:
```ruby
begin
  a
rescue ArgumentError
  b
rescue Interrupt
  c
end
```
Can you check why?

**Comment by rrosenblum** [comment]
@jonas054, good catch. I will create a test case and figure out why that causes a crash.

**Comment by rrosenblum** [comment]
@jonas054 I just pushed a change that fixes the example you provided. It turns out that `<=>` will return `nil` when comparing classes that are not on the same ancestry chain. This caused `sort` to throw an exception.

**Comment by jonas054** [comment]
Good job. But I found another one now:
```ruby
begin
  a
rescue *A => e
  b
end
```

**Comment by rrosenblum** [comment]
Good catch. I am not surprised that your new example is failing. I completely forgot to account for splat arguments. I will fix it shortly.

**Comment by rrosenblum** [comment]
Interestingly, trying to evaluate `*A` produces a `ScriptError` which does not inherit from `StandardError`.

**Comment by bbatsov** [comment]
Has to be rebased.

**Comment by rrosenblum** [comment]
This has been rebased. 

I tried to reuse the functionality of the `rescue_modifier?` method in the `RescueModifier` cop. It isn't working as a proper replacement, but it does appear to be a good enough check for this cop and `ParallelAssignment`.

**Pull request merged**
