### PR TITLE
Relax metrics cops threshold

### PR DESCRIPTION
**Pull request by pocke**
Currently `Metrics/MethodLength` and `Metrics/AbcSize` cops thresholds are relaxed by `.rubocop_todo.yml`.
I think it means the default thresholds is too strict. Because we haven't been able to follow the default thresholds. 😢 

So, I think we should relax the default thresholds. That way users can use appropriate thresholds.
WDYT?

### CODE REVIEW

**Comment by Drenmi** [comment]
There's quite a bit of legacy code still in RuboCop. A lot of work has been done to eliminate the cyclomatic- and perceived complexity problems, but there is still room for improvement.

Setting the defaults for everyone based on RuboCop's current state seems a bit arbitrary? 🙂

**Comment by bbatsov** [comment]
> Setting the defaults for everyone based on RuboCop's current state seems a bit arbitrary? 🙂

I agree.



> Although I am open to a discussion on whether the defaults are too stringent, and what a reasonable adjustment could be. 😊

Same here.

**Comment by pocke** [comment]
> Setting the defaults for everyone based on RuboCop's current state seems a bit arbitrary? :slightly_smiling_face:

I think RuboCop's current code is clean. So, the threshold is a bit arbitrary, but it has a ground. 

> Although I am open to a discussion on whether the defaults are too stringent, and what a reasonable adjustment could be.

:+1:  I'll investigate optimal threshold for the cops by calculating the metrics in several repositories.

**Comment by Drenmi** [comment]
> I think RuboCop's current code is clean. So, the threshold is a bit arbitrary, but it has a ground.

On average, I also think RuboCop is starting to shape up. The problem is that it uses the **worst** code as the threshold, even if that is just a single method or class. 😞 

> I'll investigate optimal threshold for the cops by calculating the metrics in several repositories.

This sounds very interesting. Looking forward to the findings. 😊

**Comment by rrosenblum** [comment]
> Setting the defaults for everyone based on RuboCop's current state seems a bit arbitrary?

Like everyone else, I agree. How did we come up with the original defaults? I know why line length is 80. Aside from that, I don't know how the defaults were decided.

Cyclomatic Complexity is set to 6 and Perceived Complexity is set to 7. Perceived Complexity should always be higher than Cyclomtic Complexity. However, only being 1 higher seems quite restrictive to me.

**Comment by bbatsov** [comment]
I think that at this point is way more important to document some of the defaults and why they were picked than relaxing them. Not to mention that default values like 18 and 14 seem extremely random.

**Comment by bbatsov** [comment]
In light of my last comment, and the lack of any subsequent discussion I think we can close this for now.

**Pull request closed without merging**
