### PR TITLE
[Fix #1802] Fix 'Exclude' when '.rubocop.yml' in subdirectory

### LINKED ISSUE #1802: Exclude doesn't work when .rubocop.yml is in subdirectory
* There is no way to Exclude/Include files in `.rubocop.yml` when it is in subdirectory ex. `config/tools/.rubocop.yml`. 
```
$ rubocop --config config/tools/.rubocop.yml
```
doesn't exclude excluded directories even with this config:
```
AllCops:
  Exclude:
    - '../../db/**/*'
```
Without `../../` it doesn't work as well

* It works only when `.rubocop.yml` is in project root directory
```
$ rubocop --config .rubocop.yml
```

```
$ rubocop -V
0.30.0 (using Parser 2.2.2.0, running on ruby 2.2.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by marcinkornek**

### CODE REVIEW

**Comment by bbatsov** [comment]
LGTM @jonas054 What do you think?

**Comment by jonas054** [comment]
I don't see any problems with this change. @marcinkornek Please rebase on top of the current master. @bbatsov Go ahead and merge after that.

**Comment by marcinkornek** [comment]
@jonas054 I rebased on top of the current master.

**Comment by bbatsov** [comment]
:+1: Thanks!

**Pull request merged**
