### PR TITLE
Empty lines

### PR DESCRIPTION
**Pull request by alexdowad**
Splitting these commits into a separate PR as requested by @bbatsov.

### CODE REVIEW

**Comment by bbatsov** [comment]
As mentioned in my previous comments - I'm not quite certain about the value of the `top-level-only` style, as the top-level often doesn't have any special meaning. Maybe `non-namespace-top-level` or something like this makes more sense, but I'd like to hear more thoughts on the subject.

**Comment by alexdowad** [comment]
> I'm not quite certain about the value of the top-level-only style, as the top-level often doesn't have any special meaning.

I think you are quite right. It is clear that a number of people want empty lines, either at top and bottom *or* top only... but only in certain circumstances. So what are those "circumstances"? Can we break them down?

**Comment by bbatsov** [comment]
I think we should apply the surrounding blanks lines either on every level or only on non-namespace top-levels. Not sure what exactly the original requester had in mind.

For the second fix - it seems @zenspider wanted this for every scope, so at least it's clear cut.

**Comment by zenspider** [comment]
Personally, I want a blank line at the top ONLY if there's rdoc on the first code element:

```ruby
class X

  ##
  # woot

  def woot
  end
end
```

If there is no rdoc (eg, there's a `:nodoc:` on it), then I don't:

```ruby
class X
  def woot # :nodoc:
  end
end
```

and poking around my code, apparently I'm very inconsistent at it. :)

**Comment by bbatsov** [comment]
Hmm, seems to me that the `body_start_only` is something quite specific (when we factor the rdoc stuff) and it's probably not worth supporting it out-of-the-box.

**Comment by bbatsov** [comment]
@mockdeep please join the discussion here about `top_level_only`.

**Comment by mockdeep** [comment]
So I guess for me the desired behavior might be different depending on whether we're dealing with blocks or modules/classes. Here's the previous issue I opened about block nesting: https://github.com/bbatsov/rubocop/issues/1568. For my own part, I'd prefer even classes namespaced within modules to be required to have blank lines within them, except for a couple of cases. One is when they don't have any code:

```ruby
class MyError < StandardError
end

# I've been just putting the on one line to avoid the cop:
class MyError < StandardError; end
```

The other use case is when I define a one-off class inside of a test block:

```ruby
it 'does something' do
  class MyClass
    extend ModuleImTesting
  end

  expect(MyClass.new.something).to eq 'something'
end
```

So I guess combined with the previous issue, I would say two overall adjustments:
1) If a class/module/block is inside of a block, no spacing requirement
2) If a class/module(/maybe block?) has no content, no spacing requirement

**Comment by alexdowad** [comment]
@mockdeep Does "no spacing requirement" mean "issue a warning if there is spacing" or "don't issue a warning regardless of whether there is spacing or not"?

**Comment by alexdowad** [comment]
In s-expressions: `(no (spacing requirement))` or ((no spacing) requirement)`?

**Comment by mockdeep** [comment]
@alexdowad I suppose I would go with the more restrictive `((no spacing) requirement)` to enforce consistency. If there's an edge case within there that isn't covered, it's probably a sign that my code is getting too goofy.

**Comment by alexdowad** [comment]
> 1) If a class/module/block is inside of a block, no spacing requirement

I'm a bit wary about this one. You've shown one example of a class defined inside a block, but that is just one example. I'm sure there are plenty of other cases out there where people are defining classes inside blocks, and I don't feel at all sure that this rule will suit all of them.

> 2) If a class/module(/maybe block?) has no content, no spacing requirement

This makes a lot of sense.

**Comment by alexdowad** [comment]
I've coded up a commit which implements @mockdeep's suggestion #2.

**Comment by mockdeep** [comment]
> I'm a bit wary about this one.

I wasn't able to think of another use case that made sense to me, though I'm sure there are some out there. There's always the opportunity to disable the rule conditionally, though I guess we could also just make it less restrictive for things nested within blocks.

**Pull request closed without merging**
