### PR TITLE
only ship selected files to reduce gem size

### PR DESCRIPTION
**Pull request by grosser**
367K -> 214K

and safer since nobody can forget to ignore things

### CODE REVIEW

**Comment by bbatsov** [comment]
Looks good to me. As before - please capitalize the commit message. I'd split the removal of the redundant attributes to a second commit.

**Comment by grosser** [comment]
updated

**Comment by bbatsov** [comment]
Thanks!

**Comment by alexdowad** [comment]
What were we shipping before which wasn't needed?

**Comment by bbatsov** [comment]
Things like changelog and the release notes. I agree what a whitelist beats a blacklist. You always have to keep updating the blacklist...

**Pull request merged**
