### PR TITLE
Unify node type checks across several cops

### PR DESCRIPTION
**Pull request by lumeet**
Apply `literal?`, `basic_literal?`, `truthy_literal?`, `falsey_literal?`, `variable?` and `reference?` to generic checks.

### CODE REVIEW

**Comment by alexdowad** [comment]
:+1: Nice!!

As a suggestion, I would prefer to see `#literal?`, etc. defined as methods on `Node` (since we have already started adding our own custom extensions). Then you can do things like `nodes.select(&:literal?)`.

**Comment by bbatsov** [comment]
> As a suggestion, I would prefer to see #literal?, etc. defined as methods on Node (since we have already started adding our own custom extensions). Then you can do things like nodes.select(&:literal?)

I agree. That'd be a better api.

**Comment by lumeet** [comment]
Absolutely! I'll change it.

**Comment by lumeet** [comment]
Changed. Or do we prefer `def_matcher`? I kept the old implementation for now as it's still simple and fast.

**Comment by alexdowad** [comment]
> Changed. Or do we prefer def_matcher?

Personally, I think whatever you like is fine. `def_matcher` was intended to make long chains of destructuring an AST node, picking out a child, destructuring it, picking out a child, etc. much more concise. In this case, there's nothing really to be gained either way.

**Comment by bbatsov** [comment]
:+1:

**Comment by alexdowad** [comment]
Thanks.

**Pull request merged**
