### PR TITLE
Add `_` to Naming/UncommunicativeMethodParamName default AllowedNames

### PR DESCRIPTION
**Pull request by ojab**

### CODE REVIEW

**Comment by Drenmi** [comment]
Hm. This seems to run completely counter to the purpose of the cop? At least to me, `_` isn't particularly communicative. 🙂

**Comment by ojab** [comment]
Ruby style guide says
>Prefix with _ unused block parameters and local variables. It's also acceptable to use just _ (although it's a bit less descriptive).

I assume that it can be applied to method arguments and "acceptable" means that it's not an offence according to the style guide.

**Comment by ojab** [comment]
I don't really have a strong opinion about that, so it's ok to just close PR, but I'd like to have some kind of consensus about that and, probably, clarification in the style guide.

**Comment by bbatsov** [comment]
I think we should not do this. The name's acceptable, but it's hardly a good name. Maybe we should even revise the style guide. I generally never use `_` by itself, I always use it just as a prefix.

**Pull request closed without merging**
