### PR TITLE
Add recursive literal checking

### PR DESCRIPTION
**Pull request by segiddins**
Also beefs up Style/DuplicatedKey in the process. I'm sure this can be used to simplify Style/LiteralInCondition too, but it wasn't immediately obvious to me how.

### CODE REVIEW

**Comment by alexdowad** [comment]
You can almost gut `LiteralInCondition` now, as you noted. Take this:

```ruby
        def check_for_literal(node)
          cond, = *node

          # if the cond node is literal we obviously have a problem
          if cond.literal?
            add_offense(cond, :expression)
          else
            # alternatively we have to consider a logical node with a
            # literal argument
            check_node(cond)
          end
        end
```

...and change to something like:

```ruby
        def check_for_literal(node)
          cond, = *node
          add_offense(cond, :expression) if cond.recursive_literal?
        end
```

Then start deleting all the methods which are not used any more.

**Comment by segiddins** [comment]
@alexdowad I tried that, but I don't think I understand why a bunch of the current specs for LiteralInCondition are the way they are -- they seem rather non-literal to me?

**Comment by bbatsov** [comment]
Which in particular?

**Comment by segiddins** [comment]
The thing I was struggling with was that `recursive_literal?` checks if _all_ nodes are literal. What we need for LiteralInCondition is to see if any 'toplevel' (i.e. nodes that a user would see, not the children the lexer produces) are literal. Should be possible to do in a short method anyways.

**Comment by alexdowad** [comment]
> see if any 'toplevel' (i.e. nodes that a user would see, not the children the lexer produces) are literal.

Could you provide an example illustrating the difference?

**Comment by segiddins** [comment]
@alexdowad 

```ruby
["#{hello}"]
```

is where all "top-level" nodes are literal

```ruby
["#{'hello'}"]
```

is where the entire thing is recursively literal

**Comment by bbatsov** [comment]
Let's wrap this PR. What remains to be done?

**Comment by segiddins** [comment]
I think it's fine as-is?

**Comment by bbatsov** [comment]
Just rename `complex` to `composite` and rebase.

**Comment by bbatsov** [comment]
And you should add a changelog entry.

**Comment by segiddins** [comment]
@bbatsov done! sorry for the long delay

**Comment by bbatsov** [comment]
:+1:

**Comment by bbatsov** [comment]
There's still no changelog entry, but I guess we can add it later.

**Pull request merged**
