### PR TITLE
Enable Style/MutableConstants by default & fix violations

### PR DESCRIPTION
**Pull request by segiddins**
The commit message on https://github.com/bbatsov/rubocop/commit/0d954122206f1bbf7ab5c859bdfb7ee327db7ea0 implied that making it enabled by default would happen eventually, so I hope this OK!

### CODE REVIEW

**Comment by alexdowad** [comment]
Just one question: when we are running on Ruby 3.0, with its immutable string literals, are we going to remove all the `.freeze` calls from string constants?

**Comment by segiddins** [comment]
@alexdowad I was actually going to handle that, but I couldn't figure out how to tell whether or not the current file has the `# frozen_string_literal: true` magic comment in it

**Comment by bbatsov** [comment]
> Just one question: when we are running on Ruby 3.0, with its immutable string literals, are we going to remove all the .freeze calls from string constants?

The cop should probably not report in such scenarios (and maybe there should be a cop pointing out redundant freezes).

**Comment by bbatsov** [comment]
> The commit message on 0d95412 implied that making it enabled by default would happen eventually, so I hope this OK!

It certainly is! Thanks!

**Comment by alexdowad** [comment]
> I couldn't figure out how to tell whether or not the current file has the # frozen_string_literal: true magic comment in it

Look at @rrosenblum's open PR. He does just that.

**Comment by segiddins** [comment]
@alexdowad oh awesome! In that case, once his PR lands, I think a bunch of those methods could be extracted into a mixin that will make being ruby-version aware much easier. One other question for you: I couldn't figure out the proper way to test the `target_ruby_version` setting other than stubbing that method on the cop?

**Comment by alexdowad** [comment]
> I couldn't figure out the proper way to test the target_ruby_version setting other than stubbing that method on the cop?

This is just a wrapper around a value from the config. In the specs, we already have helpers which can be used to test cops with different config. Our config helpers already add the `TargetRubyVersion` value to the simulated config. In your specs, you can adjust with:

`let(:ruby_version) { 2.3 }`

**Pull request merged**
