### PR TITLE
Fix false positive in Rails/Date when to_time is chained with safe method

### LINKED ISSUE #2860: Dates to Unix Timestamp
I can't find a way to satisfy Rubocop and convert dates to unix timestamps.  For time, you can do something like `Time.current.to_i`.  For dates, I have `Date.today.to_time.to_i`.  Rubocop complains about the `to_time` aspect as `Date` does not know anything about TimeZones.

Is there a way around this without disabling date checks?

### PR DESCRIPTION
**Pull request by palkan**
Fix #2860

### CODE REVIEW

**Comment by bbatsov** [comment]
Please, rebase on top of the current `master`.

**Comment by palkan** [comment]
Done

**Comment by bbatsov** [comment]
Unfortunately you'll have to rebase again.

**Comment by palkan** [comment]
No problem) Done

**Pull request merged**
