### PR TITLE
Fix documentation for Rails/Present cop

### PR DESCRIPTION
**Pull request by cbliard**
Also reformat text for Rails/Blank and Rails/Present to make it
more readable.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
Seems to me the documentation examples should be updated as well - e.g. in the style of @koic. If I didn't know what this cop does the documentation would certainly leave me confused. :-)

**Comment by cbliard** [comment]
Ok will do. Thanks for the examples and explanations.

**Comment by cbliard** [comment]
Is it better like this?

Also the primary reason I got here was because [Watir](http://watir.com/) has a `#present?` method which is different from ActiveSupport `Object#present?`. Rubocop happily changed `unless div(class: "foo").present?` to `if div(class: "foo").blank?` so I wanted to check configuration options of Rails/Blank cop to fix this. That's how I noticed a little typo in the documentation. Creating a `rubocop.yml` in `spec/` disabling both `UnlessPresent` and `NotPresent` did the trick. Is it something worth mentioning  in docs?

**Comment by bbatsov** [comment]
There's so merge conflict, other than this - it look good to me.

**Comment by cbliard** [comment]
I have just rebased on master, fixed conflicts and squashed.

**Comment by bbatsov** [comment]
👍

**Pull request merged**
