### PR TITLE
Fix frozen string literals

### PR DESCRIPTION
**Pull request by rrosenblum**
This is meant to be merged in after #2542. Once it is merged, this change set will drop to 2 commits.

### CODE REVIEW

**Comment by bquorning** [comment]
Apologies for commenting on the commit and not the PR, but GitHub cannot show the entire diff.

**Comment by bbatsov** [comment]
Guess this has to be rebased as well.

**Comment by bquorning** [comment]
:+1: I’m happy to see this being merged. Sorry about the extra trouble @rrosenblum.

**Comment by rrosenblum** [comment]
@bquorning it was no extra trouble. I rather see that something is done the right way.

**Pull request merged**
