### PR TITLE
[Fix #2066] Dont register offenses inside instance_eval context

### LINKED ISSUE #2066: TrivialAccessors gives wrong correction with instance_eval
Consider this snippet of code:
```ruby
obj.instance_eval do
  def foo
    @foo
  end
end
```
This code shouldn't be autocorrected with `attr_reader` because the method definition is in instance context. `attr_reader` doesn't exist in this context.

### PR DESCRIPTION
**Pull request by tranvictor**

### CODE REVIEW

**Comment by bbatsov** [comment]
After thinking a bit more about this issue, the problem is not as simple. We should really consider what's the receiver for the `instance_eval`, as if it were a class using `attr_` is perfectly valid. On the other hand - if it's a module we're kind of fucked. I'm not sure there's a way to fix this in a manner that's 100% reliable.

**Comment by tranvictor** [comment]
@bbatsov good point, Checking type of an object in Ruby is not simple in general. However, even if we can't find a reliable solution for this, I think we still need not to auto correct readers and writers inside `instance_eval` because it's likely to break the code. Maybe we need a config for this autocorrection?

**Comment by alexdowad** [comment]
> I'm not sure there's a way to fix this in a manner that's 100% reliable.

If not, it's better not to warn at all *except* for the cases where you can be sure.

This PR should be accepted -- but it would be better if @tranvictor could make the detection of "instance_eval context" a bit more robust. Such as by recursing up past `begin` nodes when looking for `(block (send :instance_eval ...) ...)`.

**Comment by bbatsov** [comment]
I close it, as it hasn't been updated in a while.

**Pull request closed without merging**
