### PR TITLE
Fix parallel assignment

### LINKED ISSUE #1873: Bug with parallel assignment auto-correct
See #1831, the auto-correct function is broken with this edge case:

```diff
-        best_separator, best_score = separator, score if score > best_score
+        best_separator = separator
+        best_score = score if score > best_score
```

Both assignments should stay conditional.

As a side note, I don't get why this cop is in the _Performance_ category - does it have any performance implications? Shouldn't it be in _Style_?

### PR DESCRIPTION
**Pull request by rrosenblum**
This fixes #1873.

`ParallelAssignment` will no longer register an offense when protected by a guard clause. For the time being, this seems like the easiest solution. I will start looking into how easy it would be to register an offense and auto correct the source from
```ruby
best_separator, best_score = separator, score if score > best_score
```
to
```ruby
if score > best_score
  best_separator = separator
  best_score = score 
end
```

I also went ahead and moved the cop from the Performance group to the Style group.

### CODE REVIEW

**Comment by bbatsov** [comment]
> ParallelAssignment will no longer register an offense when protected by a guard clause. For the time being, this seems like the easiest solution. I will start looking into how easy it would be to register an offense and auto correct the source from

I'd rather wait for a real fix for this. Detecting the presence of a modifier expression is not hard and expanding it to a non-modifier in the auto-correct shouldn't be hard either.

**Comment by rrosenblum** [comment]
> I'd rather wait for a real fix for this. Detecting the presence of a modifier expression is not hard and expanding it to a non-modifier in the auto-correct shouldn't be hard either. 

Sounds good. I was in the mindset of do the quickest fix for the bug. I agree, it shouldn't take too much work for the full fix.

Good catch on `while`, `unless`, & `rescue`.

**Comment by bbatsov** [comment]
@rrosenblum On a related note - we should add a style guide entry about this. This is something that certainly makes the code clearer.

**Comment by rrosenblum** [comment]
The code has been updated to account for guard clauses using `if`, `unless`, `while`, `until`, and `rescue`. I have also accounted for non-standard indentation width.

There are a few methods in here that I could see being extracted out elsewhere, but I am unsure of what other cops might be using their functionality. The methods that I have in mind are `modifier_while?`, `rescue_guard?`.

**Comment by rrosenblum** [comment]
I created a PR on the style guide for parallel assignment. https://github.com/bbatsov/ruby-style-guide/pull/440

**Comment by bbatsov** [comment]
@rrosenblum I think you forgot to update the first commit message.

**Comment by rrosenblum** [comment]
I think that I am missing something. I was unaware of something needing to be changed in the commit message. 

I looked over the commit message and changed my usage of `guard clause` to `modifier statement`. I assume that this is what you are referring to. Let me know if something else needs to be changed as well.

**Comment by bbatsov** [comment]
The message says "Do not register an offense for parallel assignment protected by a modifier statement", which was the behaviour in your original PR, but now you're properly handling and correcting such scenarios.

**Comment by rrosenblum** [comment]
Whoops, I can't believe that I overlooked that. That was the whole point of the second set of corrections. I have updated the commit and changelog messages.

**Comment by bbatsov** [comment]
:+1: Thanks!

**Pull request merged**
