### PR TITLE
Indent end squiggly heredoc

### PR DESCRIPTION
**Pull request by cllns**
As a part of updating the Hanami codebase to use Ruby 2.3's squiggly heredoc `<<~`, I used rubocop's auto-correct feature. It mostly worked perfectly, but it left the end heredoc delimiters where they were. In our case, this was with 0 spaces. See [this commit](https://github.com/hanami/hanami/pull/864/commits/f989eb9f9c924601033edf291f430573fa6eaf5b).

I've confirmed that this PR fixes the problem above, but I can't figure out how to write a passing spec. The trouble is that the `shared_example` calls `strip_indent` on both the `code` and the`correction`. If I remove those, this spec passes, but others fail. I'm not sure if I can write a passing spec with the indents being stripped. 

Happy to do more work on this, just looking for some direction. 
(And I'll clean up this PR/commits to fit with the project, once this is ready to merge)

Here's the Rspec output:
```ruby
Failures:

  1) RuboCop::Cop::Layout::IndentHeredoc quoted by  EnforcedStyle is `squiggly` autocorrects for first line minus-level indented, with `-`
     Failure/Error: expect(corrected).to eq(correction.strip_indent)

       expected: "puts <<~RUBY2\n  def foo\n    bar\n  end\nRUBY2\n"
            got: "    puts <<~RUBY2\n      def foo\n        bar\n      end\n    RUBY2\n"

       (compared using ==)

       Diff:
       @@ -1,6 +1,6 @@
       -puts <<~RUBY2
       -  def foo
       -    bar
       -  end
       -RUBY2
       +    puts <<~RUBY2
       +      def foo
       +        bar
       +      end
       +    RUBY2

     Shared Example Group: :offense called from ./spec/rubocop/cop/layout/indent_heredoc_spec.rb:272
     Shared Example Group: :all_heredoc_type called from ./spec/rubocop/cop/layout/indent_heredoc_spec.rb:339
     # ./spec/rubocop/cop/layout/indent_heredoc_spec.rb:21:in `block (3 levels) in <top (required)>'

```

### CODE REVIEW

**Comment by bbatsov** [comment]
@pocke @koic @Drenmi @garettarrowood Can you of you guys help @cllns with this PR? I'm totally swamped this week.

**Comment by garettarrowood** [comment]
@cllns - Nice job with this PR, thank you for contributing! I've messed around on your branch and figured out a way for your test to pass.  You may be able to come up with something more refined than this, but here is the gist:

```ruby
  shared_examples :offense do |name, code, correction = nil, strip_fix = true|
    it "registers an offense for #{name}" do
      inspect_source(code.strip_indent)
      expect(cop.offenses.size).to eq(1)
    end

    it "autocorrects for #{name}" do
      corrected = autocorrect_source_with_loop(code.strip_indent)
      if strip_fix
        expect(corrected).to eq(correction.strip_indent)
      else
        expect(corrected).to eq(correction)
      end
    end
  end
```

Then add `false` as a 4th parameter to your test and line up the indentation in the `CORRECTION` correctly.

```ruby
        include_examples :offense, 'first line minus-level indented, with `-`',
                         <<-RUBY, <<-CORRECTION, false
              puts <<-#{quote}RUBY2#{quote}
          def foo
            barrrr
          end
          RUBY2
        RUBY
    puts <<~#{quote}RUBY2#{quote}
      def foo
        barrrr
      end
    RUBY2
        CORRECTION
```

There may be another way to do this - but this does test your change properly. And it's a great addition!

**Comment by garettarrowood** [comment]
@bbatsov - Are you fine with me opening up a new PR with these changes and the test fix?  I think I could open a PR against this PR, but I believe @cllns would then have to merge my fix.

**Comment by cllns** [comment]
@garettarrowood I'm not sure if you have the appropriate permissions, but this PR allows commits to my branch from rubocop maintainers with write access. If that doesn't work, I can merge it into my branch (or you could integrate my changes into your branch and open the PR directly against master; I don't feel any need to own this commit.) :)

**Comment by bbatsov** [comment]
@garettarrowood I'm fine with a new PR, I think that would be the easiest thing to do.

**Comment by bbatsov** [comment]
Guess we can close this one.

**Pull request closed without merging**
