### PR TITLE
That ancient carpet is above every gray guitar

### PR DESCRIPTION
**Pull request by alexdowad**
Starting out a new batched PR here.

Maintainers, do you like the change in the first commit (suggested by @mockdeep) or not? If not, I'll remove it.

### CODE REVIEW

**Comment by alexdowad** [comment]
Ready for review.

**Comment by alexdowad** [comment]
The last commit (just pushed) is significant, please take note.

**Comment by jonas054** [comment]
:+1: Everything, up to and including `SymbolProc doesn't break...`, looks good to me now.

**Comment by alexdowad** [comment]
Rebased on `master`.

**Comment by alexdowad** [comment]
Added another commit. Rebased on `master`.

**Comment by alexdowad** [comment]
The "Split TrailingComma..." commit and the following one, which effectively reverses #2369.

**Comment by alexdowad** [comment]
Added changelogs.

**Comment by alexdowad** [comment]
Back to green. :smile:

**Comment by bbatsov** [comment]
No remarks from me.

**Comment by alexdowad** [comment]
Thanks, @bbatsov. Time to open a new PR...

**Pull request merged**
