### PR TITLE
Specify latest version in README.md

### PR DESCRIPTION
**Pull request by poudelprakash**

### CODE REVIEW

**Comment by bbatsov** [comment]
Such changes don't need a changelog entry.

**Comment by poudelprakash** [comment]
@bbatsov made changes :)

**Comment by bbatsov** [comment]
One more thing - capitalize the commit message and drop the redundant lines in its description (guess they were the result of squashing). Basically you need to do `git commit --amend` and `git push --force`.

**Comment by poudelprakash** [comment]
:ok:

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
