### PR TITLE
[Fix #2721] autocorrect parentheses in rescue call

### LINKED ISSUE #2721: RedundantParentheses auto-correct mangles rescue(Error)
The cop will change
```ruby
begin
  method
rescue(Error)
end
```
to
```ruby
begin
  method
rescueError
end
```

This is happening on 0.36.0 and master. I am looking into a fix for this.

### PR DESCRIPTION
**Pull request by rrosenblum**
This fixes #2721. I am not sure if this is the best way to fix this, but it was the simplest solution. Alternatively, I thought about checking `node.parent.parent.resbody_type?`. I would be interested in feedback from @lumeet since he authored the cop.

### CODE REVIEW

**Comment by lumeet** [comment]
Nice! My only concern is that the fix would make the cop's behavior a bit inconsistent. I'd probably just allow the parentheses after `rescue` as we do with `next(1)`, `case(a)` etc. Additionally, the new `Style/SpaceAroundKeyword` is configured to register an offense for parentheses after `rescue`, so if enabled, we'd basically get the same outcome without any specific correction logic in this cop.

**Comment by rrosenblum** [comment]
> 'd probably just allow the parentheses after `rescue`

That was my other thought to fixing this cop. I will move the logic from the correction to the check. The logic just seems like a weird and weak way of determining if the constant is being used in `rescue`.

**Comment by bbatsov** [comment]
Capitalize `autocorrect` in the commit message.

**Comment by bbatsov** [comment]
And rebase.

**Pull request merged**
