### PR TITLE
[Fix #1803] Don't warn for return from lambda

### LINKED ISSUE #1803: Lint/NonLocalExitFromIterator reporting false positive for a return inside a lambda inside RSpec.configure
We have the following in the spec helper of one of our projects, to ignore a deprecation warning that we'll keep getting until the next big version of a gem we use is released:

```
RSpec.configure do |config|
  # some configuration

  if Gem.loaded_specs["paper_trail"].version < Gem::Version.new("4.0.0")
    current_behavior = ActiveSupport::Deprecation.behavior
    ActiveSupport::Deprecation.behavior = lambda do |message, callstack|
      return if message =~ /`serialized_attributes` is deprecated without replacement/ && callstack.any? { |m| m =~ /paper_trail/ }
      Array.wrap(current_behavior).each { |behavior| behavior.call(message, callstack) }
    end
  end

  # more configuration
end
```

Version 0.30.0 of RuboCop is reporting the following:

```
spec/spec_helper.rb:36:7: W: Non-local exit from iterator, without return value. next, break, Array#find, Array#any?, etc. is preferred.
      return if message =~ /`serialized_attributes` is deprecated without replacement/ && callstack.any? { |m| m =~ /paper_trail/ }
```
There's no iterator here, so this looks like is could be a false positive.

### PR DESCRIPTION
**Pull request by ypresto**
Fixes #1803

### CODE REVIEW

**Comment by bbatsov** [comment]
The code looks good. Please, mention the bugfix in the changelog.

**Comment by ypresto** [comment]
Added CHANGELOG.md!

**Comment by bbatsov** [comment]
Thanks!

**Comment by ypresto** [comment]
:tada: :tada:

**Pull request merged**
