### PR TITLE
Feature fix encoding fatal error

### PR DESCRIPTION
**Pull request by gerrywastaken**
This was a tricky one to track down. When I was running rubocop against some code it would keep crashing with an encoding error but it wasn't clear why this was happening and seemed inconsistent.

It turns out that it would only occur when the offenses were read from cache as they came back as ASCII-8BIT encoded strings instead of UTF-8 encoded when the cache isn't used. The attempt to convert inside the erb highlighting helper was triggering the crash.

I squashed the commits down into 3 logical changes, but didn't want to squash it into a single commit as it would have made things harder to understand for anybody looking at the changes. It also would have made cherry picking more difficult if it became necessary. If you still would prefer me to squash it further, then I can.

Before submitting a PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it)
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by gerrywastaken** [comment]
Oops, looks like adding that entry to the change log broke some changelog related specs. I don't really understand the break though.

**Comment by bbatsov** [comment]
👍 Impressive work! I loved your attention to detail!

**Comment by gerrywastaken** [comment]
Thanks mate, thanks for making RuboCop. :)

**Comment by burnson** [comment]
Thanks for fixing this @gerrywastaken! I too was scratching my head trying to reproduce it to file [#3099](https://github.com/bbatsov/rubocop/issues/3099). Glad to see you were way ahead of me.

**Comment by gerrywastaken** [comment]
@burnson Yeah I figured it must be affecting others. Glad this helped you. Good job tracking it down to cached results, that had me banging my head against a wall for quite some time.

**Pull request merged**
