### PR TITLE
[Fix #988] Add --exclude-limit option

### LINKED ISSUE #988: Exclude files instead of disabling cops in auto generated config
If the offending files are a reasonable amount (e.g. `<= 5`) it would be convenient that rubocop would exclude them in the auto generated config instead of disabling them. Moreover after the file a comment including the number the offences could be included.

This has two benefits:

- Allows for a more granular fixing.
- Prevents style regression in the rest of the codebase.

### PR DESCRIPTION
**Pull request by jonas054**
This option can be used with `--auto-gen-config` to set the maximum number of `Exclude` properties to generate per cop. The normal behavior to generate `Enabled: false`, etc, is
kept by default and when the number of files with offenses exceeds the given limit.

I think the new option will be useful for some people. It shouldn't be used always, and the added functionality has to be weighed against the added complexity.

### CODE REVIEW

**Comment by jonas054** [comment]
I needed to make an implementation to see the pros and cons clearly. As I see it:

Pros:
* For cop like `Metrics/ClassLength`, it's better to list a few files that exceed the limit in a central place than to raise the allowed `Max` for all files. It's also better than `# rubocop: disable` comments.

Cons:
* For many other cops, it's not a good choice to exclude whole files. On the other hand, the new option is "opt-in", so we shouldn't expect people to use it without thinking.

@bbatsov It's up to you if you want this or not. I mainly wanted to finish the discussion and close the issue.

**Comment by bbatsov** [comment]
I'll think about this for a while. Input for other people is welcome as well!

**Comment by steakunderscore** [comment]
My 2 cents on the issue. When it comes to coding standards we have a few projects that are well below par. The projects are still being developed with new features being added, as well as the old code being slowly cleaned up. Adding rubocop (with auto generated config) is currently not very useful, because just about every cop gets disabled. It would be helpful to have new code uphold the style guide's standard, while not having old code disable rubocop.

**Comment by vassilevsky** [comment]
More options is better 😜

**Comment by bbatsov** [comment]
> More options is better 😜

It's also more code to maintain (probably code that we'll be used only a handful of people).

**Comment by bbatsov** [comment]
I think something like https://github.com/bbatsov/rubocop/pull/1709 makes more sense.

**Comment by jonas054** [comment]
OK. Let's continue the discussion over at 1709.

**Comment by jonas054** [comment]
This will not be merged. Closing.

**Pull request closed without merging**
