### PR TITLE
Allow IndentationWidth cop to ignore certain lines from indentation

### PR DESCRIPTION
**Pull request by jfelchner**
Fixes: bbatsov/rubocop#1031

### CODE REVIEW

**Comment by jfelchner** [comment]
@bbatsov @jonas054 any movement on this?  I hate having this cop completely disabled.

**Comment by jfelchner** [comment]
I'll be happy to rebase this onto the current master to get it mergable again.

**Comment by bbatsov** [comment]
I'm super busy at work. I'll get back to you regarding this at some point, but unfortunately I cannot make any promises as to when this would be. As you can see bugs and PRs keeping piling up and we can't keep up with all of them.

**Comment by jfelchner** [comment]
@bbatsov I understand!  I'll try to help with some of the bugs if I can find time myself!

**Comment by aschlei** [comment]
I just wanted to say I would like this as well, so that's two people :)

My workaround was just to disable Style/IndentationWidth entirely.  An IDE helps control the indentation level anyway, and Style/IndentationConsistency will catch lines that are misaligned from the others of the same logical depth (though I suppose it would miss it if they were all off).

**Pull request closed without merging**
