### PR TITLE
Style/Next can autocorrect

### PR DESCRIPTION
**Pull request by alexdowad**

### CODE REVIEW

**Comment by bbatsov** [comment]
:+1:

**Comment by jonas054** [comment]
@alexdowad I think that `Style/Next` now suffers from the same problems we had in `Style/IfUnlessModifier` before they were fixed in #1859, which is that auto-correct destroys comments. Can you take a look?

**Comment by alexdowad** [comment]
@jonas054 Whoops! I'm sure you are right!

Can we open an issue for that? I will fix it, probably tomorrow.

**Comment by jonas054** [comment]
Thanks. I opened an issue.

**Comment by alexdowad** [comment]
Thanks @jonas054 for catching my bugs!!

**Pull request merged**
