### PR TITLE
Add new `Style/TernaryParentheses` cop

### PR DESCRIPTION
**Pull request by Drenmi**
This cop checks the inclusion or omission of parentheses around ternary conditions, based on its `EnforcedStyle` configuration. It was inspired by [this StackOverflow question](http://stackoverflow.com/questions/38237472/how-can-i-implement-this-ternary-coding-rule-with-rubocop).

Example:

```
# EnforcedStyle: require_no_parentheses

foo = (bar && baz) ? a : b
```

will be corrected to:

```
foo = bar && baz ? a : b
```

Corrections that would change the meaning of the expression will be avoided.

Example:

```
# EnforcedStyle: require_no_parentheses

foo = (bar = baz = find_baz) ? a : b
```

will not be corrected.

(See the spec files for a more exhaustive list of corrections.)

### CODE REVIEW

**Comment by bbatsov** [comment]
I wonder if this shouldn't be a more generic cop - something covering all `if` nodes.

**Comment by Drenmi** [comment]
@bbatsov: There's `Style/ParenthesesAroundCondition`, but it explicitly leaves out ternary conditions.

My reason for making it a separate cop is that we use different styles for `if`, `while` and `undo` (include), and for `ternaries` (omit), and I didn't want to overload the existing cop with configuration options.

What do you think?

**Comment by Drenmi** [comment]
I should definitely leverage the existing `SafeAssignment` mixin though. I just noticed it there, through `Style/ParenthesesAroundCondition`.

**Comment by bbatsov** [comment]
> My reason for making it a separate cop is that we use different styles for if, while and until (include), and for ternaries (omit), and I didn't want to overload the existing cop with configuration options.

I'm fine with this. I totally forgot about the existing cop, although I think I wrote it myself. :-)

**Comment by bbatsov** [comment]
> I should definitely leverage the existing SafeAssignment mixin though. I just noticed it there, through Style/ParenthesesAroundCondition.

Indeed.

**Comment by Drenmi** [comment]
@bbatsov: Implementation changed to use the mixin and rebased. 😀

**Comment by bbatsov** [comment]
👍

**Pull request merged**
