### PR TITLE
Style/TrivialAccessor allows predicate methods by default

### PR DESCRIPTION
**Pull request by alexdowad**
This should cut down on the number of duplicate issues being raised on GitHub.

### CODE REVIEW

**Comment by alexdowad** [comment]
Just shoehorned a bugfix in here.

**Comment by bbatsov** [comment]
Apart from the failing build - both changes should have changelog entries.

**Comment by bbatsov** [comment]
Apart from the missing changelog entry or two, everything looks good. Rebase and we're good to merge.

**Comment by alexdowad** [comment]
Added missing changelog entry. Rebased.

**Pull request merged**
