### PR TITLE
Prefer square brackets for array literals instead of parens

### PR DESCRIPTION
**Pull request by bronson**
This is an attempt to make https://github.com/bbatsov/ruby-style-guide/pull/563 easier to merge.

To me, square brackets look like arrays and round brackets look like functions/grouping.  I appreciate the visual distinction.

This PR also allows bare `[]` and `{}` in the yaml config, potentially helping https://github.com/bbatsov/rubocop/issues/3541.

It is meant as a demonstration and to hopefully encourage discussion.  The style guide should be updated first of course.

---

Before submitting the PR make sure the following are checked:
- [x] Wrote [good commit messages](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
- [x] Used the same coding conventions as the rest of the project.
- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
- [x] All tests are passing.
- [x] The new code doesn't generate RuboCop offenses.
- [x] The PR relates to _only_ one subject with a clear title
  and description in grammatically correct, complete sentences.

### CODE REVIEW

**Comment by savef** [comment]
I'm against this change, but for no good reasons beyond personal preference. I just thought it might be a good idea to voice an opposing opinion as it looks like nobody else has in either the ruby-style-guide issue or the PR, but obviously that doesn't mean nobody disagrees. :stuck_out_tongue: 

In my mind the `%w(one two three)` looks great, and `%w[one two three]` isn't visually distinct enough from `[one two three]` where the values inside are local variables or method calls.

P.S. The change RE: #3541 is very cool, though I still intend to add some kind of per-cop validation stuff at some point.

**Comment by Drenmi** [comment]
I am on the fence about the change itself. I'm okay with both styles. I added some of your considerations to [the discussion](https://github.com/bbatsov/ruby-style-guide/issues/526#issuecomment-253768608) @savef. Please feel free to join in. 😀 

However, I think we should wait for the PR to be merged into the style guide before we merge this. 😀

**Comment by savef** [comment]
> I added some of your considerations to the discussion @savef

Ha, thanks for noticing the missing commas. I'll try to add a remark to the issue later but _+1_'d for now.

**Comment by bronson** [comment]
@Drenmi agreed, the style guide needs to be updated first.  I edited that into the description.

@savef, definitely agree that per-cop validation is still needed.  Looking forward to seeing it.  I am surprised you'd rather see arrays with rounded corners...  maybe in time you'll come around.  :)

**Comment by bbatsov** [comment]
The style guide PR is close to being merged. Guess you can update this PR and we can merge it.

**Comment by bbatsov** [comment]
@bronson The PR was merged. Feel free to update this PR as well.

**Comment by bronson** [comment]
@bbatsov that's excellent news.  I'm sorry for the delay, been neck-deep in non-computer stuff.

I'll try to update this in a week.

**Comment by bbatsov** [comment]
Sounds good.

**Comment by bbatsov** [comment]
Closing this for now due to lack of activity.

**Pull request closed without merging**
