### PR TITLE
Add a rake task for generation a new cop

### PR DESCRIPTION
**Pull request by pocke**
e.g.

```sh
$ bundle exec rake new_cop[Lint/UnifiedInteger]
created
- lib/rubocop/cop/lint/unified_integer.rb
- spec/rubocop/cop/lint/unified_integer_spec.rb

Do 4 steps
- Add an entry to `New feature` section in CHANGELOG.md
  - e.g. Add new `Lint/UnifiedInteger` cop. ([@your_id][])
- Add `require 'lib/rubocop/cop/lint/unified_integer'` into lib/rubocop.rb
- Add an entry into config/enabled.yml or config/disabled.yml
- Implement a new cop to the generated file!
```

The task generates two ruby files.
And it displays next steps.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by backus** [comment]
Would be cool if you could give it an example of offending code. Could potentially setup a node matcher for you and maybe setup your first test.

**Comment by Drenmi** [comment]
This is neat. Anything that lowers the barrier to contribution is great, if you ask me. 😀

**Comment by bbatsov** [comment]
This should probably be mentioned in the manual.

**Comment by pocke** [comment]
@backus 
Thanks for nice suggestion!
I've added some example code to generated files.

@bbatsov 
I've added `manual/development.md`.

**Comment by bbatsov** [comment]
Th build is failing.

**Comment by pocke** [comment]
Fixed the build.

**Comment by bbatsov** [comment]
Down the road it'd be nice to add a rake task for removing a cop as well. A rake task for generating release notes for the changelog would also be quite handy.

**Pull request merged**
