### PR TITLE
Add reference links to cops

### PR DESCRIPTION
**Pull request by rrosenblum**
It seemed useful to provide links to the fast-ruby project since it helped inspire the performance cops. It also provides nice information for anyone that is unaware of the performance gains. If people like this, we can consider treating the links similar to the `StyleGuide` links.

### CODE REVIEW

**Comment by bbatsov** [comment]
Maybe we could add some `Reference` key for such purposes. Adding the link in the description looks a bit ugly to me.

**Comment by rrosenblum** [comment]
I went through and found cops that specified urls in their comments and copied the urls to the new `Reference` key in the configuration.

What do you think of adding a configuration option to display the reference link in the offense message like what is done with the style guide links?

**Comment by bbatsov** [comment]
> What do you think of adding a configuration option to display the reference link in the offense message like what is done with the style guide links?

I think we can just reuse the same option even for non-style guide cops.

**Comment by jonas054** [comment]
@rrosenblum The build is failing. Could you take a look?

**Pull request merged**
