### PR TITLE
Expose files to support testing Cops using RSpec

### LINKED ISSUE #3176: Move CopHelper to a file in lib so it can be included outside RuboCop?
Recently at GitLab we've begun writing custom cops to enforce some things that are very specific to our style preferences and/or our codebase. Obviously we want to make sure these cops are covered by automated tests, but the tests make use of the methods from [`CopHelper`](https://github.com/bbatsov/rubocop/blob/master/spec/support/cop_helper.rb).

For now I've gotten by just copying the relevant parts of `CopHelper` into a file in our own `spec/support` directory, but I'm wondering if it would make sense to move the file into RuboCop's `lib` folder as something like `test_helper`, so that it can be required as-needed for testing custom cops.

### PR DESCRIPTION
**Pull request by tjwp**
I made a guess at the files that would be useful to expose.

I've verified that this removes the need for a clone of rubocop to run tests for rubocop-rspec.

The exposed files can be loaded from spec_helper using:

    require 'rubocop/rspec/support'

Supporting files were copied unmodified, except for module + class level comments added to `cop_helper.rb` to fix RuboCop offenses.

Fixes #3176.

* [x] Wrote [good commit messages][1].
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it)
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by mikegee** [comment]
I have [a Rubocop extension](https://github.com/covermymeds/rubocop-thread_safety) and putting Rubocop in a git submodule to make the specs work was definely the suckiest part. Thanks @tjwp

**Comment by tsigo** [comment]
@tjwp Awesome, thanks for tackling this!

**Comment by bbatsov** [comment]
I'm fine with this change. Just rebase this branch on top of the current `master`.

**Comment by tjwp** [comment]
Rebased. Thanks!

**Comment by bbatsov** [comment]
You'll have to do this again. :-(

**Comment by tjwp** [comment]
@bbatsov No problem. Rebased again.

**Pull request merged**
