### PR TITLE
Allow Casecmp to correct comparison to variables and methods

### PR DESCRIPTION
**Pull request by rrosenblum**

### CODE REVIEW

**Comment by rrosenblum** [comment]
I need to work on another PR for this cop to support the opposite comparison case of `'string' == str.downcase`.

**Comment by bbatsov** [comment]
Apart from the failing build - the change looks good to me.

**Comment by bbatsov** [comment]
You'll have to rebase.

**Comment by bbatsov** [comment]
The build is still failing.

**Comment by rrosenblum** [comment]
The build should be fixed now.

**Pull request merged**
