### PR TITLE
[Fix #2950] Fix correcting in OneLineConditional

### LINKED ISSUE #2950: OneLineConditional auto-correct produces incorrect code
In #2885, auto-correct functionality was added to `Style/OneLineConditional`, but it needs tweaking.
@lumeet will you take a look?

## Expected behavior

```ruby
if ARGV.size > 0 then puts 'a' else puts 'b' end
```
auto-corrected to
```ruby
ARGV.size > 0 ? (puts 'a') : (puts 'b')
```
or possibly that no change is made in complicated cases where the AST would be changed.

## Actual behavior

```ruby
if ARGV.size > 0 then puts 'a' else puts 'b' end
```
auto-corrected to
```ruby
ARGV.size > 0 ? puts 'a' : puts 'b'
```
which is a syntax error.

## Steps to reproduce the problem

`rubocop -a file.rb`

## RuboCop version

```
$ rubocop -V
0.38.0 (using Parser 2.3.0.6, running on ruby 2.3.0 x86_64-linux)
```
and also current master, 7d10599.

### PR DESCRIPTION
**Pull request by lumeet**
Before submitting a PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it)
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

Auto-correting in `Style/OneLineConditional` handles method calls with
arguments correctly by using parentheses. E.g.

    if a then puts 1 else puts 2 end

...is auto-corrected to:

    a ? (puts 1) : (puts 2)

### CODE REVIEW

**Comment by lumeet** [comment]
> or possibly that no change is made in complicated cases where the AST would be changed.

@jonas054 Did you have some examples in mind? I might have way too lazy here... :)

**Comment by jonas054** [comment]
Looking at the [precedence list](http://ruby-doc.org/core-2.3.0/doc/syntax/precedence_rdoc.html) it *is* possible to come up with some other special examples, like

```ruby
if x = ARGV.size > 0 then puts(x) else puts(0) end
```
which is changed to
```ruby
x = ARGV.size > 0 ? puts(x) : puts(0)
```
which is syntactically OK but semantically different.

**Comment by lumeet** [comment]
Thanks, @jonas054! I think it's much better now, probably not perfect but better.

**Comment by jonas054** [comment]
:+1:

**Pull request merged**
