### PR TITLE
Add new `Lint/BigDecimalNew` cop

### PR DESCRIPTION
**Pull request by koic**
## Feature

`BigDecimal.new()` is deprecated since BigDecimal 1.3.3 for Ruby 2.5.
This cop identifies places where `BigDecimal.new()` can be replaced by `BigDecimal()`.

```console
% cat /tmp/example.rb
# frozen_string_literal: true

BigDecimal.new(123.456, 3)
```

```console
% rubocop /tmp/example.rb
Inspecting 1 file
W

Offenses:

/tmp/example.rb:3:12: W: Lint/BigDecimalNew: BigDecimal.new() is deprecated. Use BigDecimal() instead.
BigDecimal.new(123.456, 3)
           ^^^

1 file inspected, 1 offense detected
```

I have verified that these methods can be replaced using the lowest
Ruby version 2.1 supported by RuboCop.

```console
% ruby -v
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-darwin13.0]
% gem list | grep bigdecimal
bigdecimal (default: 1.2.4)
% ruby -rbigdecimal -e 'p BigDecimal(123.456, 3) == BigDecimal.new(123.456, 3)'
true
```

## Other Information

The following is a change of BigDecimal 1.3.3 for Ruby 2.5 related to this PR.

- https://github.com/ruby/bigdecimal/commit/533737338db915b00dc7168c3602e4b462b23503
- https://github.com/ruby/bigdecimal/commit/16738ad0aca158d3c70123990d8caa5789818177

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by koic** [comment]
I saw this change at rails/rails#31435.

**Comment by pocke** [comment]
BTW, I think we should ship v0.52.1, that is a bug fix release. And the release should not contain any new features. So we need to wait merging this pull-request until we ship the release.
What do you think? @bbatsov

**Comment by garettarrowood** [comment]
This looks like it'd be a good check to add to `Lint/DeprecatedClassMethods`, perhaps instead of adding a new cop.

**Comment by koic** [comment]
Thanks for the review. I have worries. BigDecimal is not a standard library, it is a default gems managed by ruby/bigdecimal repo.

```console
% gem list | grep default
bigdecimal (default: 1.3.2)
(snip)
```

I don't know whether it is preferable to change configuration in the same lifecycle as `Lint/DeprecatedClassMethods` cop.

Of course, as a practical use case, I think that there is no need to make an independent configuration change, so adding it to `Lint/DeprecatedClassMethods` is an approach.

**Comment by bbatsov** [comment]
> BTW, I think we should ship v0.52.1, that is a bug fix release. And the release should not contain any new features. So we need to wait merging this pull-request until we ship the release.
What do you think? @bbatsov

I agree. That was my plan as well - do a bugfix release over the weekend or early next week. Unfortunately I'll be super busy until Tuesday.

**Comment by bbatsov** [comment]
Please, rebase on top of the current `master`.

**Comment by koic** [comment]
Thanks. I did rebase.

**Pull request merged**
