### PR TITLE
Allow submitting coverage results to Code Climate

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I observed that the build is failing since we introduced Code Climate for coverage. I hope this will fix it.

### CODE REVIEW

**Comment by bbatsov** [comment]
I was wondering about this, but had no time to investigate. I wonder how this worked with coveralls, though.

**Comment by deivid-rodriguez** [comment]
Me too...

**Comment by bbatsov** [comment]
Seems this was the issue. Thanks for spotting and fixing it!

**Comment by deivid-rodriguez** [comment]
You are welcome!

**Pull request merged**
