### PR TITLE
Fix alias method usage offenses

### PR DESCRIPTION
**Pull request by syndbg**
Addresses offenses reported by https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L12

P.S Not really worth the changelog entry.

### CODE REVIEW

**Comment by alexdowad** [comment]
It appears you are not running the latest dev version of RC. Perhaps you are using the last released gem version?

**Comment by alexdowad** [comment]
(Otherwise there would be no offenses for this.)

**Comment by syndbg** [comment]
@alexdowad Very likely. However what is going on here - the styleguide prefers usage of `alias_method

**Comment by alexdowad** [comment]
> the styleguide prefers usage of `alias_method

It's not that simple. The newest style guide prefers `alias` in some cases, and `alias_method` in others. In the newest (unreleased) version of RC, the `Alias` cop follows the newest style guide.

Have a look at the commit log, you'll see the recent work on this.

**Comment by syndbg** [comment]
@alexdowad Alright. I got you. Thanks :+1:

**Pull request closed without merging**
