### PR TITLE
Budget-hotel flavor

### PR DESCRIPTION
**Pull request by alexdowad**

### CODE REVIEW

**Comment by bbatsov** [comment]
You should also mention this in the README as suggested by @jonas054.

**Comment by bbatsov** [comment]
ping :-)

**Comment by alexdowad** [comment]
pong

**Comment by alexdowad** [comment]
Hi @bbatsov. Personally, I don't agree that this should be mentioned in the README. My view is that `formatters`, etc. are "supposed" to be plain arrays, but this patch is just making RC more tolerant of non-standard input. (Something like the way web browsers accept invalid HTML and use heuristics to fix up the DOM internally.)

**Comment by alexdowad** [comment]
Stuck another bug fix in.

**Comment by bbatsov** [comment]
Fair enough. All new changes look good. :+1:

**Pull request merged**
