### PR TITLE
Only register an offense for StringReplacement if the length of the pattern is 1

### LINKED ISSUE #2061: False positives in upcoming ﻿Performance/StringReplacement cop
I've just been having a play with the master branch (to see how the todo generation now builds an exclude list - looks like that feature is going to be very handy!) and noticed a problem with the new Performance/StringReplacement cop.

Simple example code:

    puts 'Hello, World'.gsub(/lo/, 'p!')

With just this cop and auto-correct enabled Rubocop says:

    example.rb:1:21: C: [Corrected] Performance/StringReplacement: Use tr instead of gsub.
    puts 'Hello, World'.gsub('lo', 'p!')

And the corrected version is

    puts 'Hello, World'.tr('lo', 'p!')

However, output for these is very different:

    2.2.0 :001 > puts 'Hello, World'.gsub(/lo/, 'p!')
    Help!, World
     => nil
    2.2.0 :002 > puts 'Hello, World'.tr('lo', 'p!')
    Hepp!, W!rpd
     => nil
    2.2.0 :003 >

`gsub` replaces each `lo` with `p!`.
`tr` _independently_ replaces each `l` with `p` and each `o` with `!`.
I suspect what you're trying to do here is only safe when the regex used by gsub is a single character.

### PR DESCRIPTION
**Pull request by rrosenblum**
This fixes #2061.

### CODE REVIEW

**Comment by bbatsov** [comment]
Btw, I'm guessing we should still point that `gsub(/ala/, something)` is the same as `gsub('ala', something)` and probably the second version is more efficient (and it's easier to read).

**Comment by rrosenblum** [comment]
> Btw, I'm guessing we should still point that gsub(/ala/, something) is the same as gsub('ala', something) and probably the second version is more efficient (and it's easier to read).

I agree that a string is more readable than regex. As for performance, regex is faster until Ruby 2.1 or 2.2. We could use a similar method to identify what can be changed. Recommending string vs regex feels like different functionality than `gsub` to `tr` or `delete`. I can write a separate cop to handle string vs regex passed to `gsub`. Should that cop be dependent on Ruby version to recommend regex vs string, or always recommend string?

**Comment by bbatsov** [comment]
> Should that cop be dependent on Ruby version to recommend regex vs string, or always recommend string?

It should always recommend string. We should compile a list of eligible methods to check in it (apart from `sub` & friends).

**Comment by rrosenblum** [comment]
A quick search of [Ruby Docs}(http://ruby-doc.org/core-2.2.0/String.html), points to `sub`, `gsub`, `index`, `partition`, `rindex`, `rpartition`, `scan`, and `split` all allowing string to regex.

`match` also allows string or regex, but will convert the string to regex. Should we recommend string here as well or regex since that is the natural form?

**Comment by bbatsov** [comment]
> match also allows string or regex, but will convert the string to regex. Should we recommend string here as well or regex since that is the natural form?

Guess using regexp would be better for `match`.

**Pull request merged**
