### PR TITLE
[Fix #2935] Make config loading work if SafeYAML.load is private

### LINKED ISSUE #2935: private method `load' called for SafeYAML:Module
Running RuboCop...
private method 'load' called for SafeYAML:Module
~/.rvm/gems/ruby-2.1.5/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:165:in 'yaml_safe_load'
...
RuboCop failed!

```
$ rubocop -V
0.38.0 (using Parser 2.3.0.6, running on ruby 2.1.5 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by jonas054**
It looks like this can happen. We don't know why, but let's handle it.

### CODE REVIEW

**Comment by bbatsov** [comment]
Some specs are failing.

**Comment by jonas054** [comment]
The failures seem to come from using `parser-2.3.0.7` but I'm not sure if it's a bug in Parser.

**Comment by bbatsov** [comment]
@whitequark can you lend us a hand - are we seeing a bug or not?

**Comment by whitequark** [comment]
Yes, this is because of changes in Parser.

`RuboCop::Cop::Style::CharacterLiteral accepts literals like ?\C-\M-d`:
```
(fragment:0):1:5: error: literal contains escape sequences incompatible with UTF-8
(fragment:0):1: x = ?\C-\M-d
(fragment:0):1:     ^~~~~~~~
```
`RuboCop::Cop::Style::WordArray when EnforcedStyle is array doesn't fail on strings which are not valid UTF-8`: duh.
`RuboCop::Cop::Style::StringLiterals configured with single quotes preferred accepts double quotes with some other special symbols`: uses `'g = "\xf9"'`.

All of this is the intended sort of breakage. Let's continue the discussion in https://github.com/whitequark/parser/issues/283.

**Comment by bbatsov** [comment]
@jonas054 I've patched things up (restoring the old behaviour), but the proper solution is probably to just remove the problematic specs. Any thoughts?

**Comment by jonas054** [comment]
@bbatsov I think the change you made is the right way to go for us. The specs that failed were introduced for good reasons, for example to support incorrect encoding in test code that has been added there on purpose, like in #2671. @alexdowad Do you agree?

**Comment by alexdowad** [comment]
@jonas054 Yes. I think the recent changes to `parser` are not "fixing" it, but "breaking" it. Patching it to restore the old behavior is probably the most reasonable thing to do right now.

**Pull request merged**
