### PR TITLE
Fix an itty-bitty typo

### PR DESCRIPTION
**Pull request by seanhussey**

### CODE REVIEW

**Comment by bbatsov** [comment]
Thanks for spotting this. Can you just change the commit message to "Fix an itty-bitty typo" to match our commit message guidelines?

**Comment by seanhussey** [comment]
Sure! There y'are.

**Comment by bbatsov** [comment]
Almost. :-) Commit message titles should not end with a `.`.

**Comment by seanhussey** [comment]
There you go.

**Comment by bbatsov** [comment]
:+1: Thanks!

**Pull request merged**
