### PR TITLE
[Fix #2679] Extend `MaxLineLength` to new cops

### LINKED ISSUE #2679: auto-gen-config generated Style/GuardClause Exclude doesn't seem to work
Running `rubocop --auto-gen-config` generated a config like:

```
Style/GuardClause:
  Exclude:
    - 'app/controllers/some_controller.rb'
```

but running rubocop again with that config would still report the same error in some_controller.rb

Only setting

```
Style/GuardClause:
  Enabled: false
```

turned it off effectively. Exclude lists seem to work correctly for other Style/\* cops.

### PR DESCRIPTION
**Pull request by TimMoore**
- Add to `ConditionalAssignment`
- Add to `GuardClause`
- Extract `max_line_length` to a mixin

Fixes #2679

### CODE REVIEW

**Comment by TimMoore** [comment]
There's a little bit of inconsistency in the way the fallback behaviour used to be handled:

- `ConditionalAssignment` only applied the max line length if `Metrics/LineLength` was enabled. If it was, it assumed it would have a non-`nil` `Max` (relying on `defaults.yml` for fallback).
- `GuardClause` did not consider whether `LineLength` was enabled, but also did not assume that there would be a config for `Max`, falling back to a hardcoded value of 80 columns if it was `nil`
- `IfUnlessModifier` and `WhileUntilModifier` both previously supported the `MaxLineLength` parameter, falling back to `Metrics/LineLength` `Max` if that was `nil`. However, #795, which introduced this config, also added a default value for `MaxLineLength` to these cops, so I don't think the fallback to what is configured in `LineLength` would have ever taken effect.

In an effort to make things more consistent, I refactored the check in this PR, but went with the simplest implementation that passed the specs, despite it changing behaviour for some of the cops:

- Don't consider whether `Metrics/LineLength` is enabled.
- Don't hardcode any fallback length, instead assume the default for `Metrics/LineLength` `Max` will be used from `defaults.yml`.
- Don't add a default `MaxLineLength` to the new cops, so the fallback will actually work.

I'm interested in feedback on this and happy to change the PR. In particular:

- Should the other `MaxLineLength` defaults be removed?
- Should it completely skip the line length checking if there is no `MaxLineLength` config _and_ the `LineLength` cop is not enabled?

**Comment by TimMoore** [comment]
I'm not sure why, but Travis CI doesn't seem to have picked up this PR.

**Comment by TimMoore** [comment]
Hmm is there actually any support for configs without a default value? I get "unrecognized parameter" warnings without values in `default.yml`.

**Comment by alexdowad** [comment]
> is there actually any support for configs without a default value?

I don't think so. But you could just use `nil` as the default. (In YAML, `~` is nil.)

**Comment by TimMoore** [comment]
That makes sense. It looks like the YAML spec treats `null`, `Null`, `NULL` and `~` equivalently. Personally, I prefer spelling it out for clarity, since I expect a lot of readers to be unfamiliar with this use of `~`, but I'm happy to use it if the maintainers prefer.

This also highlights a gap in the existing tests, as the fallback behaviour was never fully tested. I'm reluctant to duplicate all of these edge-case tests into each of the cops that share this behaviour so I'm tempted to do a bigger refactoring of the max line length logic. I'm not sure whether to jam that all into this PR, though.

**Comment by TimMoore** [comment]
I've updated this with `MaxLineLength` set to `null` for all cops. I'll save the bigger refactoring and test improvements for a later PR.

**Comment by TimMoore** [comment]
I just pushed another update with the merge conflict resolved.

**Comment by rrosenblum** [comment]
I like the idea of introducing consistency in dealing with `MaxLineLength`. The reason that I have used the value in `Metrics/LineLength` is that it is consistent. Typically, if it is enabled, people care, if not, they don't. Although, any newer configuration will default `Metrics/LineLength` to enabled and set to the longest line.

My concern with this is that the `MaxLineLength` can differ from `Metrics/LineLength` and between cops. If `MaxLineLength` is less than `Metrics/LineLength`, then no bid deal, you end up with a few shorter lines. If `MaxLineLength` is greater than `Metrics/LineLength`, then these corrections could possibly cause other offenses.

**Comment by alexdowad** [comment]
I suggest that the `MaxLineLength` setting should be moved under `AllCops`, since it is not specific to one cop but cuts across many of them.

**Comment by rrosenblum** [comment]
I like @alexdowad suggestion. To extend that, I then think that `Metrics/LineLength` should inherit its value for `Max` from `MaxLineLength`

**Comment by TimMoore** [comment]
I like the idea of moving `MaxLineLength` to `AllCops` ... it will make it much more convenient to set.

Of course, not all cops respect line length currently, so it might be a bit misleading, but it also would create a target to move toward.

The interaction between `Metrics/LineLength` `Max` and `MaxLineLength` is a tricky one. Taking @rrosenblum's suggestion of defaulting the former to the latter would probably at least avoid surprising behaviour in most cases, but it would still be true if it were explicitly set to something smaller than `MaxLineLength`, then auto-corrections could introduce new violations. Should we print a warning in that case?

One other question remains: should _any_ cops do max line length checking if `Metrics/LineLength` is disabled?

**Comment by rrosenblum** [comment]
By adding a `MaxLineLength` that can differ from `Metrics/LineLenth`, are we creating added unneeded complexity? There should only be 1 acceptable maximum configurable line length. I think that we should either standardize the usage of `Metrics/LineLength` or convert to using `MaxLineLength` in the `AllCops` section. If we go with `MaxLineLength`, then we should remove `Max` from `Metrics/LineLength` and `Metrics/LineLength` should get its maximum value from `MaxLineLength`.

**Comment by TimMoore** [comment]
@rrosenblum did you read through the comments on #2679 that motivated this change? Right now, the single `Metrics/LineLength` `Max` value creates problems when running `--auto-gen-config`.

If we were to remove that, however, we wouldn't be able to take advantage of the ratcheting down of Metrics cops in the `.rubocop_todo.yml` file.

**Comment by alexdowad** [comment]
> If we were to remove that, however, we wouldn't be able to take advantage of the ratcheting down of Metrics cops in the .rubocop_todo.yml file.

Sure we would. `--auto-gen-config` would have to set `AllCops` -> `MaxLineLength` rather than `Metrics/LineLength` -> `Max`.

**Comment by TimMoore** [comment]
Then it would have the same problem we have now.

**Comment by alexdowad** [comment]
OK. So it seems that if we used a single `AllCops` -> `MaxLineLength` parameter, `--auto-gen-config` would need to confirm that no offenses are caused from *any* cop when "ratcheting down" the max line length.

The part which handles `--auto-gen-config` setting of `AllCops` -> `MaxLineLength` could be pulled out and made separate from all the cops.

**Comment by TimMoore** [comment]
@alexdowad it's a little more complicated than that. When you run `--auto-gen-config`, the existing `.rubocop_todo.yml` file is truncated completely. The existing TODO configuration is never loaded, it is always regenerated from scratch.

The value for `Metrics/LineLength` is set in the TODO file by looking at the longest line in all of the files in the project, which means that other cops being evaluated in the `--auto-gen-config` run cannot know what that value will be, unless Rubocop changes completely to run different cops in different passes over the source code.

Currently, during that `--auto-gen-config` run, all of the other cops see the value of `Metrics/LineLength` `Max` as the default value of 80 columns. That causes these cops that combine multiple lines onto one to ignore any cases where the combined line would be > 80 columns. Then, when the actual maximum line length is later written into the `.rubocop_todo.yml` file, as a value greater than 80 columns, it has the effect of creating new violations of these line-combing cops.

What we need to do here is have some way to declare a "target" max line length in `.rubocop.yml` that doesn't override the `Metrics/LineLength` `Max` value in the `.rubocop_todo.yml` file, but does affect how other cops determine whether to combine lines.

**Comment by alexdowad** [comment]
> Currently, during that --auto-gen-config run, all of the other cops see the value of Metrics/LineLength Max as the default value of 80 columns. That causes these cops that combine multiple lines onto one to ignore any cases where the combined line would be > 80 columns.

So we need to change our approach of setting max line length via `--auto-gen-config`.

When running `--auto-gen-config`, all cops should see the max line length as being a very high value (perhaps infinite). **After** all the cops are finished inspecting, a separate stage can "ratchet down" max line length to a value which doesn't cause any added offenses.

**Comment by TimMoore** [comment]
Do any of the committers have an opinion on the best way to proceed with this? (@jonas054, @bbatsov)

**Comment by bbatsov** [comment]
@TimMoore I'm traveling these days. I'll take a closer look at the PR when I'm back home in a few days.

**Comment by jonas054** [comment]
It's a complex issue, so it seems hard to come up with a solution that's perfect from every aspect. Let me restate the problem first.

Some cops use the maximum length of a line when determining if some construct is an offense or not. Let's look at two examples.

`GuardClause` does this by fetching `Metrics/LineLength: Max` from the current configuration. The problem with this is that during an `--auto-gen-config` run, the value of `Metrics/LineLength: Max` is typically taken from RuboCop's `config/default.yml` rather than the local `.rubocop_todo.yml`, which means that `GuardClause` might find fewer offenses in that run compared to a normal run.

`IfUnlessModifier`, on the other hand, fetches the value from its own `MaxLineLength` parameter. This avoids the problems that `GuardClause`has, but instead we have the problem of duplication in the configuration. The `MaxLineLength` is not automatically updated by `--auto-gen-config`, so the user has to keep an eye on all the `MaxLineLength` parameters and keep them in sync with `Metrics/LineLength: Max` manually.

My observations:
* Moving `MaxLineLength` to `AllCops` is a good idea, since many cops depend on this value.
* Setting it to `nil` and falling back on `Metrics/LineLength: Max` puts us back at square one, not having solved the problem of different results in `--auto-gen-config` and a normal run.

Conclusions:
* Add `AllCops: MaxLineLength: 80` to `default.yml` and let several cops, but not `Metrics/LineLength`, use it.
* Keep `Metrics/LineLength: Max` as today, being the place where the ratcheting down is done. Leave that to the `Metrics/LineLength` cop and don't generate `MaxLineLength` into `.rubocop_todo.yml`.
* Find a way to alert the user if `AllCops: MaxLineLength` and `Metrics/LineLength: Max` deviate.

**Comment by TimMoore** [comment]
@jonas054 sounds like a good approach. If we warn/alert when `AllCops: MaxLineLength` and `Metrics/LineLength: Max` deviate, many `--auto-gen-config` users would see that warning all the time. Is that what we want?

**Comment by jonas054** [comment]
I lost track of this conversation. Sorry.

@TimMoore Yes, if the warning is "You have increased `Metrics/LineLength: Max` in your project configuration, but `AllCops: MaxLineLength` taken from default configuration is much smaller. Please set `AllCops: MaxLineLength` in the project configuration."

Something like that. How does that sound?

**Comment by alexdowad** [comment]
> How does that sound?

It sounds expedient for solving the current problem with `--auto-gen-config`, but a bad idea in the long run.

When would it ever make sense for those 2 (or more) config parameters to have different values? Never. So why add them in the first place?

The problem with `--auto-gen-config` *can* be fixed properly, without resorting to this ugliness. It just requires going a bit deeper and "breaking the mold" of how `--auto-gen-config` currently works. But in the long term, it will be better. Why not make the extra effort to do things right?

**Comment by bbatsov** [comment]
I agree with @alexdowad - this should be solved properly, even if it involves some extra work.

**Comment by TimMoore** [comment]
Thanks everyone for your input. I think a deeper change to how `--auto-gen-config` works would be great, but unfortunately I won't have any time to commit to this in the near future. I'll close this pull request now and hope that someone more familiar with Rubocop internals will be able to jump in.

**Pull request closed without merging**
