### PR TITLE
[Fix #5512] Make Kernel#tap a void-context-method

### LINKED ISSUE #5512: Lint/Void should detect `Kernel.tap` as void-context-method
`Kernel.tap` ignores the return value of the passed block. Rubocop should know about this.

The following code should emit a linting error, since it was clearly the programmer's intent to write a program that outputs `7`:

```ruby
a = 4.tap do |x|
  x = x + 3
  x
end

puts a
```

However, the **actual behavior** is that Rubocop (from master) is completely fine with that code.

I think the fix is trivial, since rubocop does analysis like this for `each` already. Will open a PR soon

### PR DESCRIPTION
**Pull request by untitaker**
Not sure about two things:

- Error message is not pretty. You might not understand what's happening if you
  are misunderstanding/misremembering the behavior of `tap`. But adding a
  specialized error message is probably too much effort.

- Amount of tests

### CODE REVIEW

**Comment by bbatsov** [comment]
I'm not sure you understand all possible usages of `tap`, as some of them can definitely yield the object you tapped with some changes to it - http://seejohncode.com/2012/01/02/ruby-tap-that/

**Comment by untitaker** [comment]
I looked through your link and I'm not sure what you mean. Sure, you can mutate the object in-place, but the same can be said about `each`. Those usecases will not trigger this lint anyway.

My point is that the return value of the block that is passed to `tap` is ignored, not that `tap` returns nothing.

**Comment by bbatsov** [comment]
`tap` returns its block argument, which is definitely not void.

**Comment by untitaker** [comment]
Yes, tap returns the argument passed to the block (i.e. `self`), as opposed to the value returned from the block. That makes the block itself a void context, right?

Please refer to the snippet in the linked issue for a (wrong) example of what I was trying to lint against. I still don't see how this change would affect any of the usecases in the post you linked.

**Comment by untitaker** [comment]
Maybe I am using the wrong terminology here... Which code would break because of this change?

**Comment by bbatsov** [comment]
What's the point of using `tap` if you're not passing something to the block? The void context applies to method calls, not the blocks passed to them, so if `tap` returns something that makes the method a non-void method. Does this make any sense?

**Comment by untitaker** [comment]
Perhaps it helps if I define how I interpreted the source code.

To me `tap` is a non-void method precisely as you say, but *it itself is a void **context*** because it ignores the return value of the block it calls. The block itself just passes the value of the last expression to `tap`, but since that value is ultimatively discarded, the block itself is a void context too. Lastly, an expression of `1 + 1` inside of that block is also non-void, but inside the block it is in a void-context, which triggers the lint.

In that sense, `tap` and `each` are very similar to me because they are a void context (they discard the block's return value) and the blocks they call are too (the last expression's value is discarded).

To me "being a void context" (discarding the value of something) and "being void" (returning nothing) are completely orthogonal concepts. Again, **tap discards the block's value** (so it is a void context) but does return a value (so it is non-void). I don't think the latter is relevant.

**Comment by mikegee** [comment]
@untitaker your explanation makes sense too me. `tap` is like `each` in the "void"-ness of the method and the block. (It is unfortunate how we don't have good terms for these things.)

I'm still wondering one thing: why do you care? What problem does this PR solve? Hopefully that explanation will help clarify this issue further.

Thanks

**Comment by untitaker** [comment]
It is meant to uncover cases where you used tap and expected it in a way to behave like yield_self (because you dont know ruby well enough, which has been the case for me). I've given an example in the linked issue.

**Comment by mikegee** [comment]
Yes, #5512 does help. Thank you. 

I didn’t notice the linked issue on my first reading.

**Comment by untitaker** [comment]
ping @bbatsov, otherwise I think I'll just close this (don't want to drag out such a long discussion about something like this)

**Comment by bbatsov** [comment]
@untitaker I'm traveling for a few weeks and my time for OSS is quite limited right now. I'll take a look at this when I can. Or maybe @koic @jonas054 @Drenmi or @pocke can take it from here.

**Comment by jonas054** [comment]
I think I'd like to see an example added in `void_spec.rb` for `#tap`, using for instance the code from #5512.

**Comment by untitaker** [comment]
@jonas054 Done.

**Comment by untitaker** [comment]
While writing the test I found #5551

**Comment by jonas054** [comment]
:+1: Looks good!

**Pull request merged**
