### PR TITLE
No stopping

### PR DESCRIPTION
**Pull request by alexdowad**

### CODE REVIEW

**Comment by bbatsov** [comment]
Love the PR names! :-) Now you should add the same config for the `SymbolArray` cop. :-)

**Comment by alexdowad** [comment]
OK, sure.

**Comment by alexdowad** [comment]
Just added `AllowForAlignment` to `Style/SpaceAroundOperators` because it wouldn't let me align `||=`.

`Style/ExtraSpacing` seems to overlap *all* these other spacing cops. `ExtraSpacing` checks for more than 1 space between *each adjacent pair of tokens* and doesn't understand anything about the AST structure. All the other "spacing" cops work on ASTs and don't understand anything about tokens.

This creates a funny situation where you can tell `ExtraSpacing` to allow (or even enforce) extra spaces for alignment, but other cops complain.

@bbatsov will probably say: "Who wants extra spaces for alignment? I hate extra spaces for alignment." But a lot of progMultiSpaceAllowedrammers do like this style.

I see the benefit of splitting "spacing" checks into a number of different cops, since people can enable/disable them individually. The main problem is that all of those cops overlap with `ExtraSpacing`.

**Comment by alexdowad** [comment]
BTW the `AllowForAlignment` commit is not complete.

**Comment by alexdowad** [comment]
Added an incomplete version of the upgrade to `SymbolArray`. Still needs specs, changelog, better commit message, autocorrection.

**Comment by alexdowad** [comment]
Check out 2e141d9. @rrosenblum, your `StringReplacement` cop is significantly improved (along with a couple of others).

**Comment by alexdowad** [comment]
Don't merge this yet; I still need to polish up a couple things.

**Comment by alexdowad** [comment]
Sorry, but this sweetness is still not sweet enough to merge! Hold on please!

**Comment by alexdowad** [comment]
Updated `[Fix #2531]` based on feedback from @jonas054. Thanks for the code review!

**Comment by alexdowad** [comment]
Problem: `Lint/EndAlignment` vs. `Style/ElseAlignment`. They are very closely linked, but in different departments. Both should be `Style`.

**Comment by bbatsov** [comment]
MRI has an end alignment check, therefore `Lint/EndAlignment`. Not sure what the best solution here would be - both options are reasonable IMO (making both cops lint or style).

**Comment by alexdowad** [comment]
> Not sure what the best solution here would be - both options are reasonable IMO (making both cops lint or style).

I think these cops should actually be merged. The reason is that `Style/ElseAlignment` reads the config for `Lint/EndAlignment`, and follows its style. This is quite unusual -- one cop following the `EnforcedStyle` of another cop. If someone has an `ElseAlignment` offense in their code, it is quite counter-intuitive that the config for `EndAlignment` should be adjusted. This also is not good for `--auto-gen-config`.

**Comment by alexdowad** [comment]
I want to change the styles for `WordArray` and `SymbolArray` to `percent` and `brackets` rather than `percent` and `array`. Any comments on this?

**Comment by alexdowad** [comment]
This PR is getting out of control. I will try to polish up the few things which are still lacking so it can be merged before it grows any bigger...

**Comment by bbatsov** [comment]
> I think these cops should actually be merged. The reason is that Style/ElseAlignment reads the config for Lint/EndAlignment, and follows its style. This is quite unusual -- one cop following the EnforcedStyle of another cop. If someone has an ElseAlignment offense in their code, it is quite counter-intuitive that the config for EndAlignment should be adjusted. This also is not good for --auto-gen-config.

I seem to recall we had other cops like this, but yeah - the coupling between the cops is high and unusual. On the other hand - one bigger cop will be one bigger cop. Striking the right balance is sometimes hard.

**Comment by alexdowad** [comment]
> Striking the right balance is sometimes hard.

Very true. Would you like to make a call on this one?

**Comment by bbatsov** [comment]
> This PR is getting out of control. I will try to polish up the few things which are still lacking so it can be merged before it grows any bigger...

Sure. Just let us know when you think it's ready for a final review.

**Comment by bbatsov** [comment]
> Very true. Would you like to make a call on this one?

Merge those together, rename it to `Lint/KeywordAlignment` and make it possible to disable this for individual keywords (to emulate the effect of having separate cops).

**Comment by alexdowad** [comment]
Looks like there is no objection to `brackets` style rather than `array` style?

**Comment by bbatsov** [comment]
Yeah, no objections.

**Comment by alexdowad** [comment]
This is getting ridiculous. This PR just has to stop here.

A few questions/comments:

- What do you think of the warnings printed when obsolete config params are used? See ca76afe and 02be2e1. Maybe we need to crash RC hard rather than just printing warnings?
- I think the weird and anomalous behavior of `Lint/EndAlignment` as re: `case` nodes can be reverted now that we have `start_of_line` style. Comments? /CC @lumeet
- Further upgrades to `Style/SpaceAroundOperators` are coming, but not in this PR. Next one.
- Merging `ElseAlignment` and `EndAlignment` (as suggested by @bbatsov) will come in the next PR too. Not here, not now. No! Next one! Not this one!
- I want to give `ElseAlignment` a hard look and see how the new `start_of_line` style will affect it. Next PR! Not now! Sorry!

**Comment by bbatsov** [comment]
> What do you think of the warnings printed when obsolete config params are used? See ca76afe and 02be2e1. Maybe we need to crash RC hard rather than just printing warnings?

It's fine to crash.

**Comment by alexdowad** [comment]
Ready for final review!

**Comment by alexdowad** [comment]
Please take special note of fe64399. Not sure if you'll like this change.

**Comment by jonas054** [comment]
:+1: All good as far as I can see.

**Comment by bbatsov** [comment]
That was epic. In general it'd be nice to limit the scope of the PRs in the future, so it's easier to review them in a meaningful manner. Anyways, once again - fantastic work @alexdowad!

**Comment by alexdowad** [comment]
Thanks to @bbatsov and @jonas054 for code review. Will try to rein in these wild PRs in future.

**Pull request merged**
