### PR TITLE
 Improve configurable attributes section in the documentation

### PR DESCRIPTION
**Pull request by pocke**
The current documentation has some problems.

- "Important attributes" is not "important". It is "configurable".
- Relationships between `EnforcedStyle` and `SupportedStyles` are not clear.
- `nil` is not displayed.

This change will fix the problems.

before
----

after
----

### CODE REVIEW

**Comment by rrosenblum** [comment]
I like the style improvements. Is it necessary to explicitly surround the values with quotes? I think it would look better without the quotes.

**Comment by bbatsov** [comment]
Yeah, I'm also wondering about this.

I also think that for numberic values which should mention the type in `Configurable Values` somehow. Right now it looks a bit odd.

**Comment by Drenmi** [comment]
I kind of like the "default value - configurable values". 👍 

I think the confusion with the formatting here is the documentation now shows Ruby values, but configuration is done in YAML, not Ruby. Is it more or less helpful that it says `nil`? To me it makes it less clear what's going on. 🙂 What about something like `<none>`?

**Comment by pocke** [comment]
> I think it would look better without the quotes.

👍 

> I also think that for numberic values which should mention the type in Configurable Values somehow. Right now it looks a bit odd.

👍 

> What about something like <none>?

Good idea 👍

**Comment by pocke** [comment]
I updated this pull-request.

**Comment by bbatsov** [comment]
Looks awesome! 👍

**Pull request merged**
