### PR TITLE
Remove `Style/ExtendSelf` cop

### PR DESCRIPTION
**Pull request by pocke**
`Style/ExtendSelf` was introduced by #5108, but the cop duplicates with `Style/ModuleFunction`.
So this change reverts the commit (da69b88).

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
That's new. :rofl: Did you compare which one was implemented better?

**Comment by pocke** [comment]
I didn't compare them. I thought the new cop should be removed for compatibility, so I removed it. Maybe we should work on another pull-request to improve the cop's implementation.

**Comment by Drenmi** [comment]
Whoops! 😬

**Comment by bbatsov** [comment]
> I didn't compare them. I thought the new cop should be removed for compatibility, so I removed it. Maybe we should work on another pull-request to improve the cop's implementation.

@Drenmi Can you look into this? I wonder how you didn't notice the existing cop. 😆

**Comment by flyerhzm** [comment]
`Style/ExtendSelf` has an autocorrect method while `Style/ModuleFunction` does not, looks we should remove `Style/ModuleFunction` cop instead.

**Comment by pocke** [comment]
> Style/ExtendSelf has an autocorrect method while Style/ModuleFunction does not, looks we should remove Style/ModuleFunction cop instead.

Maybe we can move the auto-correction to `Style/ModuleFunction`. 👍 
And I think we can't remove `Style/ModuleFunction`, because some users configure the gem already. So if remove the cop, it's a breaking change.

**Pull request merged**
