### PR TITLE
Fix some Rubinius build errors

### PR DESCRIPTION
**Pull request by jawshooah**
Still getting segfaults when running the tests locally, but at least this is one issue out of the way.

[Review on Reviewable](https://reviewable.io/reviews/bbatsov/rubocop/2603)

### CODE REVIEW

**Comment by jawshooah** [comment]
`US-ASCII` failure is likely related to [this open issue](https://github.com/rubinius/rubinius/issues/3275).

**Comment by bbatsov** [comment]
Is this still relevant now that we're testing against rbx 3?

**Comment by jawshooah** [comment]
Difficult to tell, apparently rvm is having trouble installing rbx-3 on Travis. Here's the [most recent failure on master.](https://travis-ci.org/bbatsov/rubocop/jobs/105379041)

**Comment by bbatsov** [comment]
I'll close this due to the vagueness surrounding the nature of the problems we're trying to solve. Don't want to make rbx specific changes, unless it's 100% why they are needed.

**Pull request closed without merging**
