### PR TITLE
New cop AsciiCodeString

### PR DESCRIPTION
**Pull request by rrosenblum**
I came across this in Rails's source code and had to do some digging to figure out what it was. I couldn't find too much information, but it appears to be a legacy format from the early days of Ruby. I haven't come across a name this style of code. This might be something good to add to the style guide as well.

http://stackoverflow.com/questions/1270209/getting-an-ascii-character-code-in-ruby-using-question-mark-fails
http://stackoverflow.com/a/16641266
http://stackoverflow.com/a/1878406

### CODE REVIEW

**Comment by pocke** [comment]
I think this cop needs the following test cases.

```ruby
# copied from https://ruby-doc.org/core-2.3.0/doc/syntax/literals_rdoc.html#label-Strings 
\a             bell, ASCII 07h (BEL)
\b             backspace, ASCII 08h (BS)
\t             horizontal tab, ASCII 09h (TAB)
\n             newline (line feed), ASCII 0Ah (LF)
\v             vertical tab, ASCII 0Bh (VT)
\f             form feed, ASCII 0Ch (FF)
\r             carriage return, ASCII 0Dh (CR)
\e             escape, ASCII 1Bh (ESC)
\s             space, ASCII 20h (SPC)
\\             backslash, \
\nnn           octal bit pattern, where nnn is 1-3 octal digits ([0-7])
\xnn           hexadecimal bit pattern, where nn is 1-2 hexadecimal digits ([0-9a-fA-F])
\unnnn         Unicode character, where nnnn is exactly 4 hexadecimal digits ([0-9a-fA-F])
\u{nnnn ...}   Unicode character(s), where each nnnn is 1-6 hexadecimal digits ([0-9a-fA-F])
\cx or \C-x    control character, where x is an ASCII printable character
\M-x           meta character, where x is an ASCII printable character
\M-\C-x        meta control character, where x is an ASCII printable character
\M-\cx         same as above
\c\M-x         same as above
\c? or \C-?    delete, ASCII 7Fh (DEL)


# See. https://books.google.co.jp/books?id=jcUbTcr5XWwC&pg=PA54&lpg=PA54&dq=ruby+string+literal+question&source=bl&ots=fJHkvabvjE&sig=mfIS7P8XjR2EVUUk3gG-OrPYpWs&hl=ja&sa=X&ved=0ahUKEwiqpMvSoJ_PAhVKw2MKHaxBA-AQ6AEILTAC#v=onepage&q=ruby%20string%20literal%20question&f=false
?あ  # => 'あ'
```

And  maybe the cop auto-corrects incorrect ruby code when a literal has backslash,. Because the cop uses single quote for auto correction.

**Comment by rrosenblum** [comment]
Sounds good to me. I will update the code to use double quotes and add more tests.

**Comment by savef** [comment]
I might be missing something, but isn't this doing the same job as `Style/CharacterLiteral`?

**Comment by bbatsov** [comment]
> I might be missing something, but isn't this doing the same job as Style/CharacterLiteral?

Exactly. :-)

**Comment by rrosenblum** [comment]
Turns out this is exactly the same as `Style/CharacterLiteral`. I missed that when trying to see if there was already a cop for this. Closing.

**Pull request closed without merging**
