### PR TITLE
Show custom cops in --show-cops

### PR DESCRIPTION
**Pull request by ptarjan**
Before submitting a PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it)
* [x] Squashed related commits together.
* [ ] Added tests.
* [x] Added an entry to the [Changelog](CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by Neodelf** [comment]
Damn it! [Pull-request](https://github.com/bbatsov/rubocop/pull/3051) which resolves the issue was already created. May be I was should make a mark about it?

**Comment by bbatsov** [comment]
I don't have a preference who's PR we'll merge eventually. It's simply important to fix the issue at hand.

**Comment by ptarjan** [comment]
ditto

**Comment by Neodelf** [comment]
I just wanted to draw attention. I apologize if my words seem rude. Only positive! :)

**Comment by bbatsov** [comment]
@ptarjan Please, rebase this.

**Comment by ptarjan** [comment]
I'd love to figure out a way to do CHANGELOGs without getting so many merge conflicts.

**Comment by bbatsov** [comment]
> I'd love to figure out a way to do CHANGELOGs without getting so many merge conflicts.

Who wouldn't. :-) Unfortunately all automated solutions produce crappy changelogs and I don't want to write one just before the release.

The build is broken, btw.

**Comment by bbatsov** [comment]
P.S. I plan to cut a new release soon.

**Comment by ptarjan** [comment]
@bbatsov excited for the new cut. I rebased and repushed. That CHANGELOG will be the death of me.

**Comment by bbatsov** [comment]
> That CHANGELOG will be the death of me.

I don't like dealing with it either, but it's pretty useful at release time. :-)

**Comment by ptarjan** [comment]
Agreed, I just wish there was a format which didn't always merge conflict.

**Pull request merged**
