### PR TITLE
In for a tune-up

### PR DESCRIPTION
**Pull request by alexdowad**

### CODE REVIEW

**Comment by alexdowad** [comment]
35a46ee is significant; all contributors should have a look. This is designed to support the stress tests which I am just experimenting with.

The first stress tests would have been included here, but I have found that auto-correct is just too slow to make running them practicable, so I am working on auto-correct performance first. The few performance tweaks here were found while benchmarking autocorrection on the Rails codebase.

**Comment by bbatsov** [comment]
All changes look good to me.

**Comment by alexdowad** [comment]
OK, I added some new documentation to the README.

**Comment by bbatsov** [comment]
Another PR bites the dust! @alexdowad You're a legend! :-)

**Comment by jawshooah** [comment]
For real. Just give him commit access and be done with it :laughing:

**Comment by deivid-rodriguez** [comment]
Yes, never seen anything like that! :astonished:

**Pull request merged**
