### PR TITLE
[Refactor] Do autocorrect in ExtraSpacing in a more standard way

### PR DESCRIPTION
**Pull request by jonas054**
Implement `#autocorrect` as we usually do, rather than overriding `Cop#correct`.

I didn't quite get why it was done differently in this cop. @alexdowad perhaps you can explain.

### CODE REVIEW

**Comment by alexdowad** [comment]
> I didn't quite get why it was done differently in this cop. @alexdowad perhaps you can explain.

I'm racking my memory trying to remember. There was a reason...

**Comment by alexdowad** [comment]
@jonas054, I think your patch is just fine and will help to standardize things.

One thing about this cop is that it registers an offense for *each* equals sign which is out of alignment with other contiguous assignments. But when correcting, it doesn't work well to correct them one by one. It is much easier to correct a group of contiguous lines at the same time.

However, RC will still call into `autocorrect` for *each* of those offenses, even those which were already corrected when inspecting a different line.

So instead I replaced `correct` and used that `@corrected.add?(token)` guard clause to only add as many lambdas to `@corrections` as there are tokens to correct.

With this update, RC will call into `autocorrect` more times than is necessary, and will add more lambdas than is necessary to `@corrections`. But the guard clause will stop most of those lambdas from doing anything unnecessary. So that is OK.

**Comment by jonas054** [comment]
@alexdowad Thanks!
@bbatsov My conclusion is that this would be good to merge. More standardized and thus easier to understand. All signs point to no significant impact on performance.

**Comment by bbatsov** [comment]
I'm all for easier to understand. :-)

**Pull request merged**
