### PR TITLE
[Fix #3311] Detect encoding incompatibilities to spare bad autocorrection

### LINKED ISSUE #3311: Undesired string literal replacements when UTF8 locale not set in ENV
We upgraded Rubocop from 0.38.0 to 0.41.2 in our app. Suddenly Rubocop wanted to replace stuff like:

*  `"En kort men bra text varför jag ska försöka erövra denna trofé"`
* with `"En kort men bra text varf\u00F6r jag ska f\u00F6rs\u00F6ka er\u00F6vra denna trof\u00E9"`. 

However the first variant is valid UTF-8, and much more readable.

It turns out that our locale in ENV was not set up for UTF-8. See below for a reproducible example.

This is more of a FYI, since it's something new introduced between 0.38.0 and 0.41.2 that could be very confusing and irritating to end-users. I don't know if it should be fixed, just documented or nothing needs to be done about this. It took me some time to figure out Rubocop works as desired if I set my locale correctly.

--------

## Expected behavior

* That both of the test runs below should pass.
* That Rubocop wouldn't be dependent on locale in ENV.

## Actual behavior

One of the tests fail after changing locale in ENV.

## Steps to reproduce the problem

```sh
vagrant@vagrant-machine:~/temp/rubocop$ export LC_ALL=en_US.UTF-8
vagrant@vagrant-machine:~/temp/rubocop$ export LANG=en_US.UTF-8
vagrant@vagrant-machine:~/temp/rubocop$ export LANGUAGE=en_US.UTF-8
vagrant@vagrant-machine:~/temp/rubocop$ bundle exec rspec ./spec/rubocop/cop/style/string_literals_spec.rb
Run options:
  include {:focus=>true}
  exclude {:broken=>#<Proc:./spec/spec_helper.rb:33>}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 17674
....................................................

Finished in 0.17152 seconds (files took 0.48332 seconds to load)
52 examples, 0 failures

Randomized with seed 17674

vagrant@vagrant-machine:~/temp/rubocop$ export LANGUAGE=en_US
vagrant@vagrant-machine:~/temp/rubocop$ export LANG=en_US
vagrant@vagrant-machine:~/temp/rubocop$ export LC_ALL=en_US
vagrant@vagrant-machine:~/temp/rubocop$ bundle exec rspec ./spec/rubocop/cop/style/string_literals_spec.rb
Run options:
  include {:focus=>true}
  exclude {:broken=>#<Proc:./spec/spec_helper.rb:33>}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 9774
....................................F...............

Failures:

  1) RuboCop::Cop::Style::StringLiterals configured with single quotes preferred autocorrects words with non-ascii chars
     Failure/Error: expect(new_source).to eq("'EspaÃ±a'")

       expected: "'Espa\u00F1a'"
            got: "\"Espa\\u00F1a\""

       (compared using ==)
     # ./spec/rubocop/cop/style/string_literals_spec.rb:177:in `block (3 levels) in <top (required)>'

Finished in 0.16386 seconds (files took 0.52398 seconds to load)
52 examples, 1 failure

Failed examples:

rspec ./spec/rubocop/cop/style/string_literals_spec.rb:175 # RuboCop::Cop::Style::StringLiterals configured with single quotes preferred autocorrects words with non-ascii chars

Randomized with seed 9774
```

## RuboCop version

```sh
vagrant@vagrant-machine:~/temp/rubocop$ ./bin/rubocop -V
0.41.2 (using Parser 2.3.1.2, running on ruby 2.3.0 x86_64-linux)

vagrant@vagrant-machine:~/temp/rubocop$ git rev-parse HEAD
77ebfd6113e1a0077b400c937c28be5e82022c22
```

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This was a nasty one but I think I fixed it.

I added a couple of regression tests because I thought my fix would regress but it actually didn't. Let me know if you think it's worth keeping those.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [ ] All tests are passing.
* [ ] The new code doesn't generate RuboCop offenses.
* [ ] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I noticed that the tests against an ASCII external encoding were not being run in Travis, so I added an extra commit to enable them in a9fb17ed650d358729bc8b72f7b4195857cf7db5.

At this point, we're just running the default rake task, which is what Travis run by default. So the `script` section in the `.travis.yml` file could be completely dropped if you find the implicit style preferable.

**Comment by deivid-rodriguez** [comment]
Mmmm, the build is failing. Since I was running these changes on top of #3547 and the build was passing, I guess this needs #3547 to land first.

**Comment by bbatsov** [comment]
#3547 was merged. Guess you should rebase your branch now.

**Comment by deivid-rodriguez** [comment]
Ok, just rebased this but it failed again. So this needs more work. Will let you know when it's ready!

**Comment by deivid-rodriguez** [comment]
Here you go, it's passing now!

**Pull request merged**
