### PR TITLE
Sort configuration key alphabetically

### PR DESCRIPTION
**Pull request by wata727**
Ref: https://github.com/bbatsov/rubocop/pull/5174

Additions to `config/enabled.yml` are inserted alphabetically.
However, since `config/enabled.yml` is not currently in alphabetical order, it sorts it.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by pocke** [comment]
Good catch! But unfortunately the config file is not sorted completely.

```bash
# Preparing
$ git checkout origin/master
$ cp config/enabled.yml before.yml
$ git checkout wata727/sort_enabled_yml
$ cp config/enabled.yml after.yml

# A script to check equivalent. It's ok
$ ruby -ryaml -e 'p YAML.load_file("before.yml") == YAML.load_file("after.yml")'
true

# Scripts to check it is sortred
$ ruby -rpp -ryaml -e 'File.read("after.yml").each_line.grep(/^\w/).tap{|l| pp l.sort}' > sorted
$ ruby -rpp -ryaml -e 'File.read("after.yml").each_line.grep(/^\w/).tap{|l| pp l}' > not-sorted
$ git diff --no-index not-sorted sorted
diff --git a/not-sorted b/sorted
index 24b1204..b839962 100644
--- a/not-sorted
+++ b/sorted
@@ -14,6 +14,7 @@
  "Layout/CommentIndentation:\n",
  "Layout/DotPosition:\n",
  "Layout/ElseAlignment:\n",
+ "Layout/EmptyLineAfterMagicComment:\n",
  "Layout/EmptyLineBetweenDefs:\n",
  "Layout/EmptyLines:\n",
  "Layout/EmptyLinesAroundAccessModifier:\n",
@@ -21,19 +22,18 @@
  "Layout/EmptyLinesAroundBlockBody:\n",
  "Layout/EmptyLinesAroundClassBody:\n",
  "Layout/EmptyLinesAroundExceptionHandlingKeywords:\n",
- "Layout/EmptyLinesAroundModuleBody:\n",
  "Layout/EmptyLinesAroundMethodBody:\n",
+ "Layout/EmptyLinesAroundModuleBody:\n",
  "Layout/EndOfLine:\n",
  "Layout/ExtraSpacing:\n",
- "Layout/InitialIndentation:\n",
  "Layout/FirstParameterIndentation:\n",
- "Layout/IndentationConsistency:\n",
- "Layout/IndentationWidth:\n",
  "Layout/IndentArray:\n",
  "Layout/IndentAssignment:\n",
  "Layout/IndentHash:\n",
  "Layout/IndentHeredoc:\n",
- "Layout/SpaceInLambdaLiteral:\n",
+ "Layout/IndentationConsistency:\n",
+ "Layout/IndentationWidth:\n",
+ "Layout/InitialIndentation:\n",
  "Layout/LeadingCommentSpace:\n",
  "Layout/MultilineArrayBraceLayout:\n",
  "Layout/MultilineBlockLayout:\n",
@@ -42,28 +42,28 @@
  "Layout/MultilineMethodCallIndentation:\n",
  "Layout/MultilineMethodDefinitionBraceLayout:\n",
  "Layout/MultilineOperationIndentation:\n",
- "Layout/EmptyLineAfterMagicComment:\n",
  "Layout/RescueEnsureAlignment:\n",
- "Layout/SpaceBeforeFirstArg:\n",
  "Layout/SpaceAfterColon:\n",
  "Layout/SpaceAfterComma:\n",
  "Layout/SpaceAfterMethodName:\n",
  "Layout/SpaceAfterNot:\n",
  "Layout/SpaceAfterSemicolon:\n",
- "Layout/SpaceBeforeBlockBraces:\n",
- "Layout/SpaceBeforeComma:\n",
- "Layout/SpaceBeforeComment:\n",
- "Layout/SpaceBeforeSemicolon:\n",
- "Layout/SpaceInsideBlockBraces:\n",
  "Layout/SpaceAroundBlockParameters:\n",
  "Layout/SpaceAroundEqualsInParameterDefault:\n",
  "Layout/SpaceAroundKeyword:\n",
  "Layout/SpaceAroundOperators:\n",
+ "Layout/SpaceBeforeBlockBraces:\n",
+ "Layout/SpaceBeforeComma:\n",
+ "Layout/SpaceBeforeComment:\n",
+ "Layout/SpaceBeforeFirstArg:\n",
+ "Layout/SpaceBeforeSemicolon:\n",
+ "Layout/SpaceInLambdaLiteral:\n",
  "Layout/SpaceInsideArrayPercentLiteral:\n",
- "Layout/SpaceInsidePercentLiteralDelimiters:\n",
+ "Layout/SpaceInsideBlockBraces:\n",
  "Layout/SpaceInsideBrackets:\n",
  "Layout/SpaceInsideHashLiteralBraces:\n",
  "Layout/SpaceInsideParens:\n",
+ "Layout/SpaceInsidePercentLiteralDelimiters:\n",
  "Layout/SpaceInsideRangeLiteral:\n",
  "Layout/SpaceInsideStringInterpolation:\n",
  "Layout/Tab:\n",
@@ -118,6 +118,7 @@
  "Lint/RequireParentheses:\n",
  "Lint/RescueException:\n",
  "Lint/RescueType:\n",
+ "Lint/ReturnInVoidContext:\n",
  "Lint/SafeNavigationChain:\n",
  "Lint/ScriptPermission:\n",
  "Lint/ShadowedArgument:\n",
@@ -130,30 +131,30 @@
  "Lint/UnneededDisable:\n",
  "Lint/UnneededRequireStatement:\n",
  "Lint/UnneededSplatExpansion:\n",
+ "Lint/UnreachableCode:\n",
  "Lint/UnusedBlockArgument:\n",
  "Lint/UnusedMethodArgument:\n",
- "Lint/UnreachableCode:\n",
  "Lint/UriEscapeUnescape:\n",
  "Lint/UriRegexp:\n",
  "Lint/UselessAccessModifier:\n",
  "Lint/UselessAssignment:\n",
  "Lint/UselessComparison:\n",
  "Lint/UselessElseWithoutRescue:\n",
- "Lint/ReturnInVoidContext:\n",
  "Lint/UselessSetterCall:\n",
  "Lint/Void:\n",
  "Metrics/AbcSize:\n",
+ "Metrics/BlockLength:\n",
  "Metrics/BlockNesting:\n",
  "Metrics/ClassLength:\n",
- "Metrics/ModuleLength:\n",
  "Metrics/CyclomaticComplexity:\n",
  "Metrics/LineLength:\n",
  "Metrics/MethodLength:\n",
- "Metrics/BlockLength:\n",
+ "Metrics/ModuleLength:\n",
  "Metrics/ParameterLists:\n",
  "Metrics/PerceivedComplexity:\n",
  "Naming/AccessorMethodName:\n",
  "Naming/AsciiIdentifiers:\n",
+ "Naming/BinaryOperatorParameterName:\n",
  "Naming/ClassAndModuleCamelCase:\n",
  "Naming/ConstantName:\n",
  "Naming/FileName:\n",
@@ -161,12 +162,12 @@
  "Naming/HeredocDelimiterNaming:\n",
  "Naming/MethodName:\n",
  "Naming/PredicateName:\n",
- "Naming/BinaryOperatorParameterName:\n",
  "Naming/VariableName:\n",
  "Naming/VariableNumber:\n",
  "Performance/Caller:\n",
- "Performance/Casecmp:\n",
  "Performance/CaseWhenSplat:\n",
+ "Performance/Casecmp:\n",
+ "Performance/CompareWithBlock:\n",
  "Performance/Count:\n",
  "Performance/Detect:\n",
  "Performance/DoubleStartEndWith:\n",
@@ -184,16 +185,15 @@
  "Performance/ReverseEach:\n",
  "Performance/Sample:\n",
  "Performance/Size:\n",
- "Performance/CompareWithBlock:\n",
  "Performance/StartWith:\n",
  "Performance/StringReplacement:\n",
  "Performance/TimesMap:\n",
  "Performance/UnfreezeString:\n",
  "Performance/UriDefaultParser:\n",
  "Rails/ActionFilter:\n",
+ "Rails/ActiveSupportAliases:\n",
  "Rails/ApplicationJob:\n",
  "Rails/ApplicationRecord:\n",
- "Rails/ActiveSupportAliases:\n",
  "Rails/Blank:\n",
  "Rails/CreateTableWithTimestamps:\n",
  "Rails/Date:\n",
@@ -221,10 +221,10 @@
  "Rails/ReversibleMigration:\n",
  "Rails/SafeNavigation:\n",
  "Rails/ScopeArgs:\n",
+ "Rails/SkipsModelValidations:\n",
  "Rails/TimeZone:\n",
  "Rails/UniqBeforePluck:\n",
  "Rails/UnknownEnv:\n",
- "Rails/SkipsModelValidations:\n",
  "Rails/Validation:\n",
  "Security/Eval:\n",
  "Security/JSONLoad:\n",
@@ -235,8 +235,8 @@
  "Style/ArrayJoin:\n",
  "Style/AsciiComments:\n",
  "Style/Attr:\n",
- "Style/BeginBlock:\n",
  "Style/BarePercentLiterals:\n",
+ "Style/BeginBlock:\n",
  "Style/BlockComments:\n",
  "Style/BlockDelimiters:\n",
  "Style/BracesAroundHashParameters:\n",
@@ -259,27 +259,29 @@
  "Style/DoubleNegation:\n",
  "Style/EachForSimpleLoop:\n",
  "Style/EachWithObject:\n",
- "Style/EmptyElse:\n",
+ "Style/EmptyBlockParameter:\n",
  "Style/EmptyCaseCondition:\n",
+ "Style/EmptyElse:\n",
+ "Style/EmptyLambdaParameter:\n",
  "Style/EmptyLiteral:\n",
  "Style/EmptyMethod:\n",
- "Style/EndBlock:\n",
  "Style/Encoding:\n",
+ "Style/EndBlock:\n",
  "Style/EvenOdd:\n",
  "Style/ExtendSelf:\n",
- "Style/FrozenStringLiteralComment:\n",
  "Style/FlipFlop:\n",
  "Style/For:\n",
  "Style/FormatString:\n",
  "Style/FormatStringToken:\n",
+ "Style/FrozenStringLiteralComment:\n",
  "Style/GlobalVars:\n",
  "Style/GuardClause:\n",
  "Style/HashSyntax:\n",
+ "Style/IdenticalConditionalBranches:\n",
  "Style/IfInsideElse:\n",
  "Style/IfUnlessModifier:\n",
  "Style/IfUnlessModifierOfIfUnless:\n",
  "Style/IfWithSemicolon:\n",
- "Style/IdenticalConditionalBranches:\n",
  "Style/InfiniteLoop:\n",
  "Style/InverseMethods:\n",
  "Style/Lambda:\n",
@@ -290,10 +292,11 @@
  "Style/MethodMissing:\n",
  "Style/MinMax:\n",
  "Style/MixinGrouping:\n",
+ "Style/MixinUsage:\n",
  "Style/ModuleFunction:\n",
  "Style/MultilineBlockChain:\n",
- "Style/MultilineIfThen:\n",
  "Style/MultilineIfModifier:\n",
+ "Style/MultilineIfThen:\n",
  "Style/MultilineMemoization:\n",
  "Style/MultilineTernaryOperator:\n",
  "Style/MultipleComparison:\n",
@@ -307,8 +310,8 @@
  "Style/NilComparison:\n",
  "Style/NonNilCheck:\n",
  "Style/Not:\n",
- "Style/NumericLiterals:\n",
  "Style/NumericLiteralPrefix:\n",
+ "Style/NumericLiterals:\n",
  "Style/NumericPredicate:\n",
  "Style/OneLineConditional:\n",
  "Style/OptionalArguments:\n",
@@ -318,8 +321,6 @@
  "Style/PercentLiteralDelimiters:\n",
  "Style/PercentQLiterals:\n",
  "Style/PerlBackrefs:\n",
- "Style/EmptyBlockParameter:\n",
- "Style/EmptyLambdaParameter:\n",
  "Style/PreferredHashMethods:\n",
  "Style/Proc:\n",
  "Style/RaiseArgs:\n",
@@ -349,17 +350,16 @@
  "Style/SymbolLiteral:\n",
  "Style/SymbolProc:\n",
  "Style/TernaryParentheses:\n",
- "Style/MixinUsage:\n",
  "Style/TrailingBodyOnMethodDefinition:\n",
  "Style/TrailingCommaInArguments:\n",
  "Style/TrailingCommaInLiteral:\n",
  "Style/TrailingMethodEndStatement:\n",
+ "Style/TrailingUnderscoreVariable:\n",
  "Style/TrivialAccessors:\n",
  "Style/UnlessElse:\n",
  "Style/UnneededCapitalW:\n",
  "Style/UnneededInterpolation:\n",
  "Style/UnneededPercentQ:\n",
- "Style/TrailingUnderscoreVariable:\n",
  "Style/VariableInterpolation:\n",
  "Style/WhenThen:\n",
  "Style/WhileUntilDo:\n",
```

**Comment by pocke** [comment]
And probably we can add a test or something that checks the config files are sorted in another pull-request.

**Comment by bbatsov** [comment]
> And probably we can add a test or something that checks the config files are sorted in another pull-request.

👍

**Comment by bbatsov** [comment]
👍

**Pull request merged**
