### PR TITLE
Refactor finding file upwards

### PR DESCRIPTION
**Pull request by ybiquitous**
See <https://github.com/bbatsov/rubocop/pull/5326#issuecomment-354112118>.

Changes about this refactoring:

- Extract methods from `PathUtil` to new module `FileFinder`
  - `FileFinder#find_file_upwards` (returns string)
  - `FileFinder#find_files_upwards` (returns string array)

- Replace `ConfigLoader` methods with `FileFinder` methods

- Move code about `root_level` in `ConfigLoader` to `FileFinder`

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
The build has failed.

**Comment by ybiquitous** [comment]
> The build has failed.

Sorry... 😓 I'm researching the cause of failure.

**Comment by ybiquitous** [comment]
```
$ bundle exec rake parallel:spec

...

The following suites were discovered but were not run:
./spec/isolated_environment_spec.rb[1] - /home/travis/build/bbatsov/rubocop/spec/isolated_environment_spec.rb

rake aborted!
Command failed with status (2): [rspec-queue spec/...]
```

**Comment by ybiquitous** [comment]
Tests are passed! But fetching system gem is failed.

```
$ gem update --system
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    timed out (https://api.rubygems.org/specs.4.8.gz)
```

**Comment by ybiquitous** [comment]
The failed test shown in https://github.com/bbatsov/rubocop/pull/5351#issuecomment-354942710 is fixed via 2aae303. (The cause is incorrect `root_level` check position)

```
The following suites were discovered but were not run:
./spec/isolated_environment_spec.rb[1] - /home/travis/build/bbatsov/rubocop/spec/isolated_environment_spec.rb
```

It took a lot of time to solve this failure in only parallel tests, because this failure message is unfamiliar to me and it seems that `Kernel::exit` should be used in `RuboCop::ConfigLoader::read_file`.

https://github.com/bbatsov/rubocop/blob/ca594e82d6c35c1eafb909b3c84ab135d7db9d80/lib/rubocop/config_loader.rb#L168

Although `RuboCop::CLI#run` returns exit status, `RuboCop::ConfigLoader::read_file` may exit a program. I think this behavior is unconsistent.

https://github.com/bbatsov/rubocop/blob/3e064e970e4f8e04ffa409a6994a8e0c8b6d9311/lib/rubocop/cli.rb#L33

For example, a refactoring idea:

```diff
rescue Errno::ENOENT
- warn(format('Configuration file not found: %s', absolute_path))
- exit(Errno::ENOENT::Errno)
+ raise RuboCop::ConfigurationNotFoundError, "Configuration file not found: #{absolute_path}"
end
```

What do you think about this?

**Comment by ybiquitous** [comment]
An example for https://github.com/bbatsov/rubocop/pull/5351#issuecomment-354993739:

https://github.com/bbatsov/rubocop/compare/master...ybiquitous:refactor-avoid-exit-in-config-loader

**Comment by bbatsov** [comment]
> What do you think about this?

@koic (I think) did this, so users won't see an ugly stacktrace and just a nice error message, but you do raise a valid point. I wonder if we can't come up with some reasonable solution that doesn't result in dumping a stracktrace to the users.

**Comment by bbatsov** [comment]
I guess we can catch this somewhere in `run` and that would solve both problems.

**Comment by ybiquitous** [comment]
> I guess we can catch this somewhere in run and that would solve both problems.

Yes. 👍 Like below: 

```diff
class RuboCop::CLI
  def run(args = ARGV)
    # ...
+ rescue RuboCop::ConfigNotFoundError => e
+  warn e.message
+  return e.status
  rescue RuboCop::Error => e
    warn Rainbow("Error: #{e.message}").red
    return 2
    # ...
  end
end
```

https://github.com/ybiquitous/rubocop/blob/fcd666811e8f1e4ec4e1cf0523c48445f2012cad/lib/rubocop/cli.rb#L39

**Comment by bbatsov** [comment]
@ybiquitous OK, let's do this.

**Comment by ybiquitous** [comment]
OK! I opened PR #5386. Please check it! 😁

**Comment by bbatsov** [comment]
Great! Can you also rebase this branch on top of `master` and squash the commit into it?

**Comment by ybiquitous** [comment]
> Can you also rebase this branch on top of master and squash the commit into it?

Do you mean that "this branch" is [`ybiquitous:refactor-avoid-exit-in-config-loader`](https://github.com/ybiquitous/rubocop/tree/refactor-avoid-exit-in-config-loader), or [`ybiquitous:refactor-finding-file-upwards`](https://github.com/ybiquitous/rubocop/tree/refactor-finding-file-upwards)?

**Comment by bbatsov** [comment]
"ybiquitous:refactor-finding-file-upwards"

**Comment by ybiquitous** [comment]
I rebased this branch onto master branch. Please check it! 🙏

**Comment by bbatsov** [comment]
Thanks!

**Comment by ybiquitous** [comment]
You're welcome! Thanks a lot for your review! 😊

**Pull request merged**
