### PR TITLE
A big step forward for performance linting

### PR DESCRIPTION
**Pull request by alexdowad**
This is some code I wrote last month and never opened a PR for. I wanted to close out #1677, but there is one more cop which is needed. Unfortunately, implementing that one cop will require a more sophisticated way of auto-correction.

Basically, implementing auto-correction in that last cop will be *very* tricky using just textual manipulation (regexes and "cut-and-paste"). We need the ability to manipulate Ruby code at the AST level.

`unparser` can do this; it can take an AST produced by `parser` and convert it back to syntactically correct Ruby code. You can parse Ruby code into an AST, add some nodes, delete some nodes, or move nodes around in the tree, then "unparse" it to Ruby code. If you tried doing this using "cut-and-paste", there would be all kinds of issues with operator precedence and other things which would cause breakage.

With the power of `unparser`, all kinds of auto-corrections which would otherwise be insanely difficult become trivially easy.

The problem is that the code emitted by `unparser` is not formatted the way we would like. I wrote some patches for `unparser` which make the output much nicer, to the point that it could be usable by RuboCop, but the maintainer is taking forever to review the patches, and there are other reasons why I feel `unparser` may not integrate well into RuboCop.

One option is to fork `unparser` and remake it into something more suitable for RC. Another is to write something comparable from scratch.

Anyways, rather than holding onto this code and not letting anyone benefit from it, I am opening a partial PR first. This *almost* finishes up #1677.

### CODE REVIEW

**Comment by bbatsov** [comment]
There are a few commit messages, that don't start with an imperative verb. 

> One option is to fork unparser and remake it into something more suitable for RC. Another is to write something comparable from scratch.

Both options are ok for me. Haven't played with `unparser`, so I can't really say how much do we need from it. I'm not also not sure how robust it is in general...

**Comment by alexdowad** [comment]
> There are a few commit messages, that don't start with an imperative verb.

Yep. Sometimes this communicates what the commit is about, in a briefer and less repetitious way.

> Haven't played with unparser, so I can't really say how much do we need from it. I'm not also not sure how robust it is in general...

In terms of emitting Ruby code which "works", it's industrial strength. Heavy duty. Tested, tried, and true. You can sleep soundly with `unparser` unparsing your ASTs.

Its problem is not in emitting correct Ruby code, but 1) emitting code with the desired formatting, and 2) pulling in too many other dependencies, which could cause gem version conflicts for some RC users.

It also has the slight problem of munching up your comments like a delicious snack, but I have fixed that one (if the maintainer ever merges my patches).

I was just fixing up this PR, then ran into a problem with `parser`, and wrote a couple patches to fix it up. We'll see what @whitequark says. Then this PR can go ahead.

**Comment by alexdowad** [comment]
Still need to add a couple more tests.

**Comment by alexdowad** [comment]
- Resolved problem with changelog.
- Resolved issue with `Pry.rescue`... thanks to @rrosenblum for that one.
- `Performance/RedundantMerge` is much smarter now about when not to register an error... thanks to @rrosenblum.

Still need to add more tests.

**Comment by alexdowad** [comment]
- Added 1 spec for each new cop which checks the generated error message.
- `Performance/RedundantMatch` has become smarter about when it is OK to convert `match` to `=~`.

**Comment by alexdowad** [comment]
This is failing solely because of the bug in the latest Bundler. I think @bbatsov is already aware of it (from my posts over at the `parser` repo).

**Comment by alexdowad** [comment]
Just slipped in a couple other fixes and enhancements...

This will be broken until a new `parser` gem is released. Hoping it comes very soon.

**Comment by alexdowad** [comment]
Bumped `parser` to 2.3.0.pre.5. I had to adjust one spec due to a small change in the line number which a syntax error is reported on -- but it actually makes more sense the new way. Otherwise, all specs still pass with the latest `parser`.

**Comment by bbatsov** [comment]
Do you have more work to do on this PR?

**Comment by alexdowad** [comment]
Hi @bbatsov... I put a lot in this PR in an attempt to avoid extra rebasing. I'm not going to jam anything more in, because it is already too big. Once you think this one is ready to merge, I will open another PR with some other commits which I have prepared since then.

In short: no.

**Comment by alexdowad** [comment]
Updated based on suggestions from @bbatsov.

**Comment by bbatsov** [comment]
You'll also have to rebase.

**Comment by alexdowad** [comment]
Rebased.

**Comment by bbatsov** [comment]
:+1:

**Comment by alexdowad** [comment]
Thanks!

**Comment by jacob-carlborg** [comment]
I just got bitten by the cop to use `yield` instead of `block.call`. I use a block parameter all over the place. Mostly because it adds documentation. You can read the signature of a method and immediately see if the method takes a block or not.

**Comment by mbj** [comment]
@alexdowad Hi, just saw this (for context, I'm the unparser maintainer you mention above multiple times).

At the time you where writing this unparser was on life support. OSS is a funny economy to deal with given unless a project is insanely popular you earn 0$ - which does not help in feeding kids etc.

Recently I turned [mutant](https://github.com/mbj/mutant) into a commercial offering, which changed the "life support" status of unparser significantly. Since re-wrote unparser with full 2.7 support and fixed lots of AST invariance bugs, many of them via re-using the parser test suite as edge case source. Also the emitted source is now way cleaner, especially dynamic strings.

I've to admit I was a bit triggered by your "if the maintainer ever" etc comments I had to read above. But I think you also had your reasons, no bad feelings at this point from me.

Anyhow this is a heads up. Should you ever have to look at unparser again I'd want to ask that you re-evaluate it, as its now an integral part of what makes my living.

**Pull request merged**
