### PR TITLE
Fix #2679 auto-gen-config and line length

### LINKED ISSUE #2679: auto-gen-config generated Style/GuardClause Exclude doesn't seem to work
Running `rubocop --auto-gen-config` generated a config like:

```
Style/GuardClause:
  Exclude:
    - 'app/controllers/some_controller.rb'
```

but running rubocop again with that config would still report the same error in some_controller.rb

Only setting

```
Style/GuardClause:
  Enabled: false
```

turned it off effectively. Exclude lists seem to work correctly for other Style/\* cops.

### LINKED ISSUE #3496: Running after `--auto-gen-config` does not ignore all convention offenses
I have a large codebase that I'm trying to make pass rubocop. However, while I work on that, I wanted to setup the `.rubocop_todo.yml` to ignore all existing offenses so that I can run it on CI and avoid having the rest of my team introduce new rubocop offenses. I understand that's one of the main purposes of `--auto-gen-config`.

When I run `rubocop --auto-gen-config`, it shows 16,000+ offenses and generates the proper `.rubocop_todo.yml`. However, after setting rubocop to inherit from that file and running `rubocop`, it still shows 4000+ offenses, all of which are `C` (convention) offenses. 

I've run `rubocop --format offenses` and all of the cops reporting offenses are included in the `.rubocop_todo.yml` with the correct config so that they should be ignored, but they are not.

Do I need to be running it with a certain flag to ignore convention offenses in `.rubocop_todo.yml`? I do not want to ignore all convention offenses, just those listed in the todo file.

Unfortunately, this is a private repo so I cannot post code samples. If needed, I can spin up a new app and try to reproduce.

---
## Expected behavior

I expected the auto generated config to ignore all errors, warnings, conventions, and everything else rubocop found if `.rubocop_todo.yml` is inherited from in `.rubocop.yml`.
## Actual behavior

rubocop ignored all warnings but did not ignore conventions.
## Steps to reproduce the problem
1. Run `rubocop --auto-gen-config`
2. Add `inherit_from: .rubocop_todo.yml` to top of `.rubocop.yml`
3. Run `rubocop`
## RuboCop version

```
$ rubocop -V
0.42.0 (using Parser 2.3.1.2, running on ruby 2.2.4 x86_64-darwin14)
```

### PR DESCRIPTION
**Pull request by jonas054**
This change contains a solution for the old problem of cops that depend on the configuration of `Metrics/LineLength` getting the wrong settings in `.rubocop_todo.yml`. Then there are some refactoring commits to fix metrics that had gone over the limit.

Also fixes #3496.

### CODE REVIEW

**Comment by jonas054** [comment]
The error on AppVeyor is
```
gem update --system --no-document
ERROR:  While executing gem ... (NoMethodError)
    undefined method `files=' for nil:NilClass
```
I assume this is an intermittent error, not related to my changes.

**Comment by garettarrowood** [comment]
I believe I am running into `rubocop_todo.yml` generation breakage with this change. I have a large work repo with _many_ Ruby apps that inherit from a central file. I am upgrading `rubocop` from `0.51.0` to `0.52.1`.  When I comment out the `Metrics/LineLength` `Max` setting in the central file, everything works correctly. When I comment back the `Metrics/LineLength` `Max` setting, the `todo` generation misses a number of violations.

Specifically -

1. `Style/WhileUntilModifier`
1. `Style/IfUnlessModifier`
1. `Lint/UnneededDisable`
1. and 1 occurrence of `Metrics/BlockLength` (I'll double check this one)

**Comment by garettarrowood** [comment]
It looks like the part of the reason for the issue is that both the inherited rubocop file and the current file both set `Metrics/LineLength`'s `Max`.

**Comment by garettarrowood** [comment]
The `Lint/UnneededDisable` seems like a different/new issue.  I'll try to summarize in a new issue.

**Comment by garettarrowood** [comment]
Inheriting a `.rubocop.yml` appears to play no part in this bug. I am able to reproduce the bug by putting any `Metrics/LineLength` `Max` value in a single Ruby gem's `.rubocop.yml` file, having `Style/WhileUntilModifier` and `Style/IfUnlessModifier` offenses in the gem, then running `rubocop auto-gen-config`.  I'm still unsure why some offenses are accurately added to the todo and some are missed.  I can follow up with the particular offenses if it is relevant.

**Comment by garettarrowood** [comment]
I've laid out a new issue for this on #5422 .

**Comment by garettarrowood** [comment]
Last note for the record. There was no issue with `Lint/UnneededDisable`. It actually was a similar issue to what is outlined in the linked issue above, but with `Metrics/BlockLength` instead of `Metrics/LineLength`.

**Pull request merged**
