### PR TITLE
Print warning message if misconfiguration prevents a cop from working, but don't count as error

### PR DESCRIPTION
**Pull request by alexdowad**
Just took a crack at fixing #2068...

I'm sure this will need some more work, but some feedback at this point would be appreciated.

### CODE REVIEW

**Comment by alexdowad** [comment]
RuboCop complains about a "Missing top-level module documentation comment" here. But none of the other source files have a "top-level module documentation comment" on "module RuboCop" either, and there are no warnings. What gives?

**Comment by jonas054** [comment]
The `Documentation` cop has certain rules for determining if a module is a namespace or not. Your implementation didn't meet the criteria. If you change it to
```ruby
  class Warning < StandardError
  end
```
you'll be fine.

**Comment by alexdowad** [comment]
@jonas054 Thanks for the tip. I just opened a PR which makes `Style/Documentation` a bit smarter about this.

**Comment by bbatsov** [comment]
Looks good to me, apart from the failing build and the need to be rebase.

**Comment by bbatsov** [comment]
P.S. Probably other cops can benefit from something like this, but nothing comes to mind immediately.

**Comment by alexdowad** [comment]
Yeah, I was thinking the same about the other cops. Anyways, updated and rebased.

**Comment by bbatsov** [comment]
Unfortunately you'll have to rebase again.

**Comment by alexdowad** [comment]
> Unfortunately you'll have to rebase again.

Getting used to that by now.

I wish git was a bit smarter about merging updates to the changelog!

**Comment by alexdowad** [comment]
Rebased.

**Comment by bbatsov** [comment]
> I wish git was a bit smarter about merging updates to the changelog!

You and me both. The number I've had to type this comment is legendary... :-)

**Pull request merged**
