### PR TITLE
[Fix #4105] Fix `Lint/IndentationWidth` when `Lint/EndAlignment` is configured with `start_of_line`

### LINKED ISSUE #4105: Style/IndentationWidth might be conflicting with start_of_line Lint/EndAlignment style
I have:

```yaml
Lint/EndAlignment:
  EnforcedStyleAlignWith: "start_of_line"
```

And if I turn on Style/IndentationWidth I get weird suggestions, like this:

```ruby
def carry_attribution_data_from_previous_customer_invoice
  items = if line_items.retrospective.pre_subtotal.any?
            line_items.retrospective.pre_subtotal
  else
    line_items.bill_ahead.pre_subtotal
  end
end
```

It's obviously trying to indent two lines relative to the `if` statement, but that's not what I'd want/expect. What I'd expect is:

```ruby
def carry_attribution_data_from_previous_customer_invoice
  items = if line_items.retrospective.pre_subtotal.any?
    line_items.retrospective.pre_subtotal
  else
    line_items.bill_ahead.pre_subtotal
  end
end
```

### PR DESCRIPTION
**Pull request by brandonweiss**
Fix #4105

-----------------

Before submitting the PR make sure the following are checked:

* [ ] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Used the same coding conventions as the rest of the project.
* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [ ] All tests(`rake spec`) are passing.
* [ ] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [ ] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
I'll leave it to @jonas054 to review this.

**Comment by jonas054** [comment]
Only spec changes so far -- and failing. Is there more to come?

**Comment by brandonweiss** [comment]
Hey! Sorry, I posted a [comment](https://github.com/bbatsov/rubocop/issues/4105#issuecomment-321105022) on the issue.

> Hey! I've started a PR where I refactored the tests such that they also run Lint/EndAlignment configured with start_of_line in order to create a set of failing tests. I spent several hours today stepping through the on_if block of the cop, introspecting the various nodes and trying to figure out where the bug is, but I don't think I really got anywhere.
>
> My very rudimentary understanding seems to be that when it gets to here, the base_loc#column is wrong. But base_loc is passed through into the on_if hook (via base_node). So… maybe the problem is occurring higher up somewhere? If you could help me by taking a look yourself and/or pointing me in the right direction that would be awesome. Thanks!

**Comment by brandonweiss** [comment]
Hmm, I just looked at the PR again and noticed I removed a bunch of specs… shit, it's been a few weeks and now I don't know if that on accident or on purpose. 🤦‍♂️ I think that was an accident. I think I removed them in order to try and make the massive nesting to the block I was working on intelligible, and committed the removal accidentally. Going to add them back, sorry!

**Comment by bbatsov** [comment]
Apart from the failing build and the lack of changelog entry the changes look good to me.

**Comment by brandonweiss** [comment]
Sorry, I've been meaning to pick this back up—I've just been juggling a lot of things. I'll try to get a fix soon!

**Comment by bbatsov** [comment]
@brandonweiss Roger that! Just ping us when you get to this.

**Comment by bbatsov** [comment]
Closing for now due to lack of activity. Feel free to reopen it later.

**Comment by brandonweiss** [comment]
@bbatsov @jonas054 Hey! @satyap just fixed this! The additional commit is on my branch… I don't see it listed here… perhaps you need to re-open the PR? I apparently can't re-open it myself.

**Comment by jonas054** [comment]
@brandonweiss GitHub disallows re-opening the PR. It seems nobody can re-open until you follow the recipe outlined [here](https://github.com/isaacs/github/issues/361#issuecomment-219088644).

Alternatively, open a new PR and reference back to this one.

**Comment by brandonweiss** [comment]
@jonas054 Argh. Wow, I'm surprised I've never run into this before.

**Pull request closed without merging**
