### PR TITLE
Tomorrow is not ready to die

### PR DESCRIPTION
**Pull request by alexdowad**
For those wondering about the title: my creative powers are getting overtaxed from constantly thinking up new titles for pull requests. Therefore, my PRs will henceforth be given random titles generated by a computer program.

(Just to spice things up, I may occasionally still use a title which makes sense.)

### CODE REVIEW

**Comment by alexdowad** [comment]
I still need to add a spec or two to 0acf5a3.

**Comment by alexdowad** [comment]
Still need to add a few more tests.

**Comment by alexdowad** [comment]
`Node#range` is now `Node#source_range`. Added specs for `TargetRubyVersion` commit.

**Comment by alexdowad** [comment]
Added changelog for `WorstOffendersFormatter`.

This PR is now ready for final review.

**Comment by jonas054** [comment]
You need to preface *each* issue number with "fix" in a commit message in order to automatically close both of them. https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by alexdowad** [comment]
@jonas054 Thanks for the tip. Updated the commit message.

**Comment by jonas054** [comment]
:+1: All changes look good to me.

**Comment by bbatsov** [comment]
All the changes look good to me as well.

**Comment by bbatsov** [comment]
Btw, the TargetRubyVersion should likely be featured in the readme, as it's quite important.

**Comment by bbatsov** [comment]
And the PR has to be rebased.

**Comment by alexdowad** [comment]
`KNOWN_RUBIES` is now frozen. Added information on `TargetRubyVersion` to README.md. Rebased on the latest master.

**Comment by bbatsov** [comment]
:+1:

**Comment by alexdowad** [comment]
As usual, thanks to @bbatsov and @jonas054 for the thorough code review.

**Pull request merged**
