### PR TITLE
Modify HttpPositionalArguments to use session instead of headers

### PR DESCRIPTION
**Pull request by rrosenblum**
I have been working on upgrading a Rails project and started getting errors about `headers` not being a valid keyword argument. It looks like `session`is supposed to be used.

https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb#L460

### CODE REVIEW

**Comment by bbatsov** [comment]
Hmm, I wonder if something changed between Rails 4 and 5.

**Comment by rrosenblum** [comment]
It doesn't look like anything changed between 4 and 5 regarding headers vs session. Here is the implementation from 4.2, https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_controller/test_case.rb#L595.

```
# Example sending parameters, +nil+ session and setting a flash message:
#   
#   process :view, 'GET', { id: 7 }, nil, { notice: 'This is flash message' }
```

I'm surprised that I seem to be the first person that has run into this issue. I looked at the implementation for Rails 5.0 and 5.1 and both of those are using session as well.

**Comment by bbatsov** [comment]
Me too. That's why I asked - I assumed someone would have noticed this problem by now.

Anyways, I'll take your word for this! Thanks! 👍

**Comment by rrosenblum** [comment]
I found where `headers` likely came from `ActionDispatch` uses `headers` https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/testing/integration.rb#L210.

There is likely some other work that should be done to this cop to make it work a bit better. `xhr` aren't handled by this. Also, `format` inside of parameters needs to be converted to the `as` keyword argument. 

Even with some of the bugs, this cop is invaluable for upgrading Rails.

**Pull request merged**
