### PR TITLE
Layout department

### PR DESCRIPTION
**Pull request by jonas054**
In #3385 @bbatsov [said](https://github.com/bbatsov/rubocop/issues/3385#issuecomment-244573787):

> I think having a "Format"/"Layout" namespace is not a bad idea at all.

Be careful what you wish for, because here it is. :)

This is a suggestion that we add a new department called `Layout` where all the cops deal only with whitespace offenses. If they all support `--auto-correct` (as of now, only `EndOfLine` doesn't) we can use `rubocop --only Layout --auto-correct` as a source code formatter.

One problem is that there are a couple of whitespace cops in the `Lint` department, and without them in the `Layout` department the formatter solution is incomplete. We may have to solve that problem.

The change is divided into many commits to make reviewing easier. I'll squash later if this is deemed a good and merge-worthy idea.

### CODE REVIEW

**Comment by bbatsov** [comment]
The changes look good to me. Just squash, rebase and merge this.

**Comment by jonas054** [comment]
Thanks. Done.

**Comment by michaelckcheung** [comment]
All the documentation for these rules seem to be broken now? E.g. - http://rubocop.readthedocs.io/en/latest/cops/cops_layout.md#layoutleadingcommentspace

Is there a plan to fix those?

**Comment by pocke** [comment]
@michaelckcheung Thanks for your bug report. I fixed the problem in #4313 .
However, your URL doesn't exist. I can access this URL http://rubocop.readthedocs.io/en/latest/cops_layout/#layoutleadingcommentspace

If the wrong URL exists in the documentation, could you tell me where it is?

**Pull request merged**
