### PR TITLE
[Fix #1928] Avoid two changes overwriting in AutocorrectAlignment

### LINKED ISSUE #1928: Problem with autocorrect Style/Tab and Style/IndentationConsistency
When I run rubocop --autocorrect on my project with Style/Tab and Style/IndentationConsistency enabled I get many errors, due to rubocop splitting up words.  A boiled down example file is:
```
require 'spec_helper'
describe ArticlesController do
  render_views
    describe "GET 'index'" do
		    it "returns http success" do
    		end
		describe "admin user" do
			 before(:each) do
 			end
		end
    end
end
```
The output is as follows:
```
require 'spec_helper'
describe ArticlesController do
  render_views
  describe "GET 'index'" do
          it "returns http success" do
          end
          describe "admin user" d    o
           before(:each) d    o
           en    d
      end
  end
end
```
Note the split `do` after the `before(:each)`.  It not only splits up keywords, but symbols, literals, i.e. it seems to do it pretty much everywhere.

### PR DESCRIPTION
**Pull request by jonas054**
Just report the inner offense and correct the outer. The next auto-correct iteration will fix the inner offense.

### CODE REVIEW

**Comment by bbatsov** [comment]
You'll have to rebase this.

**Comment by jonas054** [comment]
Rebased.

**Comment by bbatsov** [comment]
Unfortunately you have to rebase again.

**Comment by jonas054** [comment]
No sweat. Rerebased.

**Pull request merged**
