### PR TITLE
[Fix #2001] New cop Style/FirstIndentation

### LINKED ISSUE #2001: Entire file is indented, but RuboCop doesn't complain
```rb
  # encoding: utf-8
  class A
  end
```
RuboCop doesn't discover that all lines should be unindented by 2 spaces.

### PR DESCRIPTION
**Pull request by jonas054**
A new cop seems like the best solution. To avoid different cops stepping on each other's toes.

Found a couple of unrelated problems that I marked with `TODO` comments. Will open issues for them.

### CODE REVIEW

**Comment by bbatsov** [comment]
The code looks good, but we can do better with the name (I think). Maybe `Initial/Base/Starting/TopLevel` instead of `First`?

**Comment by jonas054** [comment]
I like `Initial`. Changed.

**Comment by bbatsov** [comment]
The build is failing now. Guess you forgot to rename something.

**Comment by jonas054** [comment]
Yes, kind of. Should be fixed now. Fingers crossed.

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
