### PR TITLE
Fix Style/Documentation false-positive offence #1905.

### LINKED ISSUE #1905: False-positive Style/Documentation offence on trailing comments
```shell
% rubocop -V
0.31.0 (using Parser 2.2.2.3, running on ruby 2.2.1 x86_64-linux)
```

### tl;dr

[This](https://gist.github.com/RGBD/0fc6e0377fdefbbf721b#file-minimal-rb) file:

```shell
% cat minimal.rb
module M
  # top level class documentation
  class C
	def foo; end
  end # class ending comment, the troublemaker
end
```

Produces this:

```shell
% rubocop minimal.rb
Inspecting 1 file
C

Offenses:

minimal.rb:3:3: C: Missing top-level class documentation comment.
  class C
  ^^^^^

1 file inspected, 1 offense detected
```

### Problem domain

I've seen people use end block comment do denote which class it ends. The style
guide indirectly discourages need of such comments [here](https://github.com/bbatsov/ruby-style-guide#file-classes), and maybe it
even deserves a separate cop. But because of this issue the user is provided
with irrelevant problem description and location.

### Why this happens?

There is a little ambiguity on how trailing comments should be treated by [parser](https://github.com/whitequark/parser/). In
particular, Parser::Source::Comment associates comments after the last child of
a node with this last child. So, when Rubocop::Cop::Style::Documentation parses
last class enclosed in module, it gives unexpected results, see [gist](https://gist.github.com/RGBD/0fc6e0377fdefbbf721b#file-default-log).

### Possible fix

Cop could check for associated comments only before class/module definition.
See my PR (#1906).

### The reason lies deeper

I think, the behaviour of parser comment association should be changed to be
more intuitive in this case. I've found example for false-positive match.
See this [gist](https://gist.github.com/RGBD/0fc6e0377fdefbbf721b#file-default-log).

### Summary

If my approach seems good to you, I'll add rspec examples so we can merge. I
hope @whitequark will join this conversation, because there are even more edge
cases, that should be fixed in parser itself, not in rubocop.

### PR DESCRIPTION
**Pull request by RGBD**
Fixes #1905.

### CODE REVIEW

**Comment by rrosenblum** [comment]
Is there a test that can exercise the changed code?

**Comment by bbatsov** [comment]
Overall the changes look good. Update the changelog, fix the typos, squash the commits, refer to the issue in the commit message and capitalise the commit message.

**Comment by bbatsov** [comment]
Looks good, but unfortunately you'll have to rebase on top of the current `master`.

**Comment by bbatsov** [comment]
@RGBD You'll have to rebase again. Notify me when you do so, you I can merge this right away and spare you from doing extra rebasing.

**Comment by RGBD** [comment]
@bbatsov, done!

**Comment by bbatsov** [comment]
That was fast! Thanks!

**Pull request merged**
