### PR TITLE
The deepest locksmithing

### PR DESCRIPTION
**Pull request by alexdowad**
Another batched PR. Tweaks, fixes, tweaks, fixes.

### CODE REVIEW

**Comment by alexdowad** [comment]
Added changelog entries, just seeing if build still passes.

**Comment by bbatsov** [comment]
Apart from the failing build and my small remarks - the PR looks good to me.

**Comment by alexdowad** [comment]
@bbatsov Corrected misspelling in commit message. `relevant_options_hash` is `relevant_options_digest` now. Fixed build.

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
