### PR TITLE
Bugs galore

### PR DESCRIPTION
**Pull request by alexdowad**
I have been working on making RC faster, but am stuck waiting for @whitequark to release a new version of `parser`. In the meantime, I'll clear all these bug reports which are multiplying like weeds.

(We really need something to make future releases more solid; I think the stress test suite which I have half-done will fit the bill. But that will be after the outstanding performance work is cleared.)

### CODE REVIEW

**Comment by bbatsov** [comment]
You forgot to add changelog entries.

**Comment by alexdowad** [comment]
Have to write specs for the last fix.

**Comment by bbatsov** [comment]
I still don't see changelog entries accompanying the bugfix commits.

**Comment by alexdowad** [comment]
> I still don't see changelog entries accompanying the bugfix commits.

That's because I haven't added any. Still need a couple more tests too. Will post here when I'm ready for final review. (No more commits will be added in this PR.)

**Comment by bbatsov** [comment]
Ah, OK.

**Comment by alexdowad** [comment]
Added a couple more specs, plus changelog. Ready for final review.

**Comment by bbatsov** [comment]
Apart from my small remark, the code looks good.

**Comment by alexdowad** [comment]
Removed commit re: Active Support's `delegate`. Added a couple more specs. Updated `GuardClause` code as suggested by @bbatsov. Rebased.

**Comment by alexdowad** [comment]
`SpaceAroundKeywords` now checks `zsuper` and `defined?` nodes as suggested by @bbatsov.

**Pull request merged**
