### PR TITLE
Fix erroring when frozen strings are enabled

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by alexdowad** [comment]
Looks good! But it needs at least one test to confirm the fix, and make sure there will be no regressions. If the one who reported the error posted their code in the GH issue, you can use it as a test case.

Also put "[Fix #....]" in the commit log title. This will make GH automatically close the issue when your commit is merged.

Thank you for the great work!

**Comment by alexdowad** [comment]
Also, style offenses to fix:

```
lib/rubocop/cop/mixin/frozen_string_literal_comment.rb:6:5: C: Missing top-level module documentation comment.
    module FrozenStringLiteral
    ^^^^^^
lib/rubocop/cop/mixin/frozen_string_literal_comment.rb:13:81: C: Line is too long. [98/80]
      def frozen_string_literal_comment_exists?(processed_source, comment = FROZEN_STRING_LITERAL)
                                                                                ^^^^^^^^^^^^^^^^^^
lib/rubocop/cop/mixin/frozen_string_literal_comment.rb:25:81: C: Line is too long. [124/80]
        target_ruby_version >= 2.3 && frozen_string_literal_comment_exists?(processed_source, FROZEN_STRING_LITERAL_ENABLED)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/rubocop/cop/style/mutable_constant.rb:25:81: C: Line is too long. [130/80]
          return if value && FROZEN_STRING_LITERAL_TYPES.include?(value.type) && frozen_string_literals_enabled?(processed_source)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by segiddins** [comment]
@alexdowad done

**Comment by alexdowad** [comment]
:+1:

**Comment by alexdowad** [comment]
You just need a comment on `module FrozenStringLiteral` to make the build pass.

**Comment by segiddins** [comment]
Silly me, done. Sorry, have been a bit frazzled this week

**Comment by bbatsov** [comment]
The code looks good, but it's lacking a changelog entry.

**Pull request merged**
