### PR TITLE
[Fix #3288] Fix auto-correction bug for %w()/%i() in ParallelAssignment

### LINKED ISSUE #3288: Autocorrection of multiple assignment makes ints from stirings
--------

## Expected behavior
```
  a, b = %w(1 2)
```      

becomes
```
 a= '1'
 b='2'
```   

## Actual behavior
```
  a, b = %w(1 2)
```      
becomes
```
 a= 1
 b=2
```      

## Steps to reproduce the problem

This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

## RuboCop version

Include the output of `rubocop -V`:

```
16:13 % rubocop -V                                                                                                                                       2016-07-05 16:13:54
0.41.1 (using Parser 2.3.1.2, running on ruby 2.3.1 x86_64-linux)

```

### PR DESCRIPTION
**Pull request by jonas054**
Add special handling of string and symbol nodes that don't have delimiters.

### CODE REVIEW

**Comment by Drenmi** [comment]
Should we extend this to also work for symbol arrays? Currently:

```
a, b, c = %i(a b c)
```

is corrected into:

```
a = a
b = b
c = c
```

but should be:

```
a = :a
b = :b
c = :c
```

**Comment by bbatsov** [comment]
I guess we should.

**Comment by jonas054** [comment]
Thanks @Drenmi, I'll update the code to handle symbol arrays.

**Comment by jonas054** [comment]
Updated.

**Comment by bbatsov** [comment]
👍

**Pull request merged**
