### PR TITLE
[Fix #5589] Remove Performance/HashEachMethods

### LINKED ISSUE #5589: Performance/HashEachMethods does not provide a net performance benefit
## Background

The Performance/HashEachMethods cop was introduced in af84fb2b4, in PR https://github.com/bbatsov/rubocop/pull/2578.

Since its introduction, there have been a large number of issues raised related to false positives (https://github.com/bbatsov/rubocop/issues/5328, https://github.com/bbatsov/rubocop/issues/5028, https://github.com/bbatsov/rubocop/issues/4931, https://github.com/bbatsov/rubocop/pull/4883, https://github.com/bbatsov/rubocop/issues/4881, https://github.com/bbatsov/rubocop/issues/4872, https://github.com/bbatsov/rubocop/issues/4777, https://github.com/bbatsov/rubocop/issues/4774, https://github.com/bbatsov/rubocop/pull/4754, https://github.com/bbatsov/rubocop/issues/4732).

While some of these have been addressed, the fundamental problem that the cop can't know what type of object is receiving the `#each` message means that most of these false positives will never be eliminated. The cop will match any invocation of `#each` yielding two arguments of which one is ignored: for example, iterating over an array of pairs.

As a workaround, the cop suggests wrapping destructuring block arguments in parens:

```ruby
# violates the cop
[[1, 2], [3, 4]].each do |k, _|
  p k
end

# does not violate the cop
[[1, 2], [3, 4]].each do |(k, _)|
  p k
end
```

However, measurement suggests the cop's suggested changes do not reliably result in performance improvements, and that the suggested workaround for its false positives usually *does* have a negative performance impact.

## Expected behavior

The `Performance/HashEachMethods` cop's suggested changes should improve code performance.

## Actual behavior

The cop's suggested changes do not significantly improve performance in recent rubies, and the suggested workaround for its false positives significantly harms performance.

## Steps to reproduce the problem

I [ran a benchmark](https://gist.github.com/urbanautomaton/7051549d5873964a878d5af3b8a7da1c) comparing `Hash#each` with `Hash#each_key` and `Hash#each_value`, and another comparing `Array#each` on an array of pairs, using implicit and explicit destructuring args.

The full benchmark code and results can be seen [here](https://gist.github.com/urbanautomaton/7051549d5873964a878d5af3b8a7da1c), and are summarised below (for simplicity's sake I've looked only at key-only access, but the results for value-only are broadly similar).

Hash comparison (`Hash#each` = 1.0, larger number implies faster, measurements with the margin of error in _italics_):

| Ruby: | 2.2 | 2.3 | 2.4 | 2.5 |
| --- | --- | --- | --- | --- |
| `Hash#each` | 1.0 | 1.0 | 1.0 | 1.0 |
| `Hash#each_key` | 1.16 | 1.15 | _1.02_ | _0.99_ |

Array comparison (`|k, _|` = 1.0, larger number implies faster, measurements within the margin of error in _italics_):

| Ruby: | 2.2 | 2.3 | 2.4 | 2.5 |
| --- | --- | --- | --- | --- |
| `Array#each` with `k, _` | 1.0 | 1.0 | 1.0 | 1.0 |
| `Array#each` with `(k, _)` | _0.95_ | 0.87 | 0.89 | 0.90 |

The small performance benefit to `Hash#each_key` that used to exist appears to have been eliminated in recent rubies, while a performance hit of similar magnitude remains when using parens for destructuring `Array#each` block arguments.

## Conclusion

I think we should remove this cop, as:

* it no longer provides performance benefits in recent ruby versions,
* it does cost non-trivial end user time working around false positives, and
* it suggests a workaround for its false positives that is harmful to performance.

I'd be happy to write a PR for this if it's agreed we should do so.

## RuboCop version

```
$ rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.4.3 x86_64-darwin17)
```

### PR DESCRIPTION
**Pull request by urbanautomaton**
As discussed in #5589, `Performance/HashEachMethods` cop's suggested changes no longer confer performance benefits in modern rubies, and the suggested workaround for one of its common false positives has negative performance effects.

As a result there seemed to be agreement that it should be removed, so that's what this PR does.

I've removed the code, added it to the `OBSOLETE_COPS` hash and removed any further references to it I could find - is that all that needs doing?

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests. (N/A)
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
I'm OK with dropping the cop, but I wonder if we shouldn't just make it a style cop instead. Some people might appreciate a consistent approach to those, although this types of cops are inherently flawed and produce false positives.

**Comment by urbanautomaton** [comment]
My personal preference would be to drop it on account of the false positives. The number of old issues relating to these for this cop suggests these cases aren't that rare, so it feels like the cop wouldn't be adding net value as a style cop.

**Comment by bbatsov** [comment]
@pocke @koic @Drenmi @jonas054 @garettarrowood Any thoughts on this?

**Comment by pocke** [comment]
Firstly, I 100% agree with removing the cop from Performance department.


> I'm OK with dropping the cop, but I wonder if we shouldn't just make it a style cop instead. Some people might appreciate a consistent approach to those, although this types of cops are inherently flawed and produce false positives.


> My personal preference would be to drop it on account of the false positives. The number of old issues relating to these for this cop suggests these cases aren't that rare, so it feels like the cop wouldn't be adding net value as a style cop.


I think we can make it a style cop and disable it by default. If someone needs the cop and can ignore the false positives with some tool, the cop can be enabled with a configuration.

But I guess the use case is rare. And maintenance cost for a disabled cop is larger than enabled cop. Because if it is disabled by default, we cannot notice bugs of the cop.
So, I would tend to agree completely removing the cop, but if many users want to use the cop as a style cop, I think we should make it a style cop.

**Comment by garettarrowood** [comment]
I guess my vote would be to remove it entirely. 

Because even if we make it a Style cop and disable by default, we have a buggy cop to continue to upkeep. Since this cop has proven to be a pretty problematic, I rather not keep a somewhat broken tool. Contributor energy is better spent on cops/issues that deliver more value.

**Comment by bbatsov** [comment]
Fine by me. I guess in general we should do two more things:

* consider for removal other problematic cops, that are currently probably disabled by default
* come up with some guidelines about the reliability of a cop, so we would consider it for inclusion upstream

@urbanautomaton Thanks for tackling this!

**Comment by urbanautomaton** [comment]
> I guess in general we should do two more things:
>
> * consider for removal other problematic cops, that are currently probably disabled by default
> * come up with some guidelines about the reliability of a cop, so we would consider it for inclusion upstream

@bbatsov I think this would be fantastic. Having a rubric for introducing new cops would be a big help in maintaining quality. The cop generator does a good job of providing a generic template, but a checklist of things to discuss in PRs introducing new cops would be a great benefit for review, I think. This PR doesn't seem like the ideal place to make suggestions but I can't find a mailing list - would opening an issue to discuss guideline contents be helpful?

**Pull request merged**
