### PR TITLE
[Fix #1586] StructInheritance cop failing with `< DelegateClass(Something)`

### LINKED ISSUE #1586: Style/StructInheritance crashes during rubocop's self inspection
See [Travis log](https://travis-ci.org/bbatsov/rubocop/jobs/47688512).

@mmozuras, could you take a look?

### PR DESCRIPTION
**Pull request by mmozuras**
https://github.com/bbatsov/rubocop/issues/1586

### CODE REVIEW

**Comment by bbatsov** [comment]
Please, prefix the commit message with `[Fix #1586] `.

**Comment by mmozuras** [comment]
@bbatsov done.

**Comment by Koronen** [comment]
Maybe add a [changelog entry](https://github.com/bbatsov/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format)?

**Comment by jonas054** [comment]
@Koronen That's not necessary since this is a fix for un unreleased feature.

**Comment by bbatsov** [comment]
:+1:

**Comment by Koronen** [comment]
@jonas054 Ah, disregard my comment then.

**Pull request merged**
