### PR TITLE
WIP Parallel Rubocop

### PR DESCRIPTION
**Pull request by josh**
An attempt to resurrect #175 and #117. I'm not sure why exactly they were closed.

Timings on rubocop's own codebase.

**master**

```
$ time bin/rubocop --cache false
Inspecting 825 files

825 files inspected, no offenses detected

real	0m31.175s
user	0m30.929s
sys	0m0.199s
```

**parallel**

```
$ time bin/rubocop --cache false
Inspecting 825 files

825 files inspected, no offenses detected

real	0m7.727s
user	0m54.805s
sys	0m0.629s
```

The difference is huge when running on a large codebase. For an example, @github has 10,000+ Ruby files. It takes about 4 minutes in serial and 55s in parallel on a cold cache. Even with a warm cache, parallelism still helps. 10s serial vs 2s parallel on @github's codebase.

**Problems**

Theres a number of problems with this as is:

* Something is up with offense correction. Thats why the tests are failing. But it does seem to be working when running standalone from CLI. Still trying to figure that out.
* I'm not sure what other memory side effects there are when checking for offenses. These object mutations would happen in a worker fork and wouldn't be propagated back up to the main process.
* Read/write to cache probably needs to flock or be coordinated by the main process.

-----------------

Before submitting the PR make sure the following are checked:

* [ ] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Used the same coding conventions as the rest of the project.
* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [ ] All tests are passing.
* [ ] The new code doesn't generate RuboCop offenses.
* [ ] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [ ] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

-----------------

CC: @aroben

### CODE REVIEW

**Comment by bbatsov** [comment]
> An attempt to resurrect #175 and #117. I'm not sure why exactly they were closed.

I recall that the main problem with the old efforts was that the people working on the changes couldn't get reporting to work right (and I think this worked super slow on JRuby). I think we also have some cops that depend on the order other cops are executed and a few cops that work on all processed files that were added afterwards - I'll have to double check this. So, in brief - the PRs were closed because they never got to a working state and aimed for simpler solution that would preserve the single thread/process nature of RuboCop - notably a single pass of the AST tree for all cops and the cache.

**Comment by bbatsov** [comment]
I guess #175 had most of this discussion. In the end the PR was closed simply because it wasn't moving anywhere.

**Comment by rrosenblum** [comment]
I really like the idea of this. I thought about trying to implement something like this around the time that caching was introduced. 

> I recall that the main problem with the old efforts was that the people working on the changes couldn't get reporting to work right

Take a look at how Minitest solves this issue. Their reporter implements a `synchronize` method that makes use of a `Mutex` to ensure that only 1 reporting operation can happen at a time.

**Comment by josh** [comment]
Well, I think I answered my own question about why this PR originally was abandon. I don't have time myself to keep investigating it. If someone else wants to take it over, please do!!!

**Comment by bbatsov** [comment]
I told you - this feature is cursed. :D

**Comment by jonas054** [comment]
For anyone interested, here's a wrapper script I use to speed up RuboCop execution, especially running `./bin/rubocop` on RuboCop's own source.

```ruby
#!/usr/bin/env ruby
#
# Usage: warmup <rubocop command...> [-- <rubocop args...>]
#
# Examples:
#   warmup rubocop
#   warmup bundle exec rubocop -- -F

require 'facter'

index = ARGV.index('--')
if index
  binary = ARGV[0...index]
  command = (binary + ARGV[(index + 1)..-1]).join(' ')
else
  binary = ARGV
  command = binary.join(' ')
end
binary = binary.join(' ')

CPU_COUNT = Facter.value('processors')['count']
FILES =
  `#{binary} -L`.split($RS).each_with_index.group_by { |_, i| i % CPU_COUNT }

puts "Running `#{command}` on #{CPU_COUNT} CPUs..."
CPU_COUNT.times do |cpu|
  fork { `#{command} #{FILES[cpu].map(&:first).join(' ')}` }
end

Process.waitall
puts 'Done'

system command
```
The idea is to use `rubocop -L` to get a list of files to inspect, then divide the list in equal parts and fork processes to share the work. No output is collected from these runs. The last stage is running `rubocop` again an all files, taking advantage of the results from the previous runs being cached. The gem `facter` is needed to figure out how many CPUs (cores) are available. 

I typically get the excution time down to a third of the original when running on 8 cores.

**Pull request closed without merging**
