### PR TITLE
Only report violations on changed lines (requires git)

### PR DESCRIPTION
**Pull request by melch**
Add option to only check changed lines.
- Assumes using git for source control.
  Could extend diff parser library for other versions of source control.
- Parses git diff to see what lines changed and skips any violations
  that are reported on lines that didn't change.
- When listing which files to check, also skips any files that
  weren't changed as a performance measure.

- LineupFinder parses a git diff to return what files were changed
  and what lines were changed in a changed file.
- Cop is extended if option is turned on to check for changes when
  deciding to add an offense to the rap sheet.
- Target finder is also extended if option is on to only report
  changed files to save time on large code bases.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by mikegee** [comment]
Could you please fill in the PR description to describe this work?

Please also justify this being part of Rubocop instead of depending on [an external tool to only run Rubocop on the changes](https://github.com/mmozuras/pronto).

**Comment by bbatsov** [comment]
I really dislike the idea of adding some VC-related functionality to RuboCop. As @mikegee - there are other ways to achieve the same result.

**Comment by melch** [comment]
The ways that I found and thought of to control the offense reports per lines in a file seem brittle, but I see your point about version control in rubocop. How do y'all feel about a better way to pass in what files and lines should be checked and reported on, preferably per run and not through `rubocop.yml`?

**Comment by melch** [comment]
And as a separate discussion, would y'all be interested in just this commit, which separates out this offense message logic from the cop class? e4cb787e5428f73b0a2be89380f7e6aa421f5f35

If so, I can create a new PR for it.

**Comment by mikegee** [comment]
> How do y'all feel about a better way to pass in what files and lines should be checked and reported on, preferably per run and not through rubocop.yml?

Better than this PR or better than Pronto?

**Comment by melch** [comment]
> > How do y'all feel about a better way to pass in what files and lines should be checked and reported on, preferably per run and not through rubocop.yml?

> Better than this PR or better than Pronto?

Better than both? As far as I can tell, Pronto will show offenses on changed lines, but it doesn't appear to autocorrect for changed lines only. It'd be nice to build in a way to choose which offenses to both display and autocorrect per line in a file. I can think of a couple of ways to do so:

1. The RuboCop CLI allows files to be passed in, which are then used both for analyzing offenses and correcting them. It would be convenient to also pass in an array of lines. This array could be used in `add_offense`, which would control which offenses are reported and autocorrected.
```
  rubocop app spec lib/something.rb lib/specific_lines.rb[1, 2, 3, 4, 5, 34, 42, 43, 45]
```

2. Show which lines offenses correlate to and have a way to run autocorrect only on specific offenses be auto-corrected.

Supporting Option 1 would allow tools such as Pronto to be extended to support autocorrect. Pronto would also no longer have to monkey patch existing RuboCop classes. I think people would find such an additional interface useful if needed and easy to ignore if not.

**Comment by melch** [comment]
Closing in favor of a different branch without git dependency.

**Pull request closed without merging**
