### PR TITLE
[Fix #2451] Don't treat method calls named 'lambda' as lambdas

### LINKED ISSUE #2451: undefined method `children' for :do_find:Symbol
rubocop 0.35.1 errors when parsing this file: https://github.com/theforeman/smart-proxy/blob/develop/modules/puppet_proxy/class_scanner_eparser.rb

Specifically this bit:
``` ruby
def find_CallNamedFunctionExpression o
  if o.lambda
    do_find(o.lambda)
  end
end
```
It looks like "o.lambda" is getting misinterpreted as a lambda.

Full traceback: https://gist.github.com/brandonweeks/e3684b4b882b2b378793
Test case (credit @domcleal): https://gist.github.com/domcleal/e792c526eed7275f6b4b
>0.35.1 (using Parser 2.2.3.0, running on ruby 2.2.3 x86_64-darwin14)

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by bbatsov** [comment]
That's one odd failure. Btw, you should also update the changelog.

**Comment by domcleal** [comment]
Oops, thanks for the reminder.  I've updated the PR with the CHANGELOG.md entry.

I'll see if the JRuby test fails this time too.

**Comment by domcleal** [comment]
> I'll see if the JRuby test fails this time too.

Looks like it may be an intermittent error, it's gone away on a re-test.

**Comment by bbatsov** [comment]
:+1: Thanks!

**Pull request merged**
