### PR TITLE
Reduce `Metrics/CyclomaticComplexity` Max to 7

### PR DESCRIPTION
**Pull request by Drenmi**
Today is a public holiday, and so I had time on my hands to do some clean up.

Through a lot of method extractions and the introduction of some inner classes, this change reduces cyclomatic complexity to 7, and takes a chunk out of perceived complexity and others.

### CODE REVIEW

**Comment by lumeet** [comment]
Nice, @Drenmi! In case you're planning to continue with similar PRs, I guess it's good to have some coordination. In other words, I'm on `MethodLength` -> 15. :)

**Comment by Drenmi** [comment]
@lumeet: I will most probably work on bugfixes and features after this. I'll ask you if I plan to get back to housekeeping. 😀

**Comment by bbatsov** [comment]
Impressive work!

**Comment by Drenmi** [comment]
I have to give most of the credit to RuboCop. Having the TODO-file is a huge motivator to clean things up, as you can just lower the number one "click" at a time. 😀

**Pull request merged**
