### PR TITLE
Remove an outdated comment

### PR DESCRIPTION
**Pull request by DNNX**
The problem described by the comment was fixed
in https://github.com/bbatsov/rubocop/pull/2555/files#diff-136dc9359b5a71d3b9242666420aefc5L1441 .

### CODE REVIEW

**Comment by alexdowad** [comment]
Nice catch, thank you!

**Comment by bbatsov** [comment]
Just a small remark about the commit message - "Removing" should be "Remove".

**Comment by DNNX** [comment]
@bbatsov fixed it

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
