### PR TITLE
Fix broken `--fail-fast`

### PR DESCRIPTION
**Pull request by mmyoji**
`rubocop --fail-fast` was broken at 43a157f1a674da16b45a13f69e242565382f7ac5

I fixed this and add minimum test for it.

### CODE REVIEW

**Comment by koic** [comment]
Thanks for the first time contribution.

It seems that CI has failure.
https://travis-ci.org/bbatsov/rubocop/jobs/350648219#L4210

That will be resolved by adding your account at the end of CHANGELOG.md.
Refer https://github.com/bbatsov/rubocop/commit/8ec6cf6dcf70b2cb796ab26d9193c3a4eb9c3eaf#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR3232

When you are finished, please squash multiple commits in PR into 1 commit.

**Comment by mmyoji** [comment]
@koic I fixed the CHANGELOG.md and rebased the commits into a single one :+1: Thank you for your help :raised_hands:

**Comment by bbatsov** [comment]
👍

**Comment by issei-m** [comment]
👍

**Comment by iliabylich** [comment]
Are there any plans to release it?

**Pull request merged**
