### PR TITLE
Turn up the heat

### PR DESCRIPTION
**Pull request by alexdowad**
The new `parser` has a much improved `Source::Rewriter` which makes it much more practical to apply autocorrections from all cops at once, rather than only one cop per iteration of the inspection loop. Previously, it would hideously mangle your code if you tried this.

This vastly decreases the number of iterations required until there are no corrections left to perform.

With this patch, I can autocorrect Rails' `actionpack` in 10 minutes. (19804 offenses detected, 15735 offenses corrected... :sweat:) Not impressed? Last time I tried, it took about 2 hours.

I'm still too scared to try autocorrecting all of Rails... :fearful:

### CODE REVIEW

**Comment by alexdowad** [comment]
One thing: I fully expect there may be some breakage here. But there is no other way that autocorrection will ever be fast.

**Comment by alexdowad** [comment]
Build should be fixed now...

**Comment by alexdowad** [comment]
By the way, this has another advantage: previously, autocorrecting would generate a lot of duplicate offenses for what was actually the same problem. Those duplicates are not eliminated here, but *greatly* reduced.

**Comment by bbatsov** [comment]
:+1:

**Comment by alexdowad** [comment]
Sigh. I had hoped that this optimization would bring autocorrection time right down to where my stress tests could run nice and fast. I still need to find another 3x speedup or so.

**Pull request merged**
