### PR TITLE
Numerous config/* organization improvements

### PR DESCRIPTION
**Pull request by tscheffe**
Numerous `config/default.yml` and `config/enabled.yml` organization improvements:
- Re-alphabetize many different cop configs
- Add a few more backtick escapes to some keywords and classes
- Improve a recently added `Description`
- Added a `Security` "header" and fixed up all the other headers to be uniform length

I considered squashing a few of the commits together but it's much easier to review and ensure that nothing was messed up with the reorganizing if you go commit by commit. I'm willing to squash down to four commits (based on the listed changes above) after PR is approved, or feel free to merge as is.

As there were no "functional" changes I elected not to add a line to `CHANGELOG` but as there are a fair number of lines being changed I could totally see the need for one if suggested.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by bbatsov** [comment]
Great work! 👍

**Comment by tscheffe** [comment]
Whoooo

You're doing a great job at encouraging my burgeoning desire to contribute more and more! Thanks a bunch!

**Comment by bbatsov** [comment]
I'm looking forward to your future contributions! ;-)

**Comment by bbatsov** [comment]
P.S. If you'd like to work on more documentation improvements, here's a great ticket that needs some work - https://github.com/bbatsov/rubocop/issues/3808

**Pull request merged**
