### PR TITLE
Check for zero retval of casecmp

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by bbatsov** [comment]
@segiddins Did you those benchmarks @alexdowad asked about? I think we should do the changes you've proposed, but still it's good to know the impact.

**Comment by segiddins** [comment]
What benchmarks?

**Comment by alexdowad** [comment]
@segiddens See [my comment](https://github.com/bbatsov/rubocop/issues/2614#issuecomment-170316398).

**Comment by segiddins** [comment]
```ruby
#!/usr/bin/env ruby

require 'benchmark'

x = 'sTrInG'

Benchmark.bm do |bm|
	bm.report("==    ") { 1_000_000.times { x.casecmp("string") == 0 } }
	bm.report(".zero?") { 1_000_000.times { x.casecmp("string").zero? } }
end
```

```
       user     system      total        real
==      0.200000   0.010000   0.210000 (  0.202799)
.zero?  0.200000   0.000000   0.200000 (  0.201177)
```

**Comment by alexdowad** [comment]
Thanks @segiddins. This is more what we were interested in:

```sh
5:57 ~prog/Ruby/rubocop % cat bench.rb                      [the_sky_loves_a_good_joke]
#!/usr/bin/env ruby

require 'benchmark'

x = 'sTrInG'

Benchmark.bm do |bm|
    bm.report("==      ") { 1_000_000.times { x.casecmp("string") == 0 } }
    bm.report(".zero?  ") { 1_000_000.times { x.casecmp("string").zero? } }
    bm.report("downcase") { 1_000_000.times { x.downcase == "string" } }
end
5:57 ~prog/Ruby/rubocop % ruby bench.rb                     [the_sky_loves_a_good_joke]
       user     system      total        real
==        0.170000   0.000000   0.170000 (  0.166126)
.zero?    0.170000   0.000000   0.170000 (  0.171633)
downcase  0.210000   0.000000   0.210000 (  0.216743)
```

**Comment by alexdowad** [comment]
It looks like there is still some (minor) performance benefit of using `casecmp("string").zero?` as opposed to downcasing/upcasing the string. So should we keep this `Casecmp` cop? Or do we dump it?

**Comment by bbatsov** [comment]
Let's keep this for now. Because of the release of 0.36.0, this now needs a changelog entry.

**Comment by deivid-rodriguez** [comment]
So is this cop going to be kept as a default? Do you find the `casecmp` style as readable as the `downcase` one?

**Comment by alexdowad** [comment]
> Do you find the casecmp style as readable as the downcase one?

It's not as readable, unfortunately. I think that it should be disabled by default.

**Comment by bbatsov** [comment]
Agreed. Ruby really needs a similar method that returns a boolean value...

**Comment by segiddins** [comment]
CHANGELOG'd

**Comment by bbatsov** [comment]
The entry name is not correct, therefore the failing test.

**Pull request merged**
