### PR TITLE
[Fix #1278] Add auto-correct for EndKeywordAlignment

### LINKED ISSUE #1278: Add autocorrect for Lint/DefEndAlignment cop
References https://github.com/bbatsov/rubocop/issues/743.

### PR DESCRIPTION
**Pull request by lumeet**
`Lint/EndAlignment` and `Lint/DefEndAlignment` do auto-correction.

### CODE REVIEW

**Comment by jonas054** [comment]
The end alignment cops are in the `Lint` category because the bad indentation could be something more serious than just a style issue. It could be a mistake in which keyword you think you're matching with the `end`. (`ruby -w` warns for these too, by the way.) So for this reason I don't think we can add auto-correct for these cops.

Maybe if auto-correct could be disabled by default in configuration.

**Comment by bbatsov** [comment]
> Maybe if auto-correct could be disabled by default in configuration.

Sounds good to me.

**Comment by jonas054** [comment]
We already have support for an `AutoCorrect` config parameter. I had forgotten about this. It has a couple of problems that I've just described in #1834.

Anyway, you can add
```yaml
Lint/EndAlignment:
  AutoCorrect: "False"

Lint/DefEndAlignment:
  AutoCorrect: "False"
```
in `config/default.yml`, @lumeet.

**Comment by jonas054** [comment]
@lumeet #1835 has been merged, so now it should be:
```yaml
Lint/EndAlignment:
  AutoCorrect: false

Lint/DefEndAlignment:
  AutoCorrect: false
```

**Comment by bbatsov** [comment]
You'll have to rebase this.

**Comment by lumeet** [comment]
Done.

**Pull request merged**
