### PR TITLE
Style::MultilineLiteralBraceLayout fixed: ignore single-line nodes

### PR DESCRIPTION
**Pull request by faucct**
The style has had a behavior conflicting with its name.

### CODE REVIEW

**Comment by bbatsov** [comment]
> The style has had a behavior conflicting with its name.

More details, please. :-)

**Comment by faucct** [comment]
It was not ignoring single-line literals as it should have been doing, cause this spec is only for multi-line literals, according to its name.

**Comment by jonas054** [comment]
Looks good, but you need to add a changelog entry.

**Comment by faucct** [comment]
fixed here - https://github.com/alexdowad/rubocop/commit/7ec472baa852edc83b77454a577ae35bdbf4623c

**Pull request closed without merging**
