### PR TITLE
Add Rails/ReversibleMigration cop

### PR DESCRIPTION
**Pull request by sue445**
This cop checks whether the `#change` method of the migration file is reversible.

## Example
```ruby
# bad
def change
  change_table :users do |t|
    t.column :name, :string
  end
end

# good
def change
  create_table :users do |t|
    t.string :name
  end
end

# good
def change
  reversible do |dir|
    change_table :users do |t|
      dir.up do
        t.column :name, :string
      end

      dir.down do
        t.remove :name
      end
    end
  end
end
```

### drop_table
```ruby
# bad
def change
  drop_table :users
end

# good
def change
  drop_table :users do |t|
    t.string :name
  end
end
```

### change_column_default
```ruby
# bad
def change
  change_column_default(:suppliers, :qualification, 'new')
end

# good
def change
  change_column_default(:posts, :state, from: nil, to: "draft")
end
```

### remove_column
```ruby
# bad
def change
  remove_column(:suppliers, :qualification)
end

# good
def change
  remove_column(:suppliers, :qualification, :string)
end
```

### remove_foreign_key
```ruby
# bad
def change
  remove_foreign_key :accounts, column: :owner_id
end

# good
def change
  remove_foreign_key :accounts, :branches
end
```

## Note
reversible migration commands are below.
http://api.rubyonrails.org/classes/ActiveRecord/Migration/CommandRecorder.html

 
-----------------

Before submitting the PR make sure the following are checked:

* [ ] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by bbatsov** [comment]
That's one really handy cop! I'll review the code a bit later. It'd be nice if you wrote a matching rule for the Rails Style Guide.

**Comment by bbatsov** [comment]
Seems you forgot to update the documentation.

**Comment by sue445** [comment]
@bbatsov I updated doc and CI is all green 💚 

>  It'd be nice if you wrote a matching rule for the Rails Style Guide.

I see, I'll write a style guide later.  I temporarily make this PR to WIP

**Comment by sue445** [comment]
@bbatsov I wrote style guide at https://github.com/bbatsov/rails-style-guide/pull/211 , and removed WIP. Please check these 🙇

**Comment by sue445** [comment]
🎉

**Pull request merged**
