### PR TITLE
Add missing DynamicFindBy to the Rails cop list

### PR DESCRIPTION
**Pull request by astorije**
This is a documentation change only (in the manuals).

This cop can be found at http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/DynamicFindBy.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* **(N/A)** Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* **(N/A)** Added tests.
* **(N/A)** Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* **(N/A)** Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by bbatsov** [comment]
This list is generated automatically, so I'm guess something's wrong with the cop's config or something if our rake task didn't pick it up.

**Comment by astorije** [comment]
@bbatsov, damn, didn't know that. Do you want me to investigate on the reason why?

**Comment by bbatsov** [comment]
@sihu can you look into this?

**Comment by sihu** [comment]
@bbatsov yes i will 👍

**Comment by sihu** [comment]
@astorije very good point! No the overview of all cops is not updated. But the docs details for each cop is generated . We have to fix that for sure.
@bbatsov i suggest we also automate that list or add a spec so the CI fails if it's not added to the overview. A reason why it is not yet done is because we have also content which might change in the *.md file. I see some options:

- complete the task of updating documentation with a subtask to link the generated bot in the overview (fastest and easiest solution)
- add a list generator which generates the TOC. So we replace a part of the cops.md on every call of the task. 

Maybe we could also automate the generation of the task so the contribution is easier? We could also take some more points into it so it would for example add an entry to the contribution file ...

**Comment by bbatsov** [comment]
> Maybe we could also automate the generation of the task so the contribution is easier? We could also take some more points into it so it would for example add an entry to the contribution file ...

Ideally, this would be automated, but I'm guessing we'll need some bot automatically committing the docs changes or something like this. I never had to deal with adding commits automatically after merging code changes.

**Comment by bbatsov** [comment]
One more thing - this PR should be updated and rebased I guess.

**Comment by astorije** [comment]
> One more thing - this PR should be updated and rebased I guess.

Done, @bbatsov! :)

**Pull request merged**
