### PR TITLE
Improve handling of super in SymbolProc

### PR DESCRIPTION
**Pull request by lumeet**
Related to #2135, I was just too slow to submit this PR. :) Personally I'm indifferent about the auto-correct strategy. Is this what you were looking for, @bbatsov?

### CODE REVIEW

**Comment by bbatsov** [comment]
> Personally I'm indifferent about the auto-correct strategy

Is there an alternative strategy?

**Comment by lumeet** [comment]
> Is there an alternative strategy?

Sorry. It's all about handling `super` and the rest differently when arguments are being passed.

Only the latter of these now produces an offense (and thus can be auto-corrected).
```ruby
test(arg) { |x| x.inspect }
super(arg) { |x| x.inspect }
```

I'm not quite sure if you wanted it to be this way in https://github.com/bbatsov/rubocop/issues/2135#issuecomment-133421744, and also, why it would be so.

**Comment by bbatsov** [comment]
> Only the latter of these now produces an offense (and thus can be auto-corrected).

I'm not sure how's the `test` example related. 

> I'm not quite sure if you wanted it to be this way in #2135 (comment), and also, why it would be so.

Yeah, I wanted it like this. As for the why - try it out and you'll see why. :-)

**Comment by bbatsov** [comment]
P.S. You'll have to rebase this.

**Comment by lumeet** [comment]
Rebased although I'm still a bit confused. But if everybody else is happy, let's not make it more embarrassing for me. ;)

**Comment by bbatsov** [comment]
Does running this make it clear?

```
class A
  def something(x)
    yield(x)
  end
end

class B < A
  def something(x)
    puts x
    super(x, &:upcase)
  end
end

p B.new.something('aaa')
```

**Comment by lumeet** [comment]
That part is clear. It's the inconsistency between `super` and the rest that I'm thinking of.

```ruby
def test(arg)
  yield arg
end

p test('aaa', &:upcase) # no offense
p test('aaa') { |x| x.upcase } # no offense
```

...and in the case of `super`:
```ruby
super(x, &:upcase) # no offense
super(x) { |y| y.upcase } # OFFENSE
```

**Comment by bbatsov** [comment]
```
p test('aaa') { |x| x.upcase }
```

Should produce an offense - if it currently doesn't, that's a bug. I guess I didn't understand your original remark.

**Comment by bbatsov** [comment]
@lumeet Ping :-)

**Comment by lumeet** [comment]
It seems intentional that the case in question has previously been accepted so I added a new change line to changelog.

**Comment by bbatsov** [comment]
> It seems intentional that the case in question has previously been accepted

Pretty sure it was an oversight on my part. I think I wrote this cop originally.

**Comment by bbatsov** [comment]
Or if I had something in mind - I've totally forgotten it. :-)

**Pull request merged**
