### PR TITLE
Floating headers in HTML output

### PR DESCRIPTION
**Pull request by mattparlane**
Hi there.

I recently ran Rubocop over a decent sized existing project and it worked great, but I found it a minor pain trying to figure out what file a particular offence related to. A lot of offences are similar, for example favoring `.` over `::` for static method calls, and I found myself searching the HTML output for files which committed that offence and if a file had (say) 30 offences (not uncommon), I would have to scroll up a long way to figure out which file I needed to change.

This PR is my first attempt and I'm aware it's not complete/polished, but I have found it very helpful and I was hoping to start a discussion about the merits of this kind of feature.

Thanks!

### CODE REVIEW

**Comment by bbatsov** [comment]
I think this would be useful, so I'd accept a polished version of this PR.

**Comment by mattparlane** [comment]
Great, thanks for that. Any hints on what kind of polish? Obviously making the test suite pass would be step 1, but what else? Have you tried it in a browser? What did you think of the UI?

**Comment by mattparlane** [comment]
Also, what level of browser support do you deem acceptable? For example, the classList API does not work in IE9 and below. I will try to make it only progressive enhancement, ie it should retain the current behaviour in all browsers.

**Comment by bbatsov** [comment]
> Great, thanks for that. Any hints on what kind of polish? Obviously making the test suite pass would be step 1, but what else? Have you tried it in a browser? What did you think of the UI?

A changelog will be needed as well. Haven't had time to play with it, so you can just post a screenshot/animated gif.

I'm fine with not supporting IE9 as I doubt many devs are using it.

**Comment by mattparlane** [comment]
Alright, I've tidied up the formatting, added some comments, tested in IE (it works), and updated the test suite. Pull?

**Comment by bbatsov** [comment]
You'll have to rebase on top of the current `master`.

**Pull request closed without merging**
