### PR TITLE
Add spaces as EnforcedStyle to SpaceInsideParens.

### LINKED ISSUE #5666: Enforce spaces in parentheses.
Is there any way to enforce spaces in parentheses? It looks like the only option is to ensure there are _no_ spaces.

And, if not, is this something that you would consider merging in as an config option if I  create a PR for  it?

For support, we use ESLint for our mobile application and it supports this as a configuration, as can be seen [here](https://eslint.org/docs/rules/space-in-parens#always).

Thanks!

### PR DESCRIPTION
**Pull request by joshuapinter**
**Fixes #5666.**

## Add config option for Style/SpaceInsideParens Cop to enforce spaces.

Simply supply `EnforcedStyle: space` in your rubocop.yml configuration and instead of enforcing no spaces inside parens, it will enforce spaces.

Even supports auto-correct!

Stylistic choice, to be sure, but one that can help alleviate cluttered code and parentheses hell.

## Add Layout/SpaceInsideParens to default.yml.

This defaults the EnforcedStyle to `no_space` and then lists the supported styles, including `space`.

## Code formatting to match rubocop style.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `rake default` or `rake parallel`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
Ping us when the build is green and this is ready for review.

**Comment by Drenmi** [comment]
You need to finish the checklist (add `CHANGELOG` entry and regenerate documentation) before I can review. 🙂

**Comment by joshuapinter** [comment]
Will do! Sorry, we started using it in our codebase and it's working great so this got pushed down the to-do pile. :)

**Comment by bbatsov** [comment]
@joshuapinter Fair enough. Let us know when you decide to pick up it up again.

**Comment by joshuapinter** [comment]
@bbatsov Will do. Should be next week after we catch up on a few things.

**Comment by joshuapinter** [comment]
Hey Guys,

I've added an entry to `CHANGELOG` and fixed a few issues but when I try and re-generate the docs, I'm hitting this error: 

```bash
bundle exec rake generate_cops_documentation
rake aborted!
NoMethodError: undefined method `type' for 68576:Fixnum
/Users/joshuapinter/.rbenv/versions/2.2.0/bin/bundle:23:in `load'
/Users/joshuapinter/.rbenv/versions/2.2.0/bin/bundle:23:in `<main>'
Tasks: TOP => generate_cops_documentation => yard_for_generate_documentation
(See full trace by running task with --trace)
```

Any ideas?

Thanks.

**Comment by joshuapinter** [comment]
Figured out what the issue was.

I was running Ruby 2.2.0 in my rbenv.

Changing my local rbenv to use Ruby 2.5.0 fixed the issue.

I regenerated the docs, resolved conflicts and pushed. 

Just waiting on tests to pass now.

Btw, I don't think I can squash my commits now that I've created this PR but I think you can do that on your side when you merge this in. Correct me if I'm wrong, though, and let me know how to do it. 

Thanks!

**Comment by joshuapinter** [comment]
Boom! Checks passing. We should be good to go!

**Comment by bbatsov** [comment]
LGMT! 👍

**Comment by joshuapinter** [comment]
👍

**Pull request merged**
