### PR TITLE
[FIX] Change Lint/UselessOptionalArgument to Style/OptionalArguments and do not autocorrect

### PR DESCRIPTION
**Pull request by rrosenblum**
Turns out that I was wrong with this functionality. It is possible to call a method with optional arguments at the beginning, and only declare the required parameters. Ruby has a very awkward implementation for optional args at the beginning of a method. The cop should still exist, but it should not auto-correct as this could change functionality.

This is by far some of the weirdest functionality that I can think of.

```ruby
[1] pry(main)> def foo(a = 1, b = 2, c, d)
[1] pry(main)*   puts a, b, c, d
[1] pry(main)* end  
=> :foo
[2] pry(main)> foo
ArgumentError: wrong number of arguments (0 for 2..4)
from (pry):1:in `foo'
[3] pry(main)> foo('a', 'b')                                                                                                                                                      
1
2
a
b
[4] pry(main)> foo('a', 'b', 'c')
a
2
b
c
[5] pry(main)> foo('a', 'b', 'c', 'd')
a
b
c
d
```

### CODE REVIEW

**Comment by bbatsov** [comment]
Guess we should make it a Style cop then.

**Comment by bbatsov** [comment]
And we should add an entry in the style guide advising against such obscure practices.

**Comment by rrosenblum** [comment]
I had been thinking the same thing about needing to change this to a Style cop. 

I will work on a style guide entry.

**Comment by bbatsov** [comment]
:+1: Excellent!

**Pull request merged**
