### PR TITLE
Legend of the raven's roar

### PR DESCRIPTION
**Pull request by alexdowad**

### CODE REVIEW

**Comment by jonas054** [comment]
:+1: Looks good!

**Comment by jonas054** [comment]
@alexdowad I think you forgot "Fix" in one of the commit messages.

**Comment by alexdowad** [comment]
> I think you forgot "Fix" in one of the commit messages.

Whoops!

**Comment by alexdowad** [comment]
Thanks @jonas054! Fixed.

**Comment by bbatsov** [comment]
:+1: Looks good.

**Pull request merged**
