### PR TITLE
Feature: Allow exclusion of lines matching pattern from indentation

### PR DESCRIPTION
**Pull request by jfelchner**
This change allows for more fine-grained control over which lines indentation is required.  It isn't frequent, but there are occasionally times when the requirement for indentation doesn't quite fit in with the code style you're trying to achieve.

I wasn't entirely sure on what I wanted to do here, however once I saw the change to the `LineLength` cop which added the `IgnoredPatterns` option, I knew that's what I wanted for `IndentationWidth`.

This PR extracts the `IgnoredPatterns` logic out into a mixin and then adds that to the `IndentationWidth` cop.

I would recommend reviewing by commit rather than looking at the full diff.  The change itself was very minor, however I did a little refactoring to alleviate some rubocop errors.

The end result is that you can have a config like so:

```yaml
Style/IndentationWidth:
  Width: 2
  IgnoredPatterns:
    - '^\s*module'
    - '^\s*if'
```

And the following will not throw errors

```ruby
module Rubocop
class  Foo
  def bar
    if true
                        puts 'true'
    else
      puts 'false'
    end
  end
end
end
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
The changes look good but this should be squashed to 2 or 3 commits on top of the current `master`.

**Comment by jfelchner** [comment]
@bbatsov definitely can do. I just wanted to make it easier for you to review.

**Comment by bbatsov** [comment]
I appreciate this!

**Comment by jfelchner** [comment]
@bbatsov squashed to 3 commits which I thought was the minimum to tell a good code story.

I also added better documentation for `IndentationWidth` as it was a little lacking.

Hope this is acceptable!

**Comment by jfelchner** [comment]
BTW, seems like we're getting close to `0.48.0`? 😬

**Comment by bbatsov** [comment]
Looks good, but you'll have to rebase again.

0.48 is right around the corner. :-)

**Comment by jfelchner** [comment]
@bbatsov there ya go!

**Pull request merged**
