### PR TITLE
Update doc comments in Count cop to match behavior

### PR DESCRIPTION
**Pull request by cltatman**
Seems like the inline docs for this cop diverged - this updates the comments to match behavior.

### CODE REVIEW

**Comment by bbatsov** [comment]
Thanks for spotting this. Remove the changelog entry - only user-visible changes are reflected there.

**Comment by cltatman** [comment]
@bbatsov Updated to remove changelog entry

**Comment by bbatsov** [comment]
You should also squash the two commits into one.

**Comment by cltatman** [comment]
@bbatsov Squashed commits

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
