### PR TITLE
[Fix #3248] Support 'ruby-' prefix in .ruby-version

### LINKED ISSUE #3248: Unable to run Rubocop
I just upgraded Rubocop to the latest version, but when I try to run it now, I receive the error:

```
➜  bundle exec rubocop
Error: Unknown Ruby version 0.0 found in `.ruby-version`.
Known versions: 1.9, 2.0, 2.1, 2.2, 2.3
```

This behaviour started after the upgrade.
--------

## Expected behavior
I expect Rubocop to work

## Actual behavior
It spits out this error. Worked fine before the upgrade.

## Steps to reproduce the problem
Have Ruby 2.2.5 installed, and upgrade from `0.40.0` to `0.41.1`
Then use the command `bundle exec rubocop --auto-gen-config` or just `bundle exec rubocop`
Running the `-V` command works for some reason.

## RuboCop version
```
$ rubocop -V
0.41.1 (using Parser 2.3.1.2, running on ruby 2.2.5 x86_64-darwin15)
```

### PR DESCRIPTION
**Pull request by tjwp**
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by aviflax** [comment]
I’m having the same problem this is intended to solve, but I’m using JRuby, so my prefix in `.ruby-version` is `jruby`. It doesn’t seem like this change will fix the problem for JRuby users.

**Comment by tjwp** [comment]
What's the right thing to do for JRuby with regard to `.ruby-version`? Is it to ignore `.ruby-version` and always use `TargetRubyVersion` from the configuration?

**Comment by bquorning** [comment]
@aviflax The problem isn’t that the prefix is `jruby` – the regex will match that just fine. I guess the problem rather is that the jruby version numbers don’t match the MRI version numbers. If you’re using the most recent version of jruby, RuboCop will now set `target_ruby_version` as `9.1`, while its `KNOWN_RUBIES` are limited to `[1.9, 2.0, 2.1, 2.2, 2.3]`. That may be a problem indeed.

**Comment by bquorning** [comment]
> What's the right thing to do for JRuby with regard to .ruby-version? Is it to ignore .ruby-version and always use TargetRubyVersion from the configuration?

I think we should switch the precedence, so `.ruby-version` only gets read if `TargetRubyVersion` isn’t configured.

**Comment by aviflax** [comment]
@bquorning yes, good point. My file’s current value is `jruby-9.1.2.0` which is perfectly valid for rbenv.

> I think we should switch the precedence, so `.ruby-version` only gets read if `TargetRubyVersion` isn’t configured.

+1 makes sense to me.

But also, IIRC until this change, Rubocop probably had some kind of sensible default if `TargetRubyVersion` isn’t configured? So it seems extreme for Rubocop to just die if it doesn’t understand the value in `.ruby-version`. I’d think it’d be better for it to emit a warning and just continue with a default setting.

**Comment by tjwp** [comment]
I opened https://github.com/bbatsov/rubocop/pull/3261 if that helps to resolve the situation.

**Pull request merged**
