### PR TITLE
[Fix #4521] Move naming related cops into their own `Naming` department

### LINKED ISSUE #4521: Should there be a `Naming` namespace?
I liked the separation of `Layout` from `Style`. It makes it easier to get an overview of the cops and their jurisdictions, and it also helps prevent the creation of cops that check too many things.

In that spirit, I was wondering if we should also split out `Naming`, which seems to have about as many cops as `Layout` does.

WDYT?

### PR DESCRIPTION
**Pull request by Drenmi**
In an effort to split up the generic `Style` department, this change moves naming related cops to their own. It also renames `OpMethod` to `BinaryOperatorParameterName`.

**Note: if you're reading this because your configuration broke after upgrading, use the mapping below to update your .rubocop.yml**

 - `Style/AccessorMethodName` -> `Naming/AccessorMethodName`
 - `Style/AsciiIdentifiers` -> `Naming/AsciiIdentifiers`
 - `Style/ClassAndModuleCamelCase` -> `Naming/ClassAndModuleCamelCase`
 - `Style/ConstantName` -> `Naming/ConstantName`
 - `Style/FileName` -> `Naming/FileName`
 - `Style/HeredocDelimiterCase` -> `Naming/HeredocDelimiterCase`
 - `Style/HeredocDelimiterNaming` -> `Naming/HeredocDelimiterNaming`
 - `Style/MethodName` -> `Naming/MethodName`
 - `Style/OpMethod` -> `Naming/BinaryOperatorParameterName`
 - `Style/PredicateName` -> `Naming/PredicateName`
 - `Style/VariableName` -> `Naming/VariableName`
 - `Style/VariableNumber` -> `Naming/VariableNumber`

-----------------

Before submitting the PR make sure the following are checked:

* [X] Wrote [good commit messages][1].
* [X] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [X] Used the same coding conventions as the rest of the project.
* [X] Feature branch is up-to-date with `master` (if not - rebase it).
* [X] Squashed related commits together.
* [X] Added tests.
* [X] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [X] All tests(`rake spec`) are passing.
* [X] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [X] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [X] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
Seems to me you forgot to update `config.rb`. 

> Note: if you're reading this because your configuration broke after upgrading, use the mapping below to update your .rubocop.yml

It exists exactly to avoid such issues. :-) Maybe we should add a checkbox in the PR template, so that people doing renamings/deletions would know to update it.

**Comment by bbatsov** [comment]
Looking the names of the cops and the fact that they now have a naming prefix it might be good to unify them a bit - e.g. `AsciiIdentifiers` can be just `Identifiers`, `ConstantName` -> `Constant` and so on.

**Comment by Drenmi** [comment]
> Seems to me you forgot to update `config.rb`

I recall seeing this at some point, but had completely forgotten it exists. 🙂 

> Looking the names of the cops and the fact that they now have a naming prefix it might be good to unify them a bit - e.g. AsciiIdentifiers can be just Identifiers, ConstantName -> Constant and so on.

I am a bit hesitant to rename to more generic names at this point. In the case of the heredoc delimiter cops, I used the `HeredocDelimiters` at first, but this later forced me to rename when I added another, separate cop related to heredoc delimiters. 😅 

For the naming cops, I think the ones checking for case, and the ones checking for identifier names, should be separated, because one can be auto-corrected and one can not. So it won't lead to strange situations where a cop auto-corrects, and then still generates an offense.

**Comment by Drenmi** [comment]
@bbatsov: Entries added to `config.rb`. (I omitted the heredoc cops, since they aren't released yet.) I think you mentioned at some point that you want a better way to handle this?

**Comment by bbatsov** [comment]
> I think you mentioned at some point that you want a better way to handle this?

True. I think this should ideally be part of cop API and when something is renamed the cop should simply keep track of its old names.

**Comment by bbatsov** [comment]
> For the naming cops, I think the ones checking for case and the ones checking for identifier names should be separated, because one can be auto-corrected and one can not. So it won't lead to strange situations where a cop auto-corrects, and then still generates an offense.

Sure. My point was mostly for uniformity - e.g. it's unclear what `AsciiIdentifiers` means at all today. Probably it should be at least `IdentifierName` (or something like this). Same with `VariableNumber`. Anyways, the PR is in a good shape right now, so I'll merge it.

**Pull request merged**
