### PR TITLE
Fix build error in manual/cops_rails.md

### PR DESCRIPTION
**Pull request by koic**
This PR fixes the following error on Travis CI.

```console
$ bundle exec rake documentation_syntax_check generate_cops_documentation

(snip)

-### Important attributes
+### Configurable attributes

-Attribute | Value
---- | ---
-Include | db/migrate/\*.rb
+Name | Default value | Configurable values
+--- | --- | ---
+Include | `db/migrate/*.rb` | Array

(snip)

.travis.rb:25:in `sh!': `bundle exec rake documentation_syntax_check generate_cops_documentation` is failed (RuntimeError)
	from .travis.rb:40:in `<main>'
The command "ruby .travis.rb" exited with 1.
```

https://travis-ci.org/bbatsov/rubocop/jobs/307082624#L708-L716

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests(`rake spec`) are passing.
* [x] The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
I'm puzzled. Didn't I just merge one PR fixing this?

**Comment by bbatsov** [comment]
https://github.com/bbatsov/rubocop/commit/ba6597eed988de01d73f261e5077df099007fe35

**Comment by koic** [comment]
It seems that regression was born by merging https://github.com/bbatsov/rubocop/commit/2ae72597023c69d0fbbb2d620eb41d4d37c1d355#diff-c9c43dc51d563f503df8494fc58ea077L712 after ba6597e.

**Comment by garettarrowood** [comment]
I think we are good now, though. Current master build is green.

**Comment by koic** [comment]
Oops, this is my mistake. Current master branch has succeeded. I will close this PR 💦 
@garettarrowood Thanks for letting me know.

**Pull request closed without merging**
