### PR TITLE
Add autocorrect ability to Style/OptionHash cop

### PR DESCRIPTION
**Pull request by zverok**
Pretty trivial, and useful for updating large outdated codebases.

### CODE REVIEW

**Comment by pocke** [comment]
I think the autocorrection should be disabled by default because this rewriting is not safe.
For example:


```ruby
def foo(options = {})
  p options
end

def bar(**options)
  p options
end

foo('a' => 1) # => {'a' => 1}
bar('a' => 1) # => wrong number of arguments (given 1, expected 0) (ArgumentError)
```

**Comment by Drenmi** [comment]
Hm. This just changes from one flavour of options hash to another one? 🤔 The recommendation is to use keyword arguments, e.g.:

```ruby
def foo(options = {})
  @bar = options[:bar] || 1
  @foo = options[:baz] || 2
end
```

can be replaced with:

```ruby
def foo(bar: 1, baz: 2)
  @bar = bar
  @baz = baz
end
```

**Comment by zverok** [comment]
@pocke Well, the cop is disabled totally by default config. So I believe if you enable it, you _probably_ will be OK with auto-correct.
@Drenmi well, you question makes sense, of course. 
So, this autocorrect is not the best way to do to "just make Rubocop happy", all in all. 
What I was thinking, though, is "at least make it more modern" is a good thing too. 
Also, probably introducing more advanced cop, which would catch the situation like "You have `**options`, but only use `options[:foo]` and `options[:bar]`, please make it `bar:, baz:` (with autocorrect, if possible), could be a good step forward.

**Comment by pocke** [comment]
>  Well, the cop is disabled totally by default config. So I believe if you enable it, you probably will be OK with auto-correct.

I do not think so. If users enable it, they expect this cop detects bad usage of option argument. But they do not expect code to be broken by auto-correction.


BTW, I think this cop should be enabled by default.


> So, this autocorrect is not the best way to do to "just make Rubocop happy", all in all.
What I was thinking, though, is "at least make it more modern" is a good thing too.
Also, probably introducing more advanced cop, which would catch the situation like "You have **options, but only use options[:foo] and options[:bar], please make it bar:, baz: (with autocorrect, if possible), could be a good step forward.

👍

**Comment by zverok** [comment]
OK, all concerns make sense here.

**Pull request closed without merging**
