### PR TITLE
Add NonLocalExitFromIterator lint and fix other cops complained by it

### PR DESCRIPTION
**Pull request by ypresto**
I found bug in our product that aborts iterator unexpectedly, with return statement.

```
def iterate
    array.each do |item|
        return if item.skip? # oh, no! it returns from "iterate" method!
        ...
    end
end
```

NonLocalExitFromIterator detects misused return statements in iterator block.
It uses heuristic way to distinguish intended use of return or not:

- No return value.
  Because where `next` should be used tend to have no return value (but of `map`).
- Method chain.
  E.g. `array.each do |item| ... end`  and not `before_fork do |server| ... end`.
- Block with arguments.
  E.g. not `foobar.with_lock do ... end`.

Cops affect with this bug also found: LiteralInInterpolation and AssignmentInCondition.
UnneededCapitalW is false-positive, but is still easy to use `any?` instead.

Thanks for great product!

### CODE REVIEW

**Comment by ypresto** [comment]
jshint has `/* falls through */` comment to allow `case` without `break`.
This would be better to have comment like `# non-local exit`, but I have no idea how to impl it...

**Comment by jonas054** [comment]
:+1: I like this cop. Just had a few comments.

**Comment by bbatsov** [comment]
Small remark from me - please, capitalize commit messages.

**Comment by ypresto** [comment]
> `# rubocop:disable Lint/NonLocalExitFromIterator`

I was thinking it is verbose a little, but it is simple enough for something rarely used :)

Thanks for reviewing! Fixed for all comments. Rebased.

**Comment by bbatsov** [comment]
@ypresto You'll have to rebase again. Sorry about this.

**Comment by ypresto** [comment]
re-rebased!

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
