### PR TITLE
[Fix #4052] Improves error message for casecmp

### LINKED ISSUE #4052: Misleading error message: Use casecmp instead of downcase ==
RuboCop warns not to do case-insensitive string comparison by using `downcase` for performance reasons: http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Performance/Casecmp

The output message for this pattern is `Use casecmp instead of downcase ==`, but this is misleading. `casecmp`, as a comparison operator, returns -1, 0, or 1, all of which are truthy, rather than `true` or `false`. Therefore a direct replacement of `a.downcase == b.downcase` with `a.casecmp(b)` will have incorrect behavior.

RuboCop autocorrect does correctly replace this `a.casecmp(b).zero?`, but the error message should indicate that the call to `zero?` is also needed.

Maybe: `Use casecmp and zero? instead of downcase ==`

```
$ rubocop -V
0.40.0 (using Parser 2.3.1.2, running on ruby 2.3.1 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by harman28**
Improves the `casecmp` error message as outlined in #4052

### CODE REVIEW

**Comment by mikegee** [comment]
Unfortunately, those lines in the specs are now too long:

```
spec/rubocop/cop/performance/casecmp_spec.rb:89:81: C: Line is too long. [92/80]
      expect(cop.messages).to eq(["Use `casecmp` and `zero?` instead of `#{selector} ==`."])
                                                                                ^^^^^^^^^^^^
spec/rubocop/cop/performance/casecmp_spec.rb:95:81: C: Line is too long. [92/80]
      expect(cop.messages).to eq(["Use `casecmp` and `zero?` instead of `== #{selector}`."])
                                                                                ^^^^^^^^^^^^
spec/rubocop/cop/performance/casecmp_spec.rb:102:81: C: Line is too long. [92/80]
      expect(cop.messages).to eq(["Use `casecmp` and `zero?` instead of `#{selector} ==`."])
                                                                                ^^^^^^^^^^^^
```

I suppose a line break is the easiest fix.

**Comment by bbatsov** [comment]
I don't think the new message solves the problem. Wouldn't it be better to have `x.casecomp(y).zero?` in the message directly? Ideally with the real expressions from the code.

**Comment by harman28** [comment]
@bbatsov I'm not sure how this can be achieved. How can I retrieve the real expressions?

**Comment by bbatsov** [comment]
You can use something like `node.loc.expression`. There are numerous examples of retrieving the underlying source code from the node in the codebase.

**Comment by bbatsov** [comment]
Guess I'll close this due to lack of activity.

**Comment by sekrett** [comment]
I believe it is better to merge this without real expressions, still better than now. Also the documentation must be corrected.

**Comment by AlexWayfer** [comment]
Oh-oh, here everything is bad.

The `String#casecmp` method does not work with Unicode (even in Ruby 2.4.1), this is written in the [documentation](http://ruby-doc.org/core-2.4.1/String.html#method-i-casecmp).

Example:

```ruby
'Привет'.casecmp('привет') # => -1
```

There is a method `String#casecmp?`, which [works with Unicode](http://ruby-doc.org/core-2.4.1/String.html#method-i-casecmp-3F).

Example:

```ruby
'Привет'.casecmp?('привет') # => true
```

That is, even `casecmp.zero?` will not work correctly for Unicode strings.

Please correct the message.

**Comment by AlexWayfer** [comment]
I created the issue #4277, because this is a slightly different problem than the one that the given PR solves.

**Pull request closed without merging**
