### PR TITLE
Add Security/YAMLLoad

### PR DESCRIPTION
**Pull request by cyberdelia**
Add ``Security/YAMLLoad``cop, covering the security issues around the use of ``YAML.load``: https://ruby-doc.org/stdlib-2.3.3/libdoc/yaml/rdoc/YAML.html#module-YAML-label-Security

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Used the same coding conventions as the rest of the project.
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] All tests are passing.
* [x] The new code doesn't generate RuboCop offenses.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

### CODE REVIEW

**Comment by lucascaton** [comment]
@cyberdelia this cop looks great, thanks for that!
However, I can't seem to get `safe_load` working for all scenarios:

It works well with:

```ruby
# String
yml = 'string'.to_yaml # => "--- string\n...\n"
YAML.load(yml)         # => "string"
YAML.safe_load(yml)    # => "string"

# Integer
yml = 1.to_yaml     # => "--- 1\n...\n"
YAML.load(yml)      # => 1
YAML.safe_load(yml) # => 1

# Array
yml = [1, "string"].to_yaml # => "---\n- 1\n- string\n"
YAML.safe_load(yml)         # => [1, "string"]
YAML.load(yml)              # => [1, "string"]
```

It doesn't work with:

```ruby
# Hash
yml = { a: 1 }.to_yaml # => "---\n:a: 1\n"
YAML.load(yml)         # => {:a=>1}
YAML.safe_load(yml)    # Psych::DisallowedClass: Tried to load unspecified class: Symbol

# Time class
yml = Time.now.to_yaml # => "--- 2017-01-21 16:43:11.160841000 +10:00\n...\n"
YAML.load(yml)         # => 2017-01-21 16:43:11 +1000
YAML.safe_load(yml)    # Psych::DisallowedClass: Tried to load unspecified class: Time

# Date class
yml = Date.today.to_yaml # => "--- 2017-01-21\n...\n"
YAML.load(yml)           # => Sat, 21 Jan 2017
YAML.safe_load(yml)      # Psych::DisallowedClass: Tried to load unspecified class: Date
```

It might be related to [this issue](https://github.com/ruby/psych/issues/262)?

Thanks.

cc: @bbatsov

**Comment by backus** [comment]
You need to whitelist classes that aren't in its default list of supported primitives.

```ruby
require 'yaml'

items = [
  true,
  false,
  nil,
  123,
  "string",
  [],
  {}
]

YAML.safe_load(YAML.dump(items)) # => [true, false, nil, 123, "string", [], {}]

items << :symbol

dump = YAML.dump(items)
YAML.safe_load(dump, [Symbol])   # => [true, false, nil, 123, "string", [], {}, :symbol]
YAML.safe_load(dump)             # !> Tried to load unspecified class: Symbol (Psych::DisallowedClass)
```

**Comment by lucascaton** [comment]
@backus you're right, thank you!

**Comment by ixti** [comment]
Also, note that `safe_load` disallows to load aliases. Consider we have following YAML data:

``` yaml
default: &default
  pool: 5

production:
  <<: *default
  db: 10
  driver: hiredis
```

If you will try to load it as `YAML.safe_load(data)` it will fail with:

    Psych::BadAlias: Unknown alias: default

So, you will need to pass `true` as (!) 4th argument:

``` ruby
YAML.safe_load(data, [], [], true)
```

You might question what the hell is 3rd argument for? It's a whitelist of allowed symbols. If it's empty - all symbols are allowed, but `Symbol` class must be whitelisted in classes whitelist. So, imagine we would have driver specified as symbol:

``` yaml
default: &default
  pool: 5

production:
  <<: *default
  db: 10
  driver: :hiredis
```

Attempt to load it would fail with:

    Psych::DisallowedClass: Tried to load unspecified class: Symbol

So in order to load the above you would need:

``` ruby
YAML.safe_load(data, [Symbol], [], true)
```

You may also limit which symbols are allowed:

``` ruby
YAML.safe_load(data, [Symbol], [:hiredis], true)
```

**Pull request merged**
